### PR TITLE
Incorrect sample codes in docs for Mocks

### PR DESCRIPTION
**Pull request by williamli**
```const { ApolloServer } = require('apollo-server');```
should be 
```const { ApolloServer, gql } = require('apollo-server');```

The functions in `mocks` would be used when no resolver in `resolvers` is specified only when `mockEntireSchema: false`.

TODO:

* [ ] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by williamli** [comment]
Do I need to update CHANGELOG even for just documentation updates?

**Comment by JakeDawkins** [comment]
Hey @williamli! Thanks for the PR!

Instead of adding `mockEntireSchema`, why don't we leave it out, and instead mention that if you add a **Type** resolver to the mocks list, it

**Comment by JakeDawkins** [comment]
Oops! didn't mean to close :)

**Comment by evans** [comment]
@williamli Thank you so much!

**Pull request merged**
