### PR TITLE
Release 3.0

### PR DESCRIPTION
**Pull request by glasser**
As with [release PRs in the past](https://github.com/apollographql/apollo-server/issues?q=label%3A%22%F0%9F%8F%97+release%22+is%3Aclosed), this is a PR tracking a `release-3.0` branch for an upcoming release of Apollo Server. 🙌  

The progress of this release is being tracked in the [Apollo Server 3 project](https://github.com/apollographql/apollo-server/projects/6), as well as on this issue.

We have released Apollo Server `3.0.0`! It is currently on the `next` npm dist-tag rather than the `latest` dist-tag, so it is not installed by default when you run `npm install apollo-server`.  We intended to promote it to `latest` in mid-July pending further feedback.

The current version is `3.0.0`. You can install it with `npm install apollo-server@3.x`.

When this version is officially released onto the `latest` npm tag, this PR will be merged into `main`.

This is the release branch for Apollo Server 3, a major version release!  The theme of this release is making Apollo Server more maintainable and replacing hard-coded external dependencies with the ability for users to install their chosen version of the formerly baked-in dependency.  There are many backwards-incompatible changes, including whole features that have been removed.

The [CHANGELOG](https://github.com/apollographql/apollo-server/blob/release-3.0/CHANGELOG.md) is up to date, and there is now a [migration guide](https://www.apollographql.com/docs/apollo-server/v3/) available. All Apollo Server docs should now be up to date for AS3; AS3 docs are available at https://www.apollographql.com/docs/apollo-server/v3/

While AS3 is mostly about removing complexity and setting the stage for future exciting features, it also has a few new features and capabilities:
- Now that we target Node 12 and up, we can build for the more efficient ES2020 compilation target.
- `apollo-server-lambda` is now built on top of `apollo-server-express` and optionally supports Express middleware
- `apollo-server-fastify` is now compatible with Fastify v3 (instead of Fastify v2)
- Apollo Server 1 had GraphiQL built in as a frontend; Apollo Server 2 had GraphQL Playground. In Apollo Server 3, there's a simple framework-agnostic plugin interface to let you swap in different frontends with one line of code. (Currently Playground is still the default frontend though this may change before 3.0.0.)

### CODE REVIEW

**Comment by darkbasic** [comment]
Any chance to get this simple PR merged in apollo-server 3? https://github.com/apollographql/apollo-server/pull/4167

**Comment by glasser** [comment]
I've released version `3.0.0-preview.2`. As you can see from https://github.com/apollographql/apollo-server/projects/6 this is now feature complete, but not doc complete.

The CHANGELOG entry is up to date for the changes in AS3. However, many docs are still out of date and there is not yet a comprehensive migration guide. Getting docs together is now my first priority.

This preview is also not compatible with `@apollo/gateway`; see  https://github.com/apollographql/federation/pull/819 for the fix.

**Comment by glasser** [comment]
We've released `3.0.0-preview.3`. There are a few small code changes from `preview.2` (you no longer need to call `start()` before the testing helper `executeOperation()`; `GraphQLRequestContext.overallCachePolicy` is `readonly`; the default landing page shows some contents when offline).

The main improvement is that we've completed a draft of the [migration guide](https://release-3-0--apollo-server-docs.netlify.app/docs/apollo-server/migration/)!

There are still some docs tasks remaining (as tracked in the [Docs column](https://github.com/apollographql/apollo-server/projects/6)): rewriting the Playground page, rewriting the subscriptions page, generally overhauling how we document the different library flavors (eg, having an explicit section on "ejecting" from `apollo-server` to `apollo-server-express`), etc. However, with the migration guide complete, it's reasonable to try out the new preview in your app.

**Comment by glasser** [comment]
(Note that while the migration guide starts by saying "Apollo Server 3 is generally available", that won't actually be true until this is merged to main and it shows up on the non-branch-preview docs site :) )

**Comment by glasser** [comment]
@darkbasic Hi, sorry that I missed your comment. AS3 is a major version bump so it needs to contain anything that's a breaking change. #4167 looks interesting but it is not a breaking change, so I don't think it should be a blocker for AS3.

**Comment by glasser** [comment]
`3.0.0-preview.4` is out with two small changes:
- #5384: default landing page plugins support `footer: false`
- #5401: Hapi and Azure Functions have the same default CORS behavior as all other integrations

Docs are also getting much closer to done! We need to land work in progress to document the new landing page plugins, to overhaul how we document the different library flavors, and to update the Subscriptions page.

**Comment by glasser** [comment]
Apollo Server 3 has reached release candidate stage! We've published version `3.0.0-rc.0` of all packages (except `apollo-server-env` where it's `3.2.0-rc.0` because it was already at v3).

Please test it in your app by installing `3.0.0-rc.0` of any apollo-server packages you directly depend on!

Docs are now available at
https://www.apollographql.com/docs/apollo-server/v3/
including a complete migration guide
https://www.apollographql.com/docs/apollo-server/v3/migration/

Our current release plan is that we will release version 3.0.0 to the npm dist tag `next` rather than `latest` and keep this PR open for a little while. This will make it easier to upgrade (eg, other packages can adjust their dependencies without having to depend on prereleases) without making it what is installed by default.  We are currently targeting Tuesday July 6th for that release. Any feedback on ease of migration before then will be very helpful.

**Comment by glasser** [comment]
I published `3.0.0-rc.1`. The only difference is that the version of `apollo-server-env` has changed from `3.2.0-rc.0` to `4.0.0-rc.0`.  (That package isn't versioned in lockstep with the main packages and was already at 3.x; I had previously given it a minor bump but realize it needs a major bump due to removal of some TypeScript global definitions.)

**Comment by glasser** [comment]
I'm planning to release Apollo Server 3.0.0 to the `next` dist-tag (so it won't yet be installed by default with `npm install apollo-server`) in an hour or two.

While we don't foresee needing to take advantage of this, it's possible we may make minorly backwards-incompatible changes to new functionality between the release of 3.0.0 and the promotion to `latest`.

**Comment by glasser** [comment]
We've released version 3.0.0, on the `next` dist-tag! Install it with `npm install apollo-server@3.x`. This PR will remain open for 1-3 weeks until we move AS3 to the `latest` dist-tag and merge `release-3.0` into `main`.

Docs are available at
https://www.apollographql.com/docs/apollo-server/v3/
including a complete migration guide
https://www.apollographql.com/docs/apollo-server/v3/migration/

**Comment by glasser** [comment]
Apollo Server 3.0.0 has now been released and is available on the `latest` dist-tag! The docs site has been updated to show v2 as an old version and v3 as the current version. Thanks to everyone who has contributed!

**Comment by jwoo92** [comment]
@glasser Thank you for the awesome birthday present 😃

**Pull request merged**
