### PR TITLE
[WIP] Fix (#4283 #3582): Union with interfaces issue

### PR DESCRIPTION
**Pull request by mpospelov**
# Purpose

This is a bugfix for #4283 issue

# Root cause

The problem comes from the following optimization https://github.com/apollographql/apollo-server/pull/3582

The idea of optimization is to prevent expanding interfaces if it's possible, the problem that this case also appears where it should not - when types are defined in separate services. 
As a result, this optimization leads to ignoring fetching from external services

Kudos to @id-ilych for finding a solution!
Thanks for your hard work! 🚀 And hope you will find this bug fix useful 😉

### CODE REVIEW

**Comment by id-ilych** [comment]
@abernix Hello 👋 Could you elaborate on the reason this PR is closed?

**Comment by abernix** [comment]
Unintentional closing! Please stand-by: https://github.com/apollographql/apollo-server/issues/4304

**Comment by havenchyk** [comment]
@abernix could you please take a look? we need this soon 😄

**Comment by LucienLee** [comment]
I got the same issue after I upgrade over v0.11.x version. Hope that it can be merged asap!

**Comment by mpospelov** [comment]
This optimization is broken even more than we expected, further fixes are required.
We found 2 more issue with value type interfaces and another case. We have a fix for it but the code needs polishing first, so I'm marking this PR as WIP for now

**Comment by havenchyk** [comment]
@trevor-scheer maybe you can also take a look?

**Comment by trevor-scheer** [comment]
Hey @mpospelov, thank you for hard work on this (and anyone else involved!). I can't guarantee _how_ soon I can give this the attention it deserves, but it's high on my list.

For context, (GraphQL Summit)[https://summit.graphql.com/] is right around the corner and we're all quite busy for the next couple weeks. Hope to see you there!

**Comment by id-ilych** [comment]
Hey @trevor-scheer :wave:
I've created [another branch](https://github.com/apollographql/apollo-server/compare/main...id-ilych:fix-gateway-optimization-for-interface-fields) with slightly modified version of the test to demonstrate the difficulties I currently have with implementing a fix - it seems that behavior of the `splitFields` when dealing with interface as a `parentType` should be different when the interface is the return type of the parent field and when the parent field is of union type with `... on Interface` fragment. That is demonstrated by the following test-cases correspondingly:
* `handles interface-typed field when interface is used on multiple services`
* `handles interface fragments for union-typed field from multiple services`

in `packages/apollo-gateway/src/__tests__/integration/unions-with-value-interfaces-hybrid.test.ts` file.

The issue is that I can't see how those cases can be distinguished based on existing arguments. The gist of the problem is that `possibleTypes` for the interface should be narrowed down to those implementations that are known to the current service when the interface is the return type, and they should not be when the enclosing scope is e.g. a union of a types from different services.

**Comment by id-ilych** [comment]
Hi @trevor-scheer :wave:
Any news? Can you confirm the bug?

**Comment by id-ilych** [comment]
Hi @trevor-scheer @abernix :wave:
I see that the query planner was replaced (https://github.com/apollographql/apollo-server/pull/4534). Does it solve the issue? If not then are there plans to fix it?

**Comment by glasser** [comment]
The gateway code moved to the https://github.com/apollographql/federation repository a few years ago. Sorry for the delay!

**Pull request closed without merging**
