### PR TITLE
Document that formatResponse also gets the query

### PR DESCRIPTION
**Pull request by dandv**

### CODE REVIEW

**Comment by unicodeveloper** [comment]
Hey @dandv you didn't document that in this PR. Any reason why?

**Comment by martijnwalraven** [comment]
Note that the shape of that `query` parameter is likely to change in the next version, so I wouldn't consider this part of the public API yet.

**Comment by dandv** [comment]
@unicodeveloper: I was respecting the doc style and thought that the "per input" part of "per input, response, and errors" refers to the query, since the error or `response` parameters aren't *explicitly* documented either, except by way of example.

But in the light of what @martijnwalraven said, feel free to close the PR without merging.

**Comment by dandv** [comment]
Looks like this change has occurred, and the `query` object no longer has `queryString` and `variables`. What is the current recommended way to log these for every query?

**Comment by dandv** [comment]
Ping? This change breaks logging.

**Comment by dusan-dragon** [comment]
Hi @dandv it was changed again, as a second param you will get request context:
https://github.com/apollographql/apollo-server/blob/8059326ce43a776b6f34e1a6de4cb78da4e4a2b3/packages/apollo-server-core/src/graphqlOptions.ts#L50

**Comment by dandv** [comment]
I've been using this with v2.9.15:

```js
new ApolloServer({
  // ...
  context: async ({ req }) => {
    const request = req.method === 'GET' ? req.query : req.body;  // POST vs. GET
    if (!request.query.startsWith('query IntrospectionQuery'))
      logger.info(`GraphQL query&variables`, {
        query: request.query,
        vars: request.variables,  // TODO: how are variables passed via GET?
      });
  }
});
```

**Pull request closed without merging**
