### PR TITLE
Allow additional Hapi route options to be passed

### PR DESCRIPTION
**Pull request by robinvdvleuten**
This PR adds the functionality to pass additional [route configuration options](https://hapijs.com/api#route-options) when using the plugin with Hapi. In my case for example, I needed to modify the auth options and wasn't be able to do at (unfortunately only CORS options can be passed at the moment). 
It would make the current CORS option obsolete though (as you can see in the test case).

TODO:

* [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by mikl** [comment]
Additional point in favour of this change – with the new `cors` setting in 2.0.0, it doesn’t appear possible to enable the `Access-Control-Allow-Credentials` header, which unfortunately makes it a pain to do local development, since create-react-app and similar usually run on a separate, hot-loading dev-server, and thus CORS is needed to talk to the GraphQL server.

**Comment by maxnachlinger** [comment]
I'm excited for this PR too :) @robinvdvleuten - it might be worth resolving the conflicts in your branch.

**Comment by robinvdvleuten** [comment]
@maxnachlinger good idea, did it immediately 👍

**Comment by robinvdvleuten** [comment]
It would be nice to have a look from one of the maintainers like @evans otherwise I keep fixing merge conflicts 😔

**Comment by evans** [comment]
@robinvdvleuten Really sorry about the delay! We'll merge and publish this right away. Thank you for the PR!

@maxnachlinger Thank you for taking a look as well

**Pull request merged**
