### PR TITLE
Feature: Add HTTP2 support

### PR DESCRIPTION
**Pull request by johman10**
**TODO:**
* [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

**Description:**
This PR makes sure the server starts accepting HTTP2 request by filtering unsupported headers out. I'm very aware that this solution is probably not the correct one but I'm not sure what else there is to do here. The idea to do this comes from https://github.com/apollographql/apollo-server/issues/1533 and I have found myself that this works when used in combination with `apollo-server-fastify`. If there are better ways of getting HTTP2 support into the project, please let me know.

About tests, I can't find any for the method I'm changing here. So I didn't add any. Please correct me if this is wrong.

**Use case:** 
This is very useful when using a server framework that support HTTP2, which is a growing set.

**Could this be a plugin?**
I don't see any way to make this into a plugin. But perhaps it can be. I'm not very familiar with the architecture here. Could this method perhaps be overwritten via a plugin?

**Is there a workaround?**
As far as I know, there is non at this point in time.

### CODE REVIEW

**Comment by SoyYoRafa** [comment]
Hi, why has this PR been open for 6 months without merging?

**Comment by johman10** [comment]
@abernix @martijnwalraven I understand you might be busy, but could I receive some feedback on this? It would be greatly appreciated. :)

**Comment by gkartalis** [comment]
Hello,

any updates on this PR? It would be greatly appreciated! 🚀

**Comment by krisread** [comment]
Our company assumed this would work, then went down the path, and realized Apollo does not support it yet.  This looks pretty much like someone got it pretty far along, any updates?  As I understood it GraphQL and Apollo are pretty protocol/transport agnostic?

**Comment by stefanholzapfel** [comment]
Thanks for your work, but for me the changes proposed in the pull request ar not working (apollo-server-express 2.0.15).

And should that also work for ws subscriptions (via apollo.installSubscriptionHandlers)?

**Comment by hoebbelsB** [comment]
any news on this one?

**Comment by Seemspyo** [comment]
this Error invoked by `node-fetch` library, which check every header keys and values to be proper to HTTP/1.1 schema.

Apollo currently using `node-fetch`'s `Header` class. When call `append` method on `Header` instance, it checks headers key and value, and they currently using RegExp like below.

```js
/**
 * headers.js
 *
 * Headers class offers convenient helpers
 */

const invalidTokenRegex = /[^\^_`a-zA-Z\-0-9!#$%&'*+.|~]/;
const invalidHeaderCharRegex = /[^\t\x20-\x7e\x80-\xff]/;

function validateName(name) {
	name = `${name}`;
	if (invalidTokenRegex.test(name) || name === '') {
		throw new TypeError(`${name} is not a legal HTTP header name`);
	}
}

function validateValue(value) {
	value = `${value}`;
	if (invalidHeaderCharRegex.test(value)) {
		throw new TypeError(`${value} is not a legal HTTP header value`);
	}
}
```

And that regexp doesn't allows `:`.

I think just filtering all the HTTP/2 headers like `:method`, `:path` won't work since these are required fields.

**Comment by Seemspyo** [comment]
After spending a long time to digging down the source code, I decided to make a simple workaround.

node-fetch-http2-header-workaround.js
```js
import { Headers } from 'node-fetch';

/**
 * Find the key in the map object given a header name.
 *
 * Returns undefined if not found.
 *
 * @param   String  name  Header name
 * @return  String|Undefined
 */
function find(map, name) {
	name = name.toLowerCase();
	for (const key in map) {
		if (key.toLowerCase() === name) {
			return key;
		}
	}
	return undefined;
}

Object.defineProperty(Headers.prototype, 'append', {
    value(name, value) {
        const MAP = Object.getOwnPropertySymbols(this).find(s => s.toString().includes('(map)'));
        if (MAP !== undefined) return;

        const map = this[MAP];

        const key = find(map, name);
        if (key !== undefined) {
            map[key].push(value);
        } else {
            map[key][name] = [ value ]
        }
    }
});
```

and import top of file like

```js
import './node-fetch-http2-header-workaround.js';
```

This will suppress the error like `TypeError: :method is not a legal HTTP header name` for now.

**Comment by fataltrace** [comment]
Any updates?

**Comment by dbousamra** [comment]
Hi all. Any updates on this?

**Comment by glasser** [comment]
My guess is that AS4 supports http/2 because we no longer convert requests to node-fetch Requests...

**Comment by glasser** [comment]
My guess is that AS4 supports http/2 because we no longer convert requests to node-fetch Requests. I'm closing this issue because this fix no longer is relevant to making http/2 work.

I would love to get a PR with a test that demonstrates that Apollo Server supports http/2 now, though! Not sure if any of the clients we use in our integration tests support http/2 but I guess you could just do one or two one-off tests.

**Pull request closed without merging**
