### PR TITLE
Enables parsing of application/hal+json as JSON

### PR DESCRIPTION
**Pull request by janhartmann**
This pull requests enables JSON parsing of content type `application/hal+json`.

https://en.wikipedia.org/wiki/Hypertext_Application_Language

TODO:

* [X] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [X] Make sure all of the significant new logic is covered by tests
* [X] Rebase your changes on master so that they can be merged easily
* [X] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by martijnwalraven** [comment]
Thanks, this looks good! I'm happy you also added a new test.

**Comment by jonbjk** [comment]
I think the solution proposed in https://github.com/apollographql/apollo-server/pull/1645
is more general, since it would allow parsing of any JSON response, by making the contentType configurable. In that way we can support for example "application/vnd.api+json" as well as "application/hal+json".

**Comment by janhartmann** [comment]
I agree, we also to support different casing.

As og today, if the content type sent back is “Application/Json” it will not parse either. Might need another issue

**Comment by jonbjk** [comment]
In #1645 I added a field jsonContentType that defaults to "application/json", but that the developer can override (a bit like the baseUrl). I think that that is a simple and flexible solution.
If you look at for example: https://swagger.io/docs/specification/media-types/
a content type such as "application/vnd.mycompany.myapp.v2+json"
is also valid.

**Pull request merged**
