### PR TITLE
Add support for human-readable maxAge

### LINKED ISSUE #2488: Add

### PR DESCRIPTION
**Pull request by mxstbr**
TODO:

* [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

Closes #2488

### CODE REVIEW

**Comment by abernix** [comment]
I really love the idea of a human-readable date here, but I'm tempted to opt for something which is more language agnostic and standardized, rather than adopting a JS-centric duration package (even as popular as it is).  For example, the ISO8601 duration format (which could be implemented via https://www.npmjs.com/package/iso8601-duration) seems more universally supported.

The user could of course supply their own implementation that utilizes it, but it seems the specification here might call for ISO8601?

e.g.

* `P1D` for _1-day_.
* `P1M` for _1-month_.
* `PT1H30M` for _1-hour 30-minutes_.
* Or, in the extreme example suggested on `iso8601-duration`'s `README`: 
  `P1Y2M4DT20H44M12.67S` for _1 year, 2 months, 4 days, 20 hours, 44 minutes and 12.67 seconds_.

Thoughts?

**Comment by mxstbr** [comment]
I am fine with either option, both are an improvement over the status quo. While I do think `ms` is more readable I also understand the value of using a standard! I'll let you make that call

**Comment by martijnwalraven** [comment]
I'm a little bit on the fence about adopting ISO 8601, because the examples seem pretty cryptic to me, and the goal of this is to make it more human readable. I don't think we should rely on the arbitrary patterns supported by a specific JavaScript package however, so I really wish there was another standard we could adopt instead.

**Comment by abernix** [comment]
The ISO8601 duration standard is long established.  I do think it's entirely possible we can support both though, just by piping the duration of (the super lightweight `ms` package) into `iso8601-duration` as `PT(output-from-ms/1000)S`.

**Comment by abernix** [comment]
Did not mean to close. 😄

**Comment by glasser** [comment]
The seconds-based maxAge (inspired by the HTTP cache-control header) has been our standard for quite a while now and I don't think we're planning to change it. Sorry for the delay!

**Pull request closed without merging**
