### PR TITLE
Fix for broken healthcheck in apollo-server-lambda

### LINKED ISSUE #4891: Healthcheck does not work for apollo-server-lambda when using an API gateway custom domain
If you run your service with a custom domain and you use a path in your mapping, you will get a 400 response.

**The expected behavior:**
Return the healthcheck status

**The actual behavior.**
A 400 response with `GET query missing.`

This is probably due to how the path is passed from Cloudfront to APIG. One way to fix it would be to check if the path endsWith "/.well-known/apollo/server-health" in this file:
https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-lambda/src/ApolloServer.ts#L176

I can create a PR if this could be useful for others.

- [x] A short, but descriptive title. The title doesn't need "Apollo" in it.
- [x] The package name and version of Apollo showing the problem.
- [ ] If applicable, the last version of Apollo where the problem did _not_ occur.
- [x] The expected behavior.
- [x] The actual behavior.
- [ ] A **simple**, runnable reproduction!
      Please make a GitHub repository that anyone can clone and run and see the
      problem. Other great ways to demonstrate a reproduction are using our
      CodeSandbox template (https://codesandbox.io/s/apollo-server), or re-mixing
      our Glitch template (https://glitch.com/~apollo-launchpad).

### PR DESCRIPTION
**Pull request by iannickb**
Use `endsWith` except of `===` to check if the healthcheck endpoint is called. This should fix #4891.

### CODE REVIEW

**Comment by glasser** [comment]
Is this something that used to work and has changed in Lambda? Or is it an issue specific to custom domains and that's why it wasn't caught before? Are there docs you can point me at that make it clear what the expected value of `event.path` is?  What does the value look like in your custom domain use case?  Do we have to apply a similar change to the other use of `event.path` in the file (which brings in graphql-playground)?

**Comment by iannickb** [comment]
Thank you for the quick response @glasser !

> Is this something that used to work and has changed in Lambda?

My guess is that it never worked. It was introduced when onHealthCheck was added https://github.com/apollographql/apollo-server/commit/84e1aa5ad3ee2acf410ca8984cfc68e90d4f8a66#diff-859ee6c9b8a50783a3f6358ec930fd105d32832ffd678c836f58e02ee3ed60d9

> Or is it an issue specific to custom domains and that's why it wasn't caught before?

It is specific to Custom Domains and how the `event.path` is populated when behind a Cloudfront distribution

> Are there docs you can point me at that make it clear what the expected value of event.path is?

For some reason, I could not find any documentation related to that on the aWS website. I did find a good explanation on the serverless-express repo from someone who encountered the same thing.
https://github.com/vendia/serverless-express/issues/216

> What does the value look like in your custom domain use case?

Everything works fine if I am calling the APIG generated endpoint. The value is different when running behind a custom domain and a non-default base path mapping.

> Do we have to apply a similar change to the other use of event.path in the file (which brings in graphql-playground)?

It would be better to be consistent and change it across the board.

**Comment by iannickb** [comment]
I reviewed the code for playground and I am wondering why there is a check for `event.path`. That value should always be there for apollo-server-lambda.
https://github.com/iannickb/apollo-server/blob/f1a8d518339e98d429d414288b3c2e3eed15b488/packages/apollo-server-lambda/src/ApolloServer.ts#L208-L211

Also, since the condition is on method and the playground setting, maybe we could leave as is?

**Comment by kamaz** [comment]
@iannickb I believe that is a real problem and doesn't apply only on `api gateway`. I use it with `ALB` where `Apollo Server` is bound by custom `context`. In my scenario, I get `/bff/.well-known/apollo/server-health`.

**Comment by glasser** [comment]
Just want to note that I am still tracking this for the next day of "merge a bunch of PRs that cover parts of the codebase where I need to do some research before I can evaluate them"; this hasn't happened yet largely due to some vacation.

**Comment by glasser** [comment]
OK. I find this whole thing to be pretty confusing. Sounds like the way `event.path` works in Lambda is very inconsistent depending on which particular service your Lambda lives behind.  I'm also rather confused that #4687 is asking for the opposite resolution (they're saying `event.path` is shorter than it should be rather than longer).

That said, this particular change does seem unlikely to break anything: nobody should be depending on any URL ending with `/.well-known/apollo/server-health` doing anything other than triggering a health check. So I'll merge it, though I'm still pretty confused about #4687.

**Comment by glasser** [comment]
I've published a release with this to version `2.21.1-alpha.0`. My plan is to release 2.21.1 on Monday. If you want to test that this fix works before then, try running the prerelease yourself, and provide feedback on https://github.com/apollographql/apollo-server/pull/4990

**Pull request merged**
