### PR TITLE
Setup prettier

### PR DESCRIPTION
**Pull request by n1ru4l**
This PR 

* Adds prettier and a precommit hook (with husky) to run prettier.
* Removes tslint
* Adds [prettier-check](https://github.com/hexacta/prettier-check) to check if the code formatting on travis

### CODE REVIEW

**Comment by n1ru4l** [comment]
How should I deal with the syntax error? Disable trailing comma rule for typescript? A trailing comma after a rest param is a syntax error in javascript and prettier therefore does not add them.

**Comment by stubailo** [comment]
@n1ru4l in some of our other projects we've just removed TSLint entirely, since the combination of a strict `tsconfig.json` and Prettier pretty much covers everything we need! So feel free to get rid of the TSLint stuff entirely.

**Comment by stubailo** [comment]
Looks like this time it's breaking because we are hardcoding `npm@4`

**Comment by n1ru4l** [comment]
```bash
 @ lint /home/travis/build/apollographql/apollo-server

> prettier-check "{packages/*/{src,tests,test,benchmark}/**/*.{j,t}s*,**/*.md,**/*.json}"


Forgot to run prettier? There are files without correct code style:

coverage/coverage.raw.json
````

This is the actual culprit :D

**Comment by n1ru4l** [comment]
@stubailo For some reason travis uses the old `package.json` and `.travis.yml`?

Any idea on how to fix this (maybe just retrigger the build)?

**Comment by stubailo** [comment]
Retriggered, let's see if it helps!

**Comment by stubailo** [comment]
Also, just added you as a collaborator: https://github.com/apollographql/apollo-server/invitations

**Comment by n1ru4l** [comment]
🎉🎉 Finally got it right

**Comment by stubailo** [comment]
woohooo! Will review today :]

**Comment by jbaxleyiii** [comment]
whoa the markdown support! @n1ru4l if you can resolve the conflicts I will happily merge this! 😍 this is so wonderful!

**Comment by n1ru4l** [comment]
@jbaxleyiii Resolved 😊

**Comment by kachkaev** [comment]
Hi guys, a passer-by here 👋 

Just curious how you catch semantic errors such as misspelled variable names after removing tslint. I'm trying to set up a new TypeScript project with the state-of-the-art combination of tools and am keen to understand the motivation behind your choices. `prettier-check` looks nice, but I can't see how it may cover all typos 🤔

**Pull request merged**
