### PR TITLE
Fix isGraphQLQuery check in response-cache plugin

### LINKED ISSUE #2745: Incorect behavior of plugin apollo-server-plugin-response-cache in case of validation error on client request
Hey guys

I have a bug related to the plugin apollo-server-plugin-response-cache.

Expected:
When the client sends a not well-formed request, server must answers with GraphQL error and validation details. Example of correct answer 
`{ name: 'ValidationError',
 message:
  'Cannot query field "accommodations_foo" on type "Query". Did you mean "accommodations"?',
 code: 'GRAPHQL_VALIDATION_FAILED' } [ 'Cannot query field "accommodations_foo" on type "Query". Did you mean "accommodations"?',`

Actually:
The client received the bag. Trace:
`{ name: 'TypeError',
  message: 'Cannot read property \'operation\' of undefined',
  code: 'INTERNAL_SERVER_ERROR' } [ 'TypeError: Cannot read property \'operation\' of undefined',
at isGraphQLQuery (/home/***/node_modules/apollo-server-plugin-response-cache/src/
2:36)',
at Object.<anonymous> (/home/***/node_modules/apollo-server-plugin-response-cache/
s:224:16)',
at Generator.next (<anonymous>)', at /home/***/node_modules/apollo-server-plugin-response-cache/dist/ApolloServerPlu
at new Promise (<anonymous>)',
at __awaiter (/home/***/node_modules/apollo-server-plugin-response-cache/dist/Apolo,
at Object.willSendResponse (/home/***/node_modules/apollo-server-plugin-response-cache/dist/ApolloServerPluginResponseCache.js:92:28)',`

Would be great to fix the logic here:
https://github.com/apollographql/apollo-server/blob/bfe900d359fa30e1d90cc612467bd2ec87d6287e/packages/apollo-server-plugin-response-cache/src/ApolloServerPluginResponseCache.ts#L132

Example of fix (just add checking of existing the operation level:
`function isGraphQLQuery(requestContext) {
     return requestContext.operation && requestContext.operation.operation === 'query';
 }`

By the way, I'm developing my service on JavaScript, not TypeScript. Maybe it will help you navigate the nature of the error

### PR DESCRIPTION
**Pull request by fabsrc**
Fixes #2745

### CODE REVIEW

**Comment by intellix** [comment]
For the impatient using https://github.com/ds300/patch-package:
```
diff --git a/node_modules/apollo-server-plugin-response-cache/dist/ApolloServerPluginResponseCache.js b/node_modules/apollo-server-plugin-response-cache/dist/ApolloServerPluginResponseCache.js
index 67a298a..7130a03 100644
--- a/node_modules/apollo-server-plugin-response-cache/dist/ApolloServerPluginResponseCache.js
+++ b/node_modules/apollo-server-plugin-response-cache/dist/ApolloServerPluginResponseCache.js
@@ -26,7 +26,9 @@ function cacheKeyString(key) {
     return sha(JSON.stringify(key));
 }
 function isGraphQLQuery(requestContext) {
-    return requestContext.operation.operation === 'query';
+  return (
+    requestContext.operation && requestContext.operation.operation === 'query'
+  );
 }
 function plugin(options = Object.create(null)) {
     return {

```

**Comment by fabsrc** [comment]
@abernix or @glasser: could you please have a look at this? 🙂

**Comment by glasser** [comment]
Good catch, thanks!

**Comment by scf4** [comment]
When will this be released?

**Pull request merged**
