### PR TITLE
deepMerge not working correctly with arrays

### LINKED ISSUE #2946: Gateway: deepMerge not working with arrays
Hi,

@apollo/gateway: 0.6.11

For **function deepMerge(target: any, source: any): any**
if source and target are arrays, the fonction is not working properly.

I think code should be something like that:

>        if (source[key] === undefined || key === '__proto__')
>           continue;
>        if (target[key] && isObject(source[key])) {
>           deepMerge(target[key], source[key]);
>        } else if (Array.isArray(source[key]) && Array.isArray(target[key]) && source[key].length === target[key].length) {
>            let i = 0;
>            for (; i < source[key].length; i++) {
>                deepMerge(target[key][i], source[key][i]);
>           }
>        }
>        else {
>            target[key] = source[key];
>        }

Thanks

### PR DESCRIPTION
**Pull request by hugues33**
Fix #2946

### CODE REVIEW

**Comment by trevor-scheer** [comment]
Hey @hugues33, thanks for taking the time to submit a PR 😄

I certainly don't doubt the existence of an issue, but I'd like to better understand the problem that instigated the issue to begin with. An integration test would help me accomplish that as well as guarantee we don't break this in the future (if, say, we chose to use a deep merge utility which I'm considering in response to this issue).

In addition, I want to understand the nuance behind only merging arrays of the same length. I believe we're expecting these lengths to always be the same, but if they're not, what's expected / acceptable behavior? I think an integration test would help me to understand this more clearly.

**Comment by hugues33** [comment]
Hi @trevor-scheer,

I have reproduced the problem here https://github.com/hugues33/federation-demo/tree/deepMerge_with_arrays

The following query:

```
{
  me {
    # goodAddress
    goodDescription
    metadata {
      address
    }
  }
}
```
Give me the incorrect result:
```
{
  "data": {
    "me": {
      "goodDescription": true,
      "metadata": [
        {
          "address": null
        }
      ]
    }
  }
}
```

While:
```
{
  me {
    goodAddress
    goodDescription
    metadata {
      address
    }
  }
}
```

Gives the correct result:
```
{
  "data": {
    "me": {
      "goodAddress": true,
      "goodDescription": true,
      "metadata": [
        {
          "address": "1"
        }
      ]
    }
  }
}
```

I agree this test case is special, but it can come when using a document DB like Mongo where UserMetadata is included in the same document as User.

Perhaps the problem comes from UserMetada which is not an Entity.

Please say me if it is an incorrect use of Federation.

At the deepMerge level we have to merge to arrays:
one with `[{address: "1"}]`
the other with `[{description: "1"}]`
in this case, deepMerge overwrite the target with source.

Best regards

**Comment by trevor-scheer** [comment]
Hey @hugues33, this seems like a valid use and suggestion to me. This is high on my priority list, but I may not get to it until after the weekend with the US holiday. This does still need an integration test, so if you find time to translate your example into a test case within our repo, it would be greatly appreciated and would certainly speed this up. Otherwise, I'll take care of the rest as I'm able.

Thanks again for the PR and quick response to my question!

**Comment by hugues33** [comment]
Hi @trevor-scheer ,

I have added a basic integration test. There is still some work to make this test more "realistic".

**Comment by jbaxleyiii** [comment]
@trevor-scheer we should just switch out for a library instead of our own custom impl tbh

**Comment by trevor-scheer** [comment]
@jbaxleyiii agreed, but we do have some custom array merge logic. A quick investigation showed this as potentially viable, but tests weren't passing when I dropped it in.
https://www.npmjs.com/package/deepmerge#arraymerge

Something to consider in the future if it feels important, but going to merge this.

**Pull request merged**
