### PR TITLE
Send content length header.

### PR DESCRIPTION
**Pull request by jroith**
Sending a content-length header allows CloudFront to gzip compress the response.

### CODE REVIEW

**Comment by martijnwalraven** [comment]
This looks reasonable to me, but I wanted to get at least a second set of eyes to agree before putting this in. From what I have been able to gather, the default encoding for a string when you `response.write` should always be `utf8`, so there is no worry the length could be calculated incorrectly.

 @jroith @petetnt: Does that make sense to you?

**Comment by petetnt** [comment]
Makes sense to me @martijnwalraven

**Comment by jroith** [comment]
Yes, @martijnwalraven that is my understanding as well.

**Comment by martijnwalraven** [comment]
Great, thanks!

**Pull request merged**
