### PR TITLE
federation: Include originalError in downstreamServiceError

### PR DESCRIPTION
**Pull request by bl42**
```
 new ApolloServer({
  formatError: GraphQLError => GraphQLError.originalError, // undefined
  gateway: new ApolloGateway({ ... })
  ...
})
```

The GraphQLError type expected to have originalError (if avialible)
`formatError: GraphQLError => GraphQLError.originalError` 

In the event of a downstreamServiceError, it does not include the original error.
I believe it's reasonable to expect the original error in this event.

### CODE REVIEW

**Comment by charlesxsh** [comment]
Is it better remove the yarn.lock file from this?

**Comment by ycfreeman** [comment]
https://github.com/apollographql/apollo-server/pull/3610

**Comment by abernix** [comment]
Superseded by https://github.com/apollographql/apollo-server/pull/3610.

**Comment by abernix** [comment]
Re-opening because I can no longer re-open #3610 and this is very close (just with a `yarn.lock`).

**Comment by abernix** [comment]
Hi @bl42!,

> This is a semi-automated message.  Apologies for the lack of personal detail.  I’d encourage reading the rest of this message but, if you're busy, hopefully this is as easy for you — or someone who is willing to own the contribution — as pushing the button later in this message to re-create this PR, from an auto-migrated branch, on the new Federation repository.  If you have time, read on!

We’re in the process of moving federation-related concerns out of this repository (where it has historically lived) into a new home specifically for Apollo Federation.   **This PR is affected by the transition since it touches code which has been moved**.

I’ve done some preparations to make this as easy as possible, but **we’ll need to close this PR, and I could use your help in re-opening it on the new Apollo Federation repository.**

In https://github.com/apollographql/federation/pull/134 (which has a lot more details, if you’re interested), we introduced the same code that was in this repository to the new Federation repository (maintaining its history) and removed the code from this repository in https://github.com/apollographql/apollo-server/pull/4561.

While **this** PR still needs to get reviewed and approved to land, it should no longer live in this repository in its current state since it cannot merge in anymore.  To facilitate the movement of this PR to the new home, I’ve **automatically generated branches on the new repository** using the same commit authorship and messages that you originally included on this PR.

Pull-requests can’t be moved on GitHub in the same way _Issues_ can be.  While I could just create the PRs from these new branches too, the contribution belongs to you!

---

**Original PR author only: Click this button to open a new PR from the auto-created  `apollo-server-import/pr-3211` branch on the new Apollo Federation repository**

[Original PR author: Click here to re-create this PR on the Federation repository](https://github.com/apollographql/federation/compare/main...apollo-server-import/pr-3211?expand=1&title=federation%3A+Include+originalError+in+downstreamServiceError&body=%60%60%60%0D%0A+new+ApolloServer%28%7B%0D%0A++formatError%3A+GraphQLError+%3D%3E+GraphQLError.originalError%2C+%2F%2F+undefined%0D%0A++gateway%3A+new+ApolloGateway%28%7B+...+%7D%29%0D%0A++...%0D%0A%7D%29%0D%0A%60%60%60%0D%0A%0D%0AThe+GraphQLError+type+expected+to+have+originalError+%28if+avialible%29%0D%0A%60formatError%3A+GraphQLError+%3D%3E+GraphQLError.originalError%60+%0D%0A%0D%0AIn+the+event+of+a+downstreamServiceError%2C+it+does+not+include+the+original+error.%0D%0AI+believe+it%27s+reasonable+to+expect+the+original+error+in+this+event.%0D%0A%0A---%0AOriginally+at%3A+apollographql%2Fapollo-server%233211)

(The code and your commits should be the same and **you will have an opportunity to confirm**, but this way you can continue to be the author and track its progress on the new Federation repository!)

---

There’s no easy way to bring over any existing comments on this PR, so I encourage you to copy and paste those onto the new issue if possible.

Overall, I hope this process is _relatively_ easy for you while maintaining your commit contribution authorship.  I apologize for any inconvenience caused by this shuffle, but please ping me if I can help in any way!

:rocket:

**Pull request closed without merging**
