### PR TITLE
feat(uploads): replace apollo-upload-server v5 with graphql-upload v8

### LINKED ISSUE #1703: [File Upload] - flawed error handling for bad JSON
With "apollo-server-express": "^2.1.0".

I am testing my file upload API using a REST client (Insomnia). The Apollo Express Server delegates file upload handling to the Apollo Upload Server by Jayden Seric. This middleware handles multipart requests and requires a few HTTP headers to be set to work correctly. These headers ("operations" and "map") require JSON data. If I pass invalid JSON data to one of these headers, an unhandled exception is thrown _asynchronously_ in the Upload Server thus killing the whole server!

I believe this issue to have been fixed in later releases of the Upload Server. The latest Apollo Express uses apollo-upload-server v5. The apollo-upload-server code has been migrated to graphql-upload and the current version is 8. There is a small change in the API, which I believe to be non-essential. It would be nice to have the dependency updated! : ]

Working on Windows I find forking the apollo-server repo and testing this change a bit of a nuisance but if required I could try to do it.

### PR DESCRIPTION
**Pull request by lgaticaq**
Fix #1703 and #1509
Migrate [@apollographql/apollo-upload-server](https://github.com/apollographql/apollo-upload-server) to [graphql-upload](https://github.com/jaydenseric/graphql-upload)

TODO:

* [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by lgaticaq** [comment]
Close this PR because make changes in https://github.com/apollographql/apollo-upload-server/pull/3

**Comment by jaydenseric** [comment]
Keep in mind the `engines.node` field of relevant packages will need to be updated, as `graphql-upload` upped support to Node.js v8.5+; see https://github.com/jaydenseric/graphql-upload/issues/109.

**Comment by jaydenseric** [comment]
CI will need to be reconfigured to not test on Node.js v6: https://github.com/apollographql/apollo-server/blob/master/.circleci/config.yml#L106

**Comment by edevil** [comment]
I was under the impression this would be included in 2.2.0. Is there anything that I can do to help move this along? @abernix @martijnwalraven @lgaticaq

**Comment by martijnwalraven** [comment]
@edevil We can't include this in 2.2 because it's a breaking change to drop Node 6 support.

**Comment by edevil** [comment]
@martijnwalraven Oh, I see. :( So I guess this is not something for the near future, right?

**Comment by abernix** [comment]
Superseded by #2054.  Thank you very much for taking the time to work on this!

I'd really appreciate if you could try the `alpha` release I published off that PR — `apollo-server@2.3.0-alpha.0` — and detail any problems (or successes!) you encounter with the upgrade.

Ref: https://github.com/apollographql/apollo-server/pull/2054#issuecomment-444471202

**Comment by abernix** [comment]
The `alpha` releases didn't identify any problems so I've graduated this to the official `apollo-server-*@2.3.0` releases.

**Pull request closed without merging**
