### PR TITLE
Release 2.4.0

### PR DESCRIPTION
**Pull request by abernix**
This is a PR tracking a `release-x.y.z` branch for an upcoming semver minor release of Apollo Server: v2.4.0 (i.e. `release-2.4.0`).  The intention here is to keep the `master` branch a bit more flexible while landing things which have been decidedly put into a release on this more specific release branch.  PRs for 2.4.0 features can be targeted toward this `release-2.4.0` branch (and thus appear in this PR's history), in addition to being merged into the `master` branch and providing the ability to backport fixes on the 2.3.x line from there.

We should experiment with this pattern a bit more in the future but my hope is that it will provide more visibility into what's already staged for a particular release and, more importantly, clarity into the npm "pre" (e.g. `alpha`, `beta`, `next`) releases that have been cut off it for those who are interested in testing/following/providing feedback on those releases, once the original PRs that introduce those features have landed.

There have already been 2.4.0 alpha releases cut from `release-2.4.0` (for example, the `alpha` releases on #2111 — which is now merged into this `release-2.4.0` branch), but I'd like to merge @rkorrelboom's work which introduces a new Fastify integration from https://github.com/apollographql/apollo-server/pull/1971, so that'll be next in line for a pre-release!

Check the [appropriate milestone](https://github.com/apollographql/apollo-server/milestone/12) for more details on what's slated for 2.4.0.

### CODE REVIEW

**Comment by iagomelanias** [comment]
[apollo-server-fastify](https://www.npmjs.com/package/apollo-server-fastify) is already taken on NPM. I believe we will need to use another name and update the documentation.

**Comment by abernix** [comment]
@iagomelanias 	I noted that on the other PR just a moment ago (https://github.com/apollographql/apollo-server/pull/1971#issuecomment-456817749).  Hopefully we can figure something out, but it might be worth waiting a few days to see how it pans out.

For the time being, `2.4.0-alpha.3` has been published, though Fastify was not included in that publishing due to the lack of package ownership.

**Comment by nahtnam** [comment]
The package hasn't been updated for a year (https://www.npmjs.com/package/apollo-server-fastify). Maybe I can reach out to the developer and ask them if they are willing to release it? In which case we could just bump it to 2.0 and announce that its a breaking change.

**Comment by abernix** [comment]
Heads up, this is landing without Fastify support.

I don't think we should wait for that to get worked out before we release 2.4.0 with its other fixes and improvements, so I've reverted the merging of that PR into this via https://github.com/apollographql/apollo-server/pull/2215/commits/e971bdf8b4f98ca2c9a25bf83daeda5b7801092c and opened https://github.com/apollographql/apollo-server/pull/2280 which will re-land it when we're ready.

**Comment by abernix** [comment]
2.4.0 has graduated to an official release! 🎆 🚀

- apollo-server-azure-functions@2.4.0
- apollo-server-cloud-functions@2.4.0
- apollo-server-cloudflare@2.4.0
- apollo-server-express@2.4.0
- apollo-server-hapi@2.4.0
- apollo-server-koa@2.4.0
- apollo-server-lambda@2.4.0
- apollo-server-micro@2.4.0
- apollo-server@2.4.0

**Pull request merged**
