### PR TITLE
Fix error rethrowing in lambda Apollo server

### PR DESCRIPTION
**Pull request by alfaproject**

### CODE REVIEW

**Comment by glasser** [comment]
Nice catch, thanks! Adding a changelog on your branch then merging.

**Comment by glasser** [comment]
I've released a prerelease with this fix, version `2.23.0-alpha.0`. Try out the alpha and see if it works for you! Please provide any feedback in #5094.

**Comment by alfaproject** [comment]
We actually use our own fork so don't worry, it's all good (:

**Comment by glasser** [comment]
This is released in Apollo Server 2.23.0.

**Pull request merged**
