### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by realalexhomer**
Hi,
Thanks for the great tutorial. Without the above two parameters you get a "GET Query Missing" page rather than the playground. See https://spectrum.chat/zeit/general/apollo-server-get-query-missing~ae8d5ca5-2faf-4c8d-8097-c3f6e25cad56

Thanks!
Alex

### CODE REVIEW

**Comment by abernix** [comment]
I really appreciate you opening this.  Can you take a look at the alternative suggestion I've made in https://github.com/apollographql/apollo-server/commit/665b406fb4b95bde6a6eaeb90ad6140f864ab4f4 (along with reading that commit's message and seeing if it makes sense to you?).

Many thanks!

**Comment by trevor-scheer** [comment]
@abernix I agree with your take on this update, especially:
> In fact, introducing them may inadvertently cause users toenable these, when we intentionally take the step to disable it.

@realalexhomer, how do you feel about landing the changes proposed by 665b406fb4b95bde6a6eaeb90ad6140f864ab4f4 and closing this?

**Comment by abernix** [comment]
I went ahead and landed a re-worded commit of 665b406 with co-authorship by @realalexhomer to preserve their contribution credit to Apollo Server, and landed it on `master`: https://github.com/apollographql/apollo-server/commit/e548a8c22409bdc2760b5524eda08b3821aff38b.

Thank you very much for opening this originally, @realalexhomer.

**Comment by realalexhomer** [comment]
Thanks guys!

**Pull request closed without merging**
