### PR TITLE
Add custom directive note to AS4 "Directives" article

### PR DESCRIPTION
**Pull request by rkoron007**
Adding a note based on [Community feedback](https://community.apollographql.com/t/how-do-i-create-custom-directives-in-apollo-server-v4/4893)

### CODE REVIEW

**Comment by glasser** [comment]
This is fine I think, but I do wonder if it would make sense to have a brief section on creating custom directives.

What graphql-tools lets you do is *transform your schema in a way that is driven by the presence of schema directives* (whether that means actually changing the schema itself, or instrumenting/creating resolver functions, etc).  That's a specific enough use case (and one where you could imagine various different approaches or tools that work) that letting graphql-tools document its own functionality and having us just link to it like this seems right. But it does seem like the page could just generally document the idea that you can create your own schema or executable directives with `directive` definitions, and look for them in plugins (for executable directives) or something...

If that's not inspiring we can go forward with this change (maybe with some small changes) for now though.

**Review by glasser — CHANGES_REQUESTED** [review]
clicking button to update metadata (made a comment last week)

**Comment by glasser** [comment]
I'm just saying that there's a difference between "writing lines in your schema that mean you can write `@foo` in an operation or a schema" (which is just part of the GraphQL spec, implemented by `graphql-js`, something you can certainly do in Apollo Server without anything else) and "processing your schema using software that searches for particular schema directives and transforms the schema based on what it finds" (which is not something supported natively by `graphql-js`/Apollo Server).  Saying you need to use a separate library to "define a custom schema directive" seems incorrect to me — it's that you need a separate library to "process your schema in a way that pays attention to custom schema directives".

**Comment by rkoron007** [comment]
[This PR](https://github.com/apollographql/apollo-server/pull/7206) will incorporate the changes I intended to make with this PR!

**Comment by glasser** [comment]
Heh, I thought that seemed familiar!

**Pull request closed without merging**
