### PR TITLE
Upgrade cors and @types/cors

### LINKED ISSUE #5055: Update cors and @types/cors
I'm using `cors@2.8.5` and `@types/cors@2.8.10` but apollo-server-express still use `cors@2.8.4` and `@types/cors@2.8.8` and this is causing a types error.

### PR DESCRIPTION
**Pull request by glasser**
The change to the code was necessary due to
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49130 which ironically
was apparently submitted to support Apollo!

Also remove unnecessary @types/cors dependency from apollo-server-koa.

Fixes #5055.

### CODE REVIEW

**Comment by jonesmac** [comment]
@glasser I think an unintended consequence of this change is that by upgrading @types/cors to 2.8.10, it caused folks who have cors setup elsewhere in their project that were compatible with earlier versions of cors typings (i.e. without the generic passed to the function) to fail to compile.  While it's just types, it does cause apps to fail to start so I feel like it could be considered a breaking change.  

Is the intention of this project to discourage the use of cors outside of apollo?  
* If not, then I would hold off on updating cors types until major releases since folks might have it configured differently outside of apollo-server.  
* If so, is that state anywhere explicitly?  

Thanks again for all the hard work on this project.  Its been great to work with so far.  Feel free to correct any misunderstandings I might have.

**Comment by glasser** [comment]
I think this is pretty challenging because versioning with DefinitelyTyped packages often runs into these issues. DefinitelyTyped is an awesome project solving a very difficult problem, but they also frequently introduce backwards incompatible changes in patch releases, and the dependencies between `@types` packages generally use `*` ranges which runs into issues.  We made this change because it was breaking users who had already upgraded their `@types/cors` a bit. We do our best to avoid backwards incompatibility in Apollo Server 2 and that has definitely included avoiding making major version upgrades of dependencies (even when this has held back the ability to use AS with up to date third party libraries). But the theme with `@types` (and *especially* around the set of `@types` packages related to Express) has seemed to be "sometimes things break unless you update all your `@types` packages too".  These aren't major version upgrades — these are patch upgrades!

If you have a suggestion of a change that can solve the original problem without causing other problems please let me know. I would love to have a solution to these issues that isn't "give up and assume that upgrading `@types` packages when there are conflicts is a thing that TypeScript users have figured out how to do".

**Comment by glasser** [comment]
(For example I don't think it's a solution to pin `cors` or `@types/cors` at a precise package version without a range, but allowing the slightly newer versions to be installed wasn't building before.)

**Comment by glasser** [comment]
I'll admit that I don't love the way that we do cors inside Apollo Server now. I think it's helpful for there to be some easy ways to do the simplest CORS changes, especially with `apollo-server` which allows you to run a GraphQL server without configuring a web framework at all. But once you're using middleware I don't know that it makes sense to continue to make it AS' responsibility.

https://github.com/apollographql/apollo-server/issues/4859 shows my thoughts (the main comment is actually by me, edited from the original poster's original) on the matter. The big challenge is that we try to support both platforms that have middleware and their own cors libraries like Express, but also serverless frameworks like Lambda with no built-in "middleware" concept of composability.

**Pull request merged**
