### PR TITLE
chore: enable test coverage

### PR DESCRIPTION
**Pull request by SimenB**
Ref https://github.com/facebook/jest/issues/12998#issuecomment-1209073310, the issue with the test coverage is caused by `@jridgewell/trace-mapping`. In order to unblock, let's just force the version of that module in that repo.

### CODE REVIEW

**Comment by glasser** [comment]
Thanks for tracking this down @SimenB!

I am not super comfortable relying on package-lock.json for important transitive dependency bumps so perhaps I'll just follow along with https://github.com/facebook/jest/pull/13119 and see when it ends up in a release? (The PR as written also doesn't currently actually enable coverage.)

**Comment by SimenB** [comment]
>see when it ends up in a release

In v29 stable sometime this weekend or next week. So it'll require a major bump (not super breaking though, so possibly no issue to upgrade).

> The PR as written also doesn't currently actually enable coverage.

Oh, I just reverted the linked commit from https://github.com/facebook/jest/issues/12998#issuecomment-1208354897 and updated the dep 🤷

**Comment by jridgewell** [comment]
I don't believe https://github.com/facebook/jest/issues/12998 will actually resolve the issue, because it's Babel that's generating the incorrect trace-mapping instance. The reason you noticed this when upgrading Jest is because Jest will reuse the invalid sourcemap as is. Maybe I should go with a better branding check, so that the old code path fails to run for this old remapping code.

**Comment by jridgewell** [comment]
> I am not super comfortable relying on package-lock.json for important transitive dependency bumps so perhaps I'll just follow along with [facebook/jest#13119](https://github.com/facebook/jest/pull/13119) and see when it ends up in a release?

If you were to fresh `npm i` without the lockfile, the problem is fixed because `@babel/core` depends on `@ampproject/remapping@^2.1.0`, and that depends on `@jridgewell/trace-mapping@^0.3.0`, and it'll pick up the fix in v0.3.9. If you were to do `npm ci`, then it would fail because of the `package-lock.json`. By updating the lockfile, everything should be resolved now.

**Comment by SimenB** [comment]
Seems like this is of no interest, so I'll close to keep clutter down

**Comment by glasser** [comment]
Thanks; I am still tracking this with the assumption that the Jest 29 upgrade will also resolve this (which is blocked on ts-jest doing a final release of their 29 support).

**Comment by SimenB** [comment]
Not necessarily - as mentioned the issue isn't in any of Jest's modules which'd be updated by v29 upgrade - it's transitive via `@babel/core`. This PR is just `npm update @ampproject/remapping` which fixes the issue. You can also do `npm update @jridgewell/trace-mapping` which forces a version which handles the output from `@ampproject/remapping` (and is what you'll get from updating Jest).

---

That said, `ts-jest` was released 3 hours ago, so might be you just wanna go to v29 🙂 But again, that's like 5 dependencies removed from the actual bug fix.

**Pull request closed without merging**
