### PR TITLE
fix(fastify): use scoped modules

### PR DESCRIPTION
**Pull request by SimenB**
The official plugins of `fastify` are now scoped, and the old names are deprecated. There should be no other breaking changes.

### CODE REVIEW

**Comment by glasser** [comment]
@SimenB Just to check: are the new packages fully backwards compatible with the old ones (eg, can you use the `accepts` and `cors` middlewares from the new packages with the same versions of Fastify as before?), or will users upgrading to a newer version of apollo-server-fastify need to upgrade Fastify as well?

(For what it's worth, we will be solving this problem in Apollo Server 4 by not trying to magically wrap these middleware in our own middleware and trusting that (with clearly documented examples) folks can use these middleware directly. We will also be decoupling the `apollo-server-fastify` release process from the Apollo Server core release process by providing a stable API between ApolloServer and web framework integrations and allowing active users of web frameworks like Fastify to maintain the integration with their expertise.)

**Comment by SimenB** [comment]
Yeah, only breaking change is the rename 🙂

**Comment by glasser** [comment]
Great. Mind resolving the `package-lock.json` conflict? Rebasing should clear up the spell-check failure too.

**Comment by SimenB** [comment]
@glasser done 🙂

**Pull request merged**
