### PR TITLE
Add support for subscription connectionParams in GraphiQL

### PR DESCRIPTION
**Pull request by Glockenbeat**
This PR adds the ability to pass connectionParams to the GraphiQL options in the GraphiQL plugins (solved https://github.com/apollographql/apollo-server/issues/452).

TODO:

- [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by DxCx** [comment]
LGTM but i think we need a better naming, at least adding websocket before so it will be
`websocketConnectionParams`

**Comment by Glockenbeat** [comment]
Would be possible of course, however I tried to stick to the naming which is used for the SubscriptionServer onConnect() method in the [authentication example](http://dev.apollodata.com/tools/graphql-subscriptions/authentication.html). Should we change it anyways?

**Comment by Glockenbeat** [comment]
Updated the naming as proposed, so it's "websocketConnectionParams" now.

**Comment by Stradivario** [comment]
Thank you guys! I was trying to implement some logic with cookies passed from the server.When the authorization header from the first graphiql request was passed to the client on second request for subscription cookies are passed trough socket and then the server verifies the token again.

Waiting for this to be merged :)

**Comment by rdickert** [comment]
I came to suggest this very thing and found it almost done. Awesome!

I have one possible change: Perhaps the item passed to `websocketConnectionParams` already be stringified rather than stringifying it at the destination. I was setting up some code:

```js
  websocketConnectionParams: {
    authToken: localStorage.getItem('AUTH_TOKEN'),
  },
```
but since I'm setting this up on the server, `localStorage` is undefined, and it throws an error.

**Comment by martijnwalraven** [comment]
@Glockenbeat @DxCx: What do you think of @rdickert's proposal?

**Comment by Glockenbeat** [comment]
I like the idea of being able to use data from the client rather than setting it in the GraphiQL connection settings on the server. Something like that is definitely needed.

Personally I don't really like how the values are passed as a string as they are implicitly executed on the client, but since that is already implemented in the same way for passHeader it should be fine to use here as well.

**Comment by Glockenbeat** [comment]
Would it be possible to merge this PR and iterate on it afterwards? So far the discussion seems to be a bit stuck but I think this could be helpful for some people to work with connectionParams and websockets, even when there might be better implementations in the long run.

**Comment by martijnwalraven** [comment]
@Glockenbeat: I'd be happy to merge this if other people agree. @DxCx? @rdickert?

**Comment by stubailo** [comment]
Yeah let's do it!

**Comment by mjgallag** [comment]
It appears I'm a bit confused, is there any way to pass an auth token from local storage with `websocketConnectionParams `as `passHeader` allows?

**Pull request merged**
