### PR TITLE
Integration with Adonis Framework

### PR DESCRIPTION
**Pull request by enniel**

### CODE REVIEW

**Comment by footniko** [comment]
When to expect it to be merged?

**Comment by geoffreylzf** [comment]
Hi, want to ask when this will be merge?

**Comment by okurichenko** [comment]
👍solve conflicts and merge?

**Comment by giuseppeangri** [comment]
Hi, there are news about the merge?

**Comment by abernix** [comment]
While I really appreciate you taking the time to open this PR, unfortunately, the Adonis framework hasn't been popular enough of a request for us to adopt into the Apollo Server repository along with the, for lack of a better word, maintenance burden that goes along with taking on another framework.

We currently support many frameworks and do our best to maintain them while maintaining feature parity across them.  We encourage developers who are using different frameworks to  to publish their own packages, and we intend on adopting a more simple approach to supporting this in Apollo Server 3 (#2360) that we hope facilitates this.  I hope it's clear that your work here isn't in vain though, and that this implementation could easily exist as it's own package that leverages `apollo-server-core`, despite us not accepting this into core.

**Comment by ghosh** [comment]
@enniel While its a bummer that it could not be added to the official repo, the reasons are understandable.

Would you be open to publishing this as a stand alone package? I'm sure the adonis community would be quite grateful for it.

**Pull request closed without merging**
