### PR TITLE
Support gateways without executors

### LINKED ISSUE #5518: Make it easier to mock execution of a managed federation schema
The GatewayInterface does two things: it watches a possibly changing schema, and it replaces the executor.  There's a use case for running an ApolloServer with a managed federation schema where we want a GatewayInterface implementation that wraps the real ApolloGateway to load and watch the schema, but still uses normal GraphQL execution (using mocks). Let's support that explicitly.

See #5507. cc @setchy

### PR DESCRIPTION
**Pull request by glasser**
Previously gateways could express their executor in two ways: as the
executor method (required to exist!) and as part of the return value
from load (which was ignored!).

Now we just return it from load, and allow it to be null.

This supports a mocking use case. Fixes #5518. It lets you do something
like:

    import { addMocksToSchema } from '@graphql-tools/mock';
    const realGateway = new ApolloGateway();
    const gateway: GatewayInterface = {
      async load(options) {
        const { schema } = await realGateway.load(options);
        return {
          schema: addMocksToSchema({ schema }),
          executor: null,
        };
      }
      stop() {
        return realGateway.stop();
      }
      onSchemaLoadOrUpdate(callback) {
        return realGateway.onSchemaLoadOrUpdate(callback);
      }
    };
    const server = new ApolloServer({ gateway });

to define a server that follows a managed federation graph but executes
queries using mocking.

### CODE REVIEW

**Comment by setchy** [comment]
Hi @glasser - do you happen to have a complete example you can share?  I've spent quite some time this morning and haven't had any success.  I've adapted to the above fragment you shared, but any queries are still returning `null` instead of a mocked value (tried both [default mocks](https://www.graphql-tools.com/docs/mocking#default-mock-example) and [custom mocks](https://www.graphql-tools.com/docs/mocking#customizing-mocks))

**Comment by glasser** [comment]
@setchy I'll admit I threw the above together pretty quickly... I'm pretty sure I tested it though! Can you show me a codesandbox or repo demonstrating that it doesn't work with AS 3.1? (FYI I'm on and off vacation the next few weeks.)

**Comment by setchy** [comment]
No problems at all @glasser - decent chance its my user error 😅 

Here is a stripped down minimal recreation - https://github.com/setchy/apollo-server-3-mocked-federation

**Comment by glasser** [comment]
Ah @setchy, here's what's going on. After some recent refactors (which introduced onSchemaLoadOrUpdate), the `schema` returned from gateway.load() is mostly ignored (unless you're using an old version of gateway without `onSchemaLoadOrUpdate`). The actual thing that drives what schema is used by the server is the onSchemaLoadOrUpdate callback. So you still need to *call and await* `realGateway.load` in your `load`, but the schema that matters is coming through `onSchemaLoadOrUpdate`.

So it looks like this works:

```typescript
const gateway: GatewayInterface = {
  async load(options) {
    await realGateway.load(options);
    return {
      schema: null,
      executor: null,
    };
  },
  stop() {
    return realGateway.stop();
  },
  onSchemaLoadOrUpdate(callback) {
    return realGateway.onSchemaLoadOrUpdate((schemaContext) => {
      callback({
        ...schemaContext,
        apiSchema: addMocksToSchema({ schema: schemaContext.apiSchema, mocks }),
      });
    });
  },
};
```

(If returning `schema: null` here is scary (it probably breaks TypeScript strict mode) you can keep your existing addMockToSchema call; I'm just reasonably sure the schema returned there is ignored if you have the rest set up properly.)

**Comment by setchy** [comment]
Awesome, this is working like a treat!  Thank you @glasser 👏 

I've updated [my sample repo](https://github.com/setchy/apollo-server-3-mocked-federation) with the above, too

**Pull request merged**
