### PR TITLE
feat(lambda) File uploads

### LINKED ISSUE #1419: File uploads using apollo-server-lambda
Hi,
Could not find any mention, whether apollo-server-lambda supports the GraphQL multipart request specification for uploading files as mutation arguments (like apollo-server does)

### LINKED ISSUE #1703: [File Upload] - flawed error handling for bad JSON
With "apollo-server-express": "^2.1.0".

I am testing my file upload API using a REST client (Insomnia). The Apollo Express Server delegates file upload handling to the Apollo Upload Server by Jayden Seric. This middleware handles multipart requests and requires a few HTTP headers to be set to work correctly. These headers ("operations" and "map") require JSON data. If I pass invalid JSON data to one of these headers, an unhandled exception is thrown _asynchronously_ in the Upload Server thus killing the whole server!

I believe this issue to have been fixed in later releases of the Upload Server. The latest Apollo Express uses apollo-upload-server v5. The apollo-upload-server code has been migrated to graphql-upload and the current version is 8. There is a small change in the API, which I believe to be non-essential. It would be nice to have the dependency updated! : ]

Working on Windows I find forking the apollo-server repo and testing this change a bit of a nuisance but if required I could try to do it.

### PR DESCRIPTION
**Pull request by mathix420**
Fix #1419, fix #1703 file upload using lambda.
Based on #3676 and #1739

TODO:
- [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

After reading both #3676 and #1739 and seeing no further advancements, I convinced myself to write this PR. I tried to consider all the comments from old PRs and merge best parts of both ideas into this one.
Hoping it can help this feature to move forward :100:

Big thanks to @charleswong28, @k00k and @smschick for having being built all the logic !
Don't hesitate to tell me if there is anything to change.

Closes #3676 
Closes #1739

### CODE REVIEW

**Comment by maxgr0** [comment]
Would love to see this merged! Thanks for your work @mathix420

**Comment by mathix420** [comment]
@abernix or @trevor-scheer is it normal that circleci is not passing on my commits ?

**Comment by craigjmidwinter** [comment]
Thanks @mathix420! would love to see one of the three PRs that were created to address this issue get merged in

**Comment by levimichael** [comment]
Thanks so much @mathix420!

Hope this gets approved soon!

**Comment by jordanskole** [comment]
🙏🏼amazing thank you for this! Hopefully gets merged soon!

**Comment by jordanskole** [comment]
Sorry, I should know this, but since all the packages are in a directory, what's the easiest way to test this out?

**Comment by mathix420** [comment]
@jordanskole take a look at this comment from abernix https://github.com/apollographql/apollo-server/pull/1739#issuecomment-612011349

**Comment by mathix420** [comment]
@jordanskole don't forget to add `multipart/form-data` in the **Binary Media Types** section of your API gateway settings, and to deploy your API stage

**Comment by jordanskole** [comment]
Hmmm I keep throwing `UnhandledPromiseRejectionWarning` on the resolver, even just trying to log and return an empty object. It feels likely to me this is not from this package, is there any additional changes I should make besides the **Binary Media Types**? I am running serverless locally. 

Server Error:
```
Serverless: POST /graphql (λ: graphql)
(node:53006) UnhandledPromiseRejectionWarning: [object Array]
(node:53006) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```

Mutation: 
```
...
uploadFile: async (parent, { file }) => {
      try {
        console.log(file)
        return {}
      }
      catch (e) {
        return {}
      }
    }
```

Schema:
```
type Mutation {
  ...
  uploadFile(file: Upload!): File!
}

type File {
    filename: String
    mimetype: String
    encoding: String
  }
```

**Comment by lassesteffen** [comment]
For me it completly crashes before even reaching the resolver with:
```
[
    [Error: Missing Content-Type] {
      message: 'Missing Content-Type',
      locations: undefined,
      path: undefined,
      extensions: { code: 'INTERNAL_SERVER_ERROR' }
    }
  ]
```

Does anybody have an idea what's going on? I am running `serverless-offline`

**Comment by maxgr0** [comment]
> For me it completely crashes before even reaching the resolver with:
> 
> ```
> 
> [
> 
>     [Error: Missing Content-Type] {
> 
>       message: 'Missing Content-Type',
> 
>       locations: undefined,
> 
>       path: undefined,
> 
>       extensions: { code: 'INTERNAL_SERVER_ERROR' }
> 
>     }
> 
>   ]
> 
> ```
> 
> 
> 
> Does anybody have an idea what's going on? I am running `serverless-offline`

Thats caused by the module which is handling the multipart form (busboy). There, the header is handled case-sensitive so you have to have both content-type and Content-Type until its fixed in this module.

**Comment by jordanskole** [comment]
Ahh! Thank you @maxgr0 that actually solved my issue as well. `createUploadLink`/`apollo-upload-client` no longer needed on the client, and was creating the error!

**Comment by lassesteffen** [comment]
@jordanskole I am using the same library how were you able to get rid of it?

**Comment by jordanskole** [comment]
Sorry @lassesteffen I think I jumped the gun, that didn't fix the issue. I was able to get past the `UnhandledPromiseRejectionWarning` but I was back to sending an empty object :(

**Comment by lassesteffen** [comment]
> There, the header is handled case-sensitive so you have to have both content-type and Content-Type until its fixed in this module.

How can I set this header in apollo client or apollo-server-lambda?

**Comment by mathix420** [comment]
> Sorry @lassesteffen I think I jumped the gun, that didn't fix the issue. I was able to get past the `UnhandledPromiseRejectionWarning` but I was back to sending an empty object :(

Which client are you using ?

**Comment by jordanskole** [comment]
@mathix420 ApolloClient 2.6.8

**Comment by maxgr0** [comment]
> > There, the header is handled case-sensitive so you have to have both content-type and Content-Type until its fixed in this module.
> 
> How can I set this header in apollo client or apollo-server-lambda?

directly in your handler (before `server.createHandler(...)`)

`if(Object.keys(event.headers).includes('Content-Type')){
    event.headers['content-type'] = event.headers['Content-Type'];
  }`

**Comment by mathix420** [comment]
@jordanskole I'm not sure if the your client can be the problem but one simple way to know that is by using [Altair client](https://altair.sirmuel.design/).
If you can upload your image and get back your file infos from Altair you'll need to change your client configuration

**Comment by jordanskole** [comment]
Thanks @mathix420, I tried that and I ran into the same error with Altair 😞so far I have been using serverless-offline. I will try and deploy and see if that fixes the issue.

**Comment by maxgr0** [comment]
> Thanks @mathix420, I tried that and I ran into the same error with Altair 😞so far I have been using serverless-offline. I will try and deploy and see if that fixes the issue, unless there are other ideas.

Have you tried changing the headers that you have both lowercase and uppercase content-type?

**Comment by jordanskole** [comment]
I'm not sure I am following where I can modify them, if not in context? My handler.ts file doesn't have access to event/context?

**Comment by maxgr0** [comment]
> I'm not sure I am following where I can modify them, if not in context? My handler.ts file doesn't have access to event/context?

Can you share me your handler.ts?

**Comment by jordanskole** [comment]
Yeah, it's actually up above 

handler.ts
```
import { ApolloServer, defaultPlaygroundOptions } from 'apollo-server-lambda'
import { schema as typeDefs } from './graphql/schema'
import { resolvers } from './graphql/resolvers';
import { createContext, ContextArguments } from './graphql/context'


const server = new ApolloServer({
  typeDefs,
  resolvers,
  playground: true, // defaultPlaygroundOptions,
  context: ({ event, context }: ContextArguments) => createContext({ event, context }),
});

const graphql = server.createHandler({
  cors: {
    origin: true,
    credentials: true,
  },
});


export { graphql }
```

graphql/context:
```
import { Context } from 'aws-lambda';
import Shopify, { IShop } from 'shopify-api-node'
import { getShopDetailsFromToken } from '../lib/jwt'

export type ContextArguments = {
  event: any;
  context: Context;
}

export const createContext = async ({ event, context }: ContextArguments) => {
  try {
    // get the user token from the headers
    const { headers } = event;
    console.log(headers)
    const token: string = event.headers.Authorization || '';
    const shop = token ? await getShopDetailsFromToken(token) : false;
    const shopify = shop ? new Shopify({...shop, autoLimit: true }) : false;
    return { headers, shop, shopify }
  } catch(e) {
    console.log(e)
    return;
  }
}
```

**Comment by maxgr0** [comment]
@jordanskole try this 👋
```
export const graphql: APIGatewayProxyHandler = (event, context, callback) => {
  if(Object.keys(event.headers).includes('Content-Type')){
    event.headers['content-type'] = event.headers['Content-Type'];
  }
  const handler = server.createHandler({
    cors: {
      origin: true,
      credentials: true
    }
  });
  return handler(event, context, callback);
};
```

**Comment by jordanskole** [comment]
That was it! 🙏🏼feel free to share your email with me I'd love to buy you a beer!

**Comment by maxgr0** [comment]
> That was it! 🙏🏼feel free to share your email with me I'd love to buy you a beer!

all good, cheers!

**Comment by jordanskole** [comment]
Hey @mathix420 , I'm back! 

I have my application running fine locally, but I am having trouble actually deploying to AWS, and I think it _might_ be related to this, since the error is getting tossed from the `fileUploadHandler` function.

I'm currently running alpha.1 and I haven't had any issues running everything locally. This is of course barking about preflight CORS when I get to staging, but I think because preflight is failing since all of the below errors are happing in playground and CORS shouldn't be an issue there -- but perhaps I am wrong?

Should this be a separate issue?

Hitting playground throws the following error (on POST request):

```
{
    "errorType": "SyntaxError",
    "errorMessage": "Unexpected token e in JSON at position 0",
    "stack": [
        "SyntaxError: Unexpected token e in JSON at position 0",
        "    at JSON.parse (<anonymous>)",
        "    at graphqlHandler (/var/task/node_modules/apollo-server-lambda/dist/lambdaApollo.js:27:26)",
        "    at /var/task/node_modules/apollo-server-lambda/dist/ApolloServer.js:169:16",
        "    at fileUploadHandler (/var/task/node_modules/apollo-server-lambda/dist/ApolloServer.js:163:28)",
        "    at /var/task/node_modules/apollo-server-lambda/dist/ApolloServer.js:166:13",
        "    at Runtime.exports.graphql [as handler] (/var/task/src/handler.js:31:12)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```

Here is the complete event:
```
{
  resource: '/graphql',
  path: '/graphql',
  httpMethod: 'POST',
  headers: {
    Accept: '*/*',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9',
    'apollo-query-plan-experimental': '1',
    'CloudFront-Forwarded-Proto': 'https',
    'CloudFront-Is-Desktop-Viewer': 'true',
    'CloudFront-Is-Mobile-Viewer': 'false',
    'CloudFront-Is-SmartTV-Viewer': 'false',
    'CloudFront-Is-Tablet-Viewer': 'false',
    'CloudFront-Viewer-Country': 'US',
    'content-type': 'application/json',
    Host: 'hz59wd6bjh.execute-api.us-east-1.amazonaws.com',
    origin: 'https://hz59wd6bjh.execute-api.us-east-1.amazonaws.com',
    Referer: 'https://hz59wd6bjh.execute-api.us-east-1.amazonaws.com/v1/graphql',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36',
    Via: '2.0 66ba388c3807ced8474a06fdfcdde4fb.cloudfront.net (CloudFront)',
    'X-Amz-Cf-Id': 'IqNtkUm3dDd-9Jt5PiSnAiMgSi3OIR3IV8qZWHboOOha6x0kKI4eeQ==',
    'X-Amzn-Trace-Id': 'Root=1-5eaecec2-96c15af525480f00a215d6e0',
    'x-apollo-tracing': '1',
    'X-Forwarded-For': '67.149.113.209, 70.132.37.71',
    'X-Forwarded-Port': '443',
    'X-Forwarded-Proto': 'https'
  },
  multiValueHeaders: {
    Accept: [ '*/*' ],
    'Accept-Encoding': [ 'gzip, deflate, br' ],
    'Accept-Language': [ 'en-US,en;q=0.9' ],
    'apollo-query-plan-experimental': [ '1' ],
    'CloudFront-Forwarded-Proto': [ 'https' ],
    'CloudFront-Is-Desktop-Viewer': [ 'true' ],
    'CloudFront-Is-Mobile-Viewer': [ 'false' ],
    'CloudFront-Is-SmartTV-Viewer': [ 'false' ],
    'CloudFront-Is-Tablet-Viewer': [ 'false' ],
    'CloudFront-Viewer-Country': [ 'US' ],
    'content-type': [ 'application/json' ],
    Host: [ 'hz59wd6bjh.execute-api.us-east-1.amazonaws.com' ],
    origin: [ 'https://hz59wd6bjh.execute-api.us-east-1.amazonaws.com' ],
    Referer: [
      'https://hz59wd6bjh.execute-api.us-east-1.amazonaws.com/v1/graphql'
    ],
    'sec-fetch-dest': [ 'empty' ],
    'sec-fetch-mode': [ 'cors' ],
    'sec-fetch-site': [ 'same-origin' ],
    'User-Agent': [
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36'
    ],
    Via: [
      '2.0 66ba388c3807ced8474a06fdfcdde4fb.cloudfront.net (CloudFront)'
    ],
    'X-Amz-Cf-Id': [ 'IqNtkUm3dDd-9Jt5PiSnAiMgSi3OIR3IV8qZWHboOOha6x0kKI4eeQ==' ],
    'X-Amzn-Trace-Id': [ 'Root=1-5eaecec2-96c15af525480f00a215d6e0' ],
    'x-apollo-tracing': [ '1' ],
    'X-Forwarded-For': [ '67.149.113.209, 70.132.37.71' ],
    'X-Forwarded-Port': [ '443' ],
    'X-Forwarded-Proto': [ 'https' ]
  },
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: null,
  stageVariables: null,
  requestContext: {
    resourceId: 'tdveht',
    resourcePath: '/graphql',
    httpMethod: 'POST',
    extendedRequestId: 'L9U-XGDnoAMFtKw=',
    requestTime: '03/May/2020:14:01:38 +0000',
    path: '/v1/graphql',
    accountId: '028260149026',
    protocol: 'HTTP/1.1',
    stage: 'v1',
    domainPrefix: 'hz59wd6bjh',
    requestTimeEpoch: 1588514498259,
    requestId: '0a30768c-e1cb-4020-9e81-d901ae10f448',
    identity: {
      cognitoIdentityPoolId: null,
      accountId: null,
      cognitoIdentityId: null,
      caller: null,
      sourceIp: '67.149.113.209',
      principalOrgId: null,
      accessKey: null,
      cognitoAuthenticationType: null,
      cognitoAuthenticationProvider: null,
      userArn: null,
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36',
      user: null
    },
    domainName: 'hz59wd6bjh.execute-api.us-east-1.amazonaws.com',
    apiId: 'hz59wd6bjh'
  },
  body: 'eyJvcGVyYXRpb25OYW1lIjoiSW50cm9zcGVjdGlvblF1ZXJ5IiwidmFyaWFibGVzIjp7fSwicXVlcnkiOiJxdWVyeSBJbnRyb3NwZWN0aW9uUXVlcnkge1xuICBfX3NjaGVtYSB7XG4gICAgcXVlcnlUeXBlIHtcbiAgICAgIG5hbWVcbiAgICB9XG4gICAgbXV0YXRpb25UeXBlIHtcbiAgICAgIG5hbWVcbiAgICB9XG4gICAgc3Vic2NyaXB0aW9uVHlwZSB7XG4gICAgICBuYW1lXG4gICAgfVxuICAgIHR5cGVzIHtcbiAgICAgIC4uLkZ1bGxUeXBlXG4gICAgfVxuICAgIGRpcmVjdGl2ZXMge1xuICAgICAgbmFtZVxuICAgICAgZGVzY3JpcHRpb25cbiAgICAgIGxvY2F0aW9uc1xuICAgICAgYXJncyB7XG4gICAgICAgIC4uLklucHV0VmFsdWVcbiAgICAgIH1cbiAgICB9XG4gIH1cbn1cblxuZnJhZ21lbnQgRnVsbFR5cGUgb24gX19UeXBlIHtcbiAga2luZFxuICBuYW1lXG4gIGRlc2NyaXB0aW9uXG4gIGZpZWxkcyhpbmNsdWRlRGVwcmVjYXRlZDogdHJ1ZSkge1xuICAgIG5hbWVcbiAgICBkZXNjcmlwdGlvblxuICAgIGFyZ3Mge1xuICAgICAgLi4uSW5wdXRWYWx1ZVxuICAgIH1cbiAgICB0eXBlIHtcbiAgICAgIC4uLlR5cGVSZWZcbiAgICB9XG4gICAgaXNEZXByZWNhdGVkXG4gICAgZGVwcmVjYXRpb25SZWFzb25cbiAgfVxuICBpbnB1dEZpZWxkcyB7XG4gICAgLi4uSW5wdXRWYWx1ZVxuICB9XG4gIGludGVyZmFjZXMge1xuICAgIC4uLlR5cGVSZWZcbiAgfVxuICBlbnVtVmFsdWVzKGluY2x1ZGVEZXByZWNhdGVkOiB0cnVlKSB7XG4gICAgbmFtZVxuICAgIGRlc2NyaXB0aW9uXG4gICAgaXNEZXByZWNhdGVkXG4gICAgZGVwcmVjYXRpb25SZWFzb25cbiAgfVxuICBwb3NzaWJsZVR5cGVzIHtcbiAgICAuLi5UeXBlUmVmXG4gIH1cbn1cblxuZnJhZ21lbnQgSW5wdXRWYWx1ZSBvbiBfX0lucHV0VmFsdWUge1xuICBuYW1lXG4gIGRlc2NyaXB0aW9uXG4gIHR5cGUge1xuICAgIC4uLlR5cGVSZWZcbiAgfVxuICBkZWZhdWx0VmFsdWVcbn1cblxuZnJhZ21lbnQgVHlwZVJlZiBvbiBfX1R5cGUge1xuICBraW5kXG4gIG5hbWVcbiAgb2ZUeXBlIHtcbiAgICBraW5kXG4gICAgbmFtZVxuICAgIG9mVHlwZSB7XG4gICAgICBraW5kXG4gICAgICBuYW1lXG4gICAgICBvZlR5cGUge1xuICAgICAgICBraW5kXG4gICAgICAgIG5hbWVcbiAgICAgICAgb2ZUeXBlIHtcbiAgICAgICAgICBraW5kXG4gICAgICAgICAgbmFtZVxuICAgICAgICAgIG9mVHlwZSB7XG4gICAgICAgICAgICBraW5kXG4gICAgICAgICAgICBuYW1lXG4gICAgICAgICAgICBvZlR5cGUge1xuICAgICAgICAgICAgICBraW5kXG4gICAgICAgICAgICAgIG5hbWVcbiAgICAgICAgICAgICAgb2ZUeXBlIHtcbiAgICAgICAgICAgICAgICBraW5kXG4gICAgICAgICAgICAgICAgbmFtZVxuICAgICAgICAgICAgICB9XG4gICAgICAgICAgICB9XG4gICAgICAgICAgfVxuICAgICAgICB9XG4gICAgICB9XG4gICAgfVxuICB9XG59XG4ifQ==',
  isBase64Encoded: true
}
```

and that body base64decoded (just an introspection) 
```
{"operationName":"IntrospectionQuery","variables":{},"query":"query IntrospectionQuery {\n  __schema {\n    queryType {\n      name\n    }\n    mutationType {\n      name\n    }\n    subscriptionType {\n      name\n    }\n    types {\n      ...FullType\n    }\n    directives {\n      name\n      description\n      locations\n      args {\n        ...InputValue\n      }\n    }\n  }\n}\n\nfragment FullType on __Type {\n  kind\n  name\n  description\n  fields(includeDeprecated: true) {\n    name\n    description\n    args {\n      ...InputValue\n    }\n    type {\n      ...TypeRef\n    }\n    isDeprecated\n    deprecationReason\n  }\n  inputFields {\n    ...InputValue\n  }\n  interfaces {\n    ...TypeRef\n  }\n  enumValues(includeDeprecated: true) {\n    name\n    description\n    isDeprecated\n    deprecationReason\n  }\n  possibleTypes {\n    ...TypeRef\n  }\n}\n\nfragment InputValue on __InputValue {\n  name\n  description\n  type {\n    ...TypeRef\n  }\n  defaultValue\n}\n\nfragment TypeRef on __Type {\n  kind\n  name\n  ofType {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}\n"}
```

**Comment by mathix420** [comment]
Hi @jordanskole, hope you're fine

Not sure but it looks like your issue is identical as this one #2599

**Comment by jordanskole** [comment]
Hey @mathix420 

Thanks for your help! That did fix the first issue I had, but now I am still struggling. 

Everything works in my staging deployment now except for my single fileUpload mutation resolver, which attempts to stream data to cloudinary. 

I _think_ this has something to do with the lower-case content-type header again, since API Gateway says it refers to the *Content-Type* header: "API Gateway will look at the Content-Type and Accept HTTP headers to decide how to handle the body."

> _API Gateway enacts the following restrictions and limitations when handling methods with either Lambda integration or HTTP integration._
> 
> - _Header names and query parameters are processed in a case-sensitive way._


Both Altair and `createUploadLink` (from `apollo-upload-client`) are setting the lowe-case `content-type` header

**Comment by mathix420** [comment]
> after base64 decoding the request

Did you skip the decoding when a `multipart/form-data` is recieved ?
If not have you put `event.isBase64Encoded` to false ?

**Comment by jordanskole** [comment]
@mathix420 amazing! you are my hero again. You are definitely getting a shoutout on this app when it launches. For anybody that finds their way back here, this is what my complete handler looks like now:


```
export const graphql: APIGatewayProxyHandler | APIGatewayProxyResult = (event, context, callback) => {
  try {

    if(Object.keys(event.headers).includes('Content-Type')){
      event.headers['content-type'] = event.headers['Content-Type'];
    }
    
    if (
      event.isBase64Encoded
      && event.body
      && (
        !event.headers['content-type'].includes('multipart/form-data')
      )
    ) {
       event = {
         ...event,
         body: Buffer.from(event.body, "base64").toString(),
         isBase64Encoded: false
       }
    }
    const handler = server.createHandler({
      cors: {
        origin: true,
        credentials: true
      }
    });
    return handler(event, context, callback);
  } catch (e) {
    console.log(e)
    return callback(e)
  }
};
```

**Comment by lanwen** [comment]
Thank you for the wrapper, but with aws api gateway v2 and payload format v1 gives error:
```json
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object",
    "reason": [
        {
            "errorType": "TypeError",
            "errorMessage": "The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object",
            "message": "The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ],
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:315:20)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}
```

what could be the reason for that?

**Comment by lassesteffen** [comment]
I have the same error.

**Comment by Umkus** [comment]
Same error here as well.

**Comment by mathix420** [comment]
@lanwen could you please give us more context ?

**Comment by lanwen** [comment]
@mathix420 Its a apollo-server-lambda, with one mutation calling apollo-upload

We use aws-cdk (1.55) to deploy the lambda packed with webpack (nothing special there, just handler as in examples above ^^^ as input and output, using ts)

```js
const fn = new lambda.Function(this, id, {
      runtime: lambda.Runtime.NODEJS_12_X,
      handler: "lambda.handler",
      memorySize: 256,
      code: lambda.Code.fromAsset(lambdaAsset),
    });

    const api = new gw.HttpApi(this, "graphql-api", {
      createDefaultStage: false,
    });

    api.addRoutes({
      path: "/graphql",
      methods: [gw.HttpMethod.POST, gw.HttpMethod.GET, gw.HttpMethod.OPTIONS],
      integration: new gw.LambdaProxyIntegration({
        handler: fn,
        // https://github.com/apollographql/apollo-server/issues/3958
        payloadFormatVersion: gw.PayloadFormatVersion.VERSION_1_0,
      }),
    });

    const stage = new gw.HttpStage(this, "DeploymentStage", {
      httpApi: api,
      stageName: environment,
      autoDeploy: true,
    });
```
Here is an event which comes into handler
```js
{
  version: '1.0',
  resource: '/graphql',
  path: '/staging/graphql',
  httpMethod: 'POST',
  headers: {
    'Content-Length': '5288',
    'Content-Type': 'multipart/form-data; boundary=---------------------------7180963393185668272703501002',
    Host: 'some-api-id.execute-api.region.amazonaws.com',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0',
    'X-Amzn-Trace-Id': 'Root=1-5f282a99-5ad69cbafb4710',
    'X-Forwarded-For': '1.2.3.4',
    'X-Forwarded-Port': '443',
    'X-Forwarded-Proto': 'https',
    accept: '*/*',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-GB,en;q=0.5',
    authorization: 'eyJh...HgfdA',
    origin: 'https://something.cloudfront.net',
    referer: 'https://something.cloudfront.net/something/'
  },
  multiValueHeaders: {
    'Content-Length': [ '5288' ],
    'Content-Type': [
      'multipart/form-data; boundary=---------------------------7180963393185668272703501002'
    ],
    Host: [ 'some-api-id.execute-api.region.amazonaws.com' ],
    'User-Agent': [
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0'
    ],
    'X-Amzn-Trace-Id': [ 'Root=1-5f282a4710' ],
    'X-Forwarded-For': [ '1.2.3.4' ],
    'X-Forwarded-Port': [ '443' ],
    'X-Forwarded-Proto': [ 'https' ],
    accept: [ '*/*' ],
    'accept-encoding': [ 'gzip, deflate, br' ],
    'accept-language': [ 'en-GB,en;q=0.5' ],
    authorization: [
      'eyJhbGciOiJ...HgfdA'
    ],
    origin: [ 'https://something.cloudfront.net' ],
    referer: [ 'https://something.cloudfront.net/something/' ]
  },
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  requestContext: {
    accountId: '1',
    apiId: 'some-api-id',
    domainName: 'some-api-id.execute-api.region.amazonaws.com',
    domainPrefix: 'some-api-id',
    extendedRequestId: 'QsBQ=',
    httpMethod: 'POST',
    identity: {
      accessKey: null,
      accountId: null,
      caller: null,
      cognitoAuthenticationProvider: null,
      cognitoAuthenticationType: null,
      cognitoIdentityId: null,
      cognitoIdentityPoolId: null,
      principalOrgId: null,
      sourceIp: '1.2.3.4',
      user: null,
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0',
      userArn: null
    },
    path: '/staging/graphql',
    protocol: 'HTTP/1.1',
    requestId: 'QQ=',
    requestTime: '03/Aug/2020:15:17:45 +0000',
    requestTimeEpoch: 1596467865307,
    resourceId: 'POST /graphql',
    resourcePath: '/graphql',
    stage: 'staging'
  },
  pathParameters: null,
  stageVariables: null,
  body: 'LS0tLS0tL...(some base64 png)...aA2RgwG...zM5MzE4NTY2ODI3MjcwMzUwMTAwMi0tDQo=',
  isBase64Encoded: true
}
```

dependencies:
```json
"dependencies": {
    "@types/form-data": "^2.5.0",
    "apollo-datasource-rest": "^0.9.3",
    "apollo-server": "^2.16.0",
    "apollo-server-lambda": "^2.16.0",
    "commander": "^6.0.0",
    "form-data": "^3.0.0",
    "graphql": "^14.0.0",
    "graphql-iso-date": "^3.6.1"
  },
```
requiest don't come to our resolver and got failed somewhere before. Wasn't able to reproduce with serverless offline locally, didn't try if dependent on the deployment type (like using old rest-api)

**Comment by Umkus** [comment]
Seems like this always happens, unless I replace the `event.body` with `Buffer.from(event.body, 'base64').toString()` and set `isBase64Encoded` to `false`. But then the images seem broken for me.

**Comment by mathix420** [comment]
I think you should check this issue https://github.com/apollographql/apollo-server/issues/4430, it seems that this issue is due to recent changes https://github.com/apollographql/apollo-server/pull/4311

**Comment by Umkus** [comment]
This setup worked for me (using `2.16.1`):

```javascript

export function handler(event, context, callback) {
  if (Object.keys(event.headers).includes('Content-Type')) {
    event.headers['content-type'] = event.headers['Content-Type'];
  }

  if (event.isBase64Encoded && event.body && event.headers['content-type'].includes('multipart/form-data')) {
    event.body = Buffer.from(event.body, 'base64').toString('binary');
    event.isBase64Encoded = false;
  }

  return server.createHandler({
    cors: {
      origin: true,
      credentials: true,
    },
  })(event, context, callback);
}

```

**Pull request merged**
