### PR TITLE
fix(fastify): return reply object from async handlers

### PR DESCRIPTION
**Pull request by SimenB**
I'm trying to use this module with `fastify@4`, but we never got a response. Adding the `return` statements fixed that issue. It's somewhat mentioned in the migration guide (https://medium.com/@fastifyjs/fastify-v4-ga-59f2103b5f0e).

Note that this also works in fastify 3

### CODE REVIEW

**Comment by glasser** [comment]
We've come to the conclusion that supporting Fastify v3 and v4 in the same release of apollo-server-fastify is not feasible (https://github.com/apollographql/apollo-server/issues/6576#issuecomment-1159249244 and some other comments). The forthcoming AS4 disentangles the precise versions of web framework integrations from Apollo Server's own version and should make supporting any Fastify version easy. (It will also allow us to hand off maintenance of the framework integration to people who actually use Fastify in any context other than trying to evaluate PRs like this one.)

Is this PR also helpful for Fastify v3 users?

**Comment by SimenB** [comment]
>Is this PR also helpful for Fastify v3 users?

Yes, making sure to return `Reply` from handlers have fixed bugs in our own (currently v3) code base, albeit not when using `.send`. Support was added back in https://github.com/fastify/fastify/pull/1869/files#diff-e5866ff20d3d7c44302e5bf2096c0c2112e6e8de8e41c0f0df9dbf7146f4ba71 (released in v2). Mostly for cases where the last thing you do is _not_ `.send`, but still. There's also [this issue](https://github.com/fastify/fastify-reply-from/issues/105) (again, not `send`).

So while I don't think this is necessary for `fastify@3` it certainly doesn't hurt, and is a well-supported pattern. And seeing as it _does_ make it work with `fastify@4`, I don't think there's any reason to land it? Even if the code is moved out of this repo later

**Comment by ro-savage** [comment]
@glasser - The fact there is a small PR that supported fastify v4 from an amazing OSS contributor like @SimenB -- I don't under why this is being considered?

It requires only a review from the team -- is a simple change -- and makes no negative impact on current users.

**Comment by glasser** [comment]
Reviewing this is on my todo list, but every time I review a Fastify PR I basically have to re-learn how Fastify works from scratch (which is why we're passing that responsibility over to community members who actually use Fastify as part of AS4). But yes, high on my todo list, and certainly the contributor's reputation makes me suspect it will be fine :)

**Comment by glasser** [comment]
Published in v3.10.2.

**Comment by SimenB** [comment]
Thanks! ❤️

**Comment by natenrb9** [comment]
Should this theoretically enable support for Fastify v4?
I am getting this error:

`FastifyError: fastify-plugin: fastify-accepts - expected '3.x' fastify version, '4.4.0' is installed`

Do something else need to be upgraded in the `apollo-server` dependencies to support Fastify v4?

**Comment by SimenB** [comment]
This is the only code change needed, but you also need to update the deps (which would be a breaking change, so won't happen in this repo). With yarn 2 or 3 like

```json
{
  "resolutions": {
    "apollo-server-fastify/@fastify/accepts": "^4.0.0",
    "apollo-server-fastify/@fastify/cors": "^8.0.0"
  }
}
```

I have no idea how to do it for npm or pnpm, but there are probably ways (npm use `overrides`).

**Comment by glasser** [comment]
yes, as mentioned above (https://github.com/apollographql/apollo-server/issues/6576#issuecomment-1159249244), we can't support multiple incompatible versions of Fastify from the same major version of the same apollo-server-fastify package. We are fixing this by decoupling "apollo server package version" from "apollo server web package X integration  package version" in AS4 but will not be fixing it for AS3.

**Comment by natenrb9** [comment]
> This is the only code change needed, but you also need to update the deps (which would be a breaking change, so won't happen in this repo). With yarn 2 or 3 like
> 
> ```json
> {
>   "resolutions": {
>     "apollo-server-fastify/@fastify/accepts": "^4.0.0",
>     "apollo-server-fastify/@fastify/cors": "^8.0.0"
>   }
> }
> ```
> 
> I have no idea how to do it for npm or pnpm, but there are probably ways (npm use `overrides`).

For anyone interested that works with npm to add Fastify v4 support.

I had to add this to my package.json, and then I ran `npm update --save`.  I also had to update my npm version to support `overrides`.

```
"overrides": {
    "apollo-server-fastify": {
      "@fastify/accepts": "^4.0.0",
      "@fastify/cors": "^8.0.0"
    }
  },
```

**Pull request merged**
