### PR TITLE
chore(deps): update dependency accept to @hapi/accept and boom to @ha…

### PR DESCRIPTION
**Pull request by campanagerald**
This PR contains the following updates:

Package: accept
Change: accept: 3.0.2 -> @hapi/accept: 5.0.1

Package: boom
Change: boom: 7.1.0 -> @hapi/boom": 9.1.0

### CODE REVIEW

**Comment by rtrys** [comment]
hi @apollo-cla / @campanagerald, can you go ahead with this PR?

**Comment by abernix** [comment]
We've started the upgrades to Hapi (core) in the `release-3.0` branch, though these particular upgrades haven't been included yet.  In that regard, I've gone ahead and re-targeted this to the `release-3.0` branch and put this in the _Release 3.x_ milestone.

However, I'm unsure how the changes in this PR (which just touch `package.json` and `package-lock.json`) would be sufficient on their own since there are `import`s of these modules that also would need to be changed (and possibly, the 
 API usage, too?).

@campanagerald Would you be taking that on?

**Comment by rtrys** [comment]
hi @campanagerald, are you going to take care of this PR? I think it is an important change that must be included in the next release

**Comment by glasser** [comment]
This is now fixed on the `release-3.0` branch via #5150. I incorporated parts of your PR into it. Thanks!

**Pull request closed without merging**
