### PR TITLE
docs how to implement modules

### PR DESCRIPTION
**Pull request by daniele-zurico**
TODO:

* [ ] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [ ] Make sure all of the significant new logic is covered by tests
* [ ] Rebase your changes on master so that they can be merged easily
* [ ] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by daniele-zurico** [comment]
Why this PR is getting so long to be merged? There’s a specific reason?

**Comment by zero298** [comment]
Please merge this.  Not seeing this in the documentation made me hesitant to actually leverage modules in my new Apollo project because I thought it might be deprecated.

**Comment by daniele-zurico** [comment]
I’m sorry,
But I really don’t feel correct the behaviour. I spent time to improve the documentation I asked if there was a reason why it wasn’t merged and I never got a reply and now you close it without giving any reason?
It’s quite a disappointed behaviour to be honest

**Comment by abernix** [comment]
Unintentional closing! Please stand-by: https://github.com/apollographql/apollo-server/issues/4304

**Comment by daniele-zurico** [comment]
Given this PR is sitting here from 2y....shall I close it? I suppose you don't need it

**Comment by glasser** [comment]
To be honest, I have never really understood the motivation behind having "modules" as its own top-level concept that involves a dependency on our `@apollographql/apollo-tools` package (https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-tools/src/buildServiceDefinition.ts), when we already support passing both `typeDefs` and `resolvers` as arrays.

Is there actually a difference between

```
new ApolloServer({modules})
```

and

```
new ApolloServer({typeDefs: modules.map(m => m.typeDefs), resolvers: modules.map(m => m.resolvers)})
```
?

I'm not really clear why it's such an important feature to even warrant existing, let alone its own page in the docs. Especially given that as your PR mentions, it doesn't support custom scalars?

I also think that if we were to update these docs for today, we wouldn't want to talk about schema stitching but about federation (and perhaps some of the use cases for "modules" would just want to use federation instead?)

I'm going to close this because I don't think this is a great fit for our docs now, but I'm definitely open to users explaining to me why this option is important.

**Pull request closed without merging**
