### PR TITLE
Fastify: update to version 2

### PR DESCRIPTION
**Pull request by jebh**
Hi, this updates apollo-server-fastify to version 2 and is a breaking change because v2 changes 'beforeHandler' in the route definition to 'preHandler'. Given how new the fastify integration is, perhaps this is not such a big problem?

Additionally, the fastify cors module has been updated to work with version 2.

### CODE REVIEW

**Comment by clarkbrent** [comment]
This is still an open issue as reported in #2397 .

Also, this PR still works with fastify@2.1.0, and passes all tests if you want to update it @jebh .

**Comment by abernix** [comment]
> On the other hand, I can really respect the desire for you to get onto the latest version.
>
> The `apollo-server-fastify@2` package (which ships with `fastify@1`) hasn't been out _too_ long (#2280; https://github.com/apollographql/apollo-server/pull/1971#issuecomment-463726327) and perhaps, just perhaps, it would be worth overlook semantic versioning for the sake of moving the Fastify package forward.

**Comment by abernix** [comment]
> An other option would be to just create an `apollo-server-fastify2` and deprecate and retire `apollo-server-fastify` entirely.

**Comment by PabloSzx** [comment]
any updates on this?

**Comment by ogheo** [comment]
up

**Comment by mhf-ir** [comment]
Fastify long time using version 2 but deprecated method still exist.
https://github.com/apollographql/apollo-server/issues/2397

I think this PR must be merge.

**Comment by rankery** [comment]
Any updates for it?

**Comment by tuananh** [comment]
can someone take a look into this?

**Comment by lednhatkhanh** [comment]
Hello, any updates on this?

**Comment by codehimanshu** [comment]
Hi, any updates on this,  I am facing the following issue as soon as I switched to fastify from express:

> Warning: The route option `beforeHandler` has been deprecated, use `preHandler` instead
crit: Error in reloading rules during initialization {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3306,"fatal":true,"meta":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3306,"fatal":true}}

It seems like Database connection is not receiving correct config.
Not sure but can this be an issue because of Fastify beforeHandlers?

**Comment by markrzen** [comment]
Resolved https://github.com/apollographql/apollo-server/issues/3477

**Comment by andreimc** [comment]
This change is needed as fastify will remove beforeHandlers in v3 and that's coming out soon

**Comment by PabloSzx** [comment]
@abernix any comment on closing this PR?

**Comment by abernix** [comment]
Unintentional closing! Please stand-by: https://github.com/apollographql/apollo-server/issues/4304

(Though side-note, my plan is to just bump this version in AS3 since it's a breaking change.  It's very much on my mind.)

**Comment by SimenB** [comment]
Fastify v3 is right around the corner, fwiw. Would be nice to either bump straight to that, or allow both somehow

**Comment by abernix** [comment]
Please see the update I just posted on https://github.com/apollographql/apollo-server/pull/4356#issuecomment-677515901 for the availability of the Fastify v3 support on Apollo Server.

**Pull request closed without merging**
