### PR TITLE
Release 2.6.1

### PR DESCRIPTION
**Pull request by abernix**
This reverts an unintended breaking change in Apollo Server 2.6.1 which caused
`typeDefs` which were defined as a `string` rather than a `DocumentNode` (i.e.
wrapped in the `gql` template tagged literal) to result in an error within the
new `isDirectiveDefined` functionality.

This was reported in https://github.com/apollographql/apollo-server/issues/2753.

TypeScript users would have been guarded against using `typeDefs` as a string,
but in JavaScript, there is no such protection and `typeDefs` historically have
frequently `string`-typed because of the internal `graphql-tools` usage which
supported this pattern.

And in case any readers of this didn't know, while many will wrap their
`typeDefs` in the `gql` tag hoping to gain syntax-highlighing in their editor
(a very good reason!), it does also do more — like parse its body into a
`DocumentNode`!

```
6adec0ad (Jesse Rosenberger, 9 minutes ago)
   Add CHANGELOG.md for breaking change inadvertently introduced in 2.6.0.

   Also added the MISSING `CHANGELOG.md` from the original release which I 
   somehow stomped out!

   Ref: #2428

c742335a (Jesse Rosenberger, 13 minutes ago)
   Revert "Avoid duplicate `cacheControl` directives via `isDirectiveDefined`
   (#2428)"

   This reverts commit 4e84defd23112ef19f502193105a7597bc6886be.
```

### CODE REVIEW

**Comment by abernix** [comment]
```
Successfully published:
 - apollo-cache-control@0.7.1
 - apollo-engine-reporting@1.2.1
 - @apollo/gateway@0.6.1
 - apollo-server-azure-functions@2.6.1
 - apollo-server-cloud-functions@2.6.1
 - apollo-server-cloudflare@2.6.1
 - apollo-server-core@2.6.1
 - apollo-server-express@2.6.1
 - apollo-server-fastify@2.6.1
 - apollo-server-hapi@2.6.1
 - apollo-server-koa@2.6.1
 - apollo-server-lambda@2.6.1
 - apollo-server-micro@2.6.1
 - apollo-server-plugin-base@0.5.1
 - apollo-server-plugin-response-cache@0.2.1
 - apollo-server-testing@2.6.1
 - apollo-server@2.6.1
 - apollo-tracing@0.7.1
 - graphql-extensions@0.7.1
```

**Comment by abernix** [comment]
Big thank you to @trevor-scheer 	for helping to track down the cause of this!

**Comment by wKovacs64** [comment]
Hmm, did the 2.6.1 release go sideways? Can't seem to install even though npm shows the 2.6.1 version exists. Tried a few of the packages listed (e.g. `apollo-server@2.6.1`, `apollo-server-express@2.6.1`, etc.). Yarn prompts to select a version and npm says the following:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for apollo-server-express@2.6.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by fullstackwebdev** [comment]
This broke my CICD server
```
yarn install v1.15.2
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find any versions for "apollo-server-express" that matches "2.6.1"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

ERROR: for backend  (<Service: backend>, "The command '/bin/sh -c npx yarn' returned a non-zero code: 1")
Service 'backend' failed to build: The command '/bin/sh -c npx yarn' returned a non-zero code: 1
ERROR: Job failed: exit code 1

```

**Comment by trevor-scheer** [comment]
@wKovacs64 @fullstackwebdev can either of you still reproduce the issue? I was seeing it for a few minutes, but it seems to have cleared up for me. Seems like some funny CDN business.

**Comment by wKovacs64** [comment]
Agreed, seems fine now. Weird.

**Pull request merged**
