### PR TITLE
Example server link for WSS is broken

### PR DESCRIPTION
**Pull request by VladimirDev93**

### CODE REVIEW

**Comment by abernix** [comment]
Thanks for taking the time to submit a docs PR!  Though this seems to break things for me.  Did you run into a problem here you could explain?  The anchor is actually `#ssl`:

https://github.com/apollographql/apollo-server/blob/cf9892694b6ab7c2cca8cc6dd7e7d953e56fd490/docs/source/essentials/server.md#L146

and the generated page is `.html` (not `.md`) which is why it (and other links) use the `.html` extension.

You can see the deploy preview on this PR: https://deploy-preview-2060--apollo-server-docs.netlify.com/docs/apollo-server/features/subscriptions.html#wss to try it out.

**Comment by VladimirDev93** [comment]
Hi @abernix and thank you for your quick response!

I should have had written a bit more detail about this PR so that the community could understand what this PR is about. 

This PR is not related to website documentation, but rather for a documentation that is broken [here](https://github.com/apollographql/apollo-server/blob/master/docs/source/features/subscriptions.md#securing-subscriptions-with-wss). If you click on the **example server** link, it leads to a 404 GitHub page.

So sorry that I didn't provide little more detail!

**Comment by abernix** [comment]
Ah, okay, I see!  Thank you for the explanation!

The website documentation is published from that source, and that's the target we should have.

Yes, in an ideal world, both GitHub and Hexo would land on exactly the same patterns and they'd both be completely usable (they are the same exact content, after all), but the documentation — for now — is designed to be read/browsed/searched from https://apollographql.com/docs/apollo-server and not from here on GitHub.

Sorry for the confusion, and thanks for trying to fix it.  We're currently making some changes to our underlying documentation infrastructure, which I fully expect will improve this situation, and I'll pass this along to that team so they're aware of this nuance.

Thanks again for the contribution attempt!

**Comment by abernix** [comment]
(To be a bit more concrete: if we were to merge this, it would break _the other_ rendered version of the documentation.  So no matter what we do here right now, we're at the mercy of something being broken, and it seems better if it was the raw markdown source that was broken, rather than the rendered documentation.)

**Pull request closed without merging**
