### PR TITLE
Update to graphql@0.12

### PR DESCRIPTION
**Pull request by stubailo**
TODO:

- [ ] Update CHANGELOG.md with your change (include reference to issue & this PR)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] Rebase your changes on master so that they can be merged easily
- [ ] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by VladShcherbin** [comment]
@stubailo hey, apollo client has support for graphql 0.12. Any eta on this one?

**Comment by dyst5422** [comment]
I'm waiting on this change for an internal release. Anything I can do to help move it along?

**Comment by n1ru4l** [comment]
0.13 is already out 😱

**Comment by kachkaev** [comment]
Also looking forward to seeing `peerDependencies` updated. There are npm install warnings in graphql-yoga because graphql 0.13 is not mentioned in Apollo's packages: https://github.com/graphcool/graphql-yoga/issues/38#issuecomment-366937003

**Comment by abernix** [comment]
The changes in this PR were released as 1.3.2.

**Pull request merged**
