### PR TITLE
Do not remove Query/Mutation/Subscription types when schema is included if schema references those types

### PR DESCRIPTION
**Pull request by JoeTravisKiva**
Attempting to resolve https://github.com/apollographql/apollo-server/issues/3100
 Where including a schema descriptor that references the default type names for Query, Mutation or Subscription prevents the intended extensions from appearing in the federated schema

### CODE REVIEW

**Comment by DevYukine** [comment]
if this fixes #3100 i would really appreciate it because i can't get my JVM GraphQL Endpoint to work with Apollo-Gateway 😞

**Comment by trevor-scheer** [comment]
This looks great, thank you for the contribution @JoeTravisKiva! I'll merge now and get this released first thing Monday morning 👍

**Comment by markguinn** [comment]
Any chance this will still see a release today?

**Comment by trevor-scheer** [comment]
@markguinn @telbot apologies for the delay on this, this is released in `@apollo/federation@0.10.0` 😄

Release commit:
https://github.com/apollographql/apollo-server/commit/6100fb5e0797cd1f578ded7cb77b60fac47e58e3

**Pull request merged**
