### PR TITLE
Ensure `executionDidEnd` hooks are only called once

### LINKED ISSUE #6567: Handle end-hook-thrown errors correctly
https://github.com/apollographql/apollo-server/blob/54416e28835adb0117f89935c11aa270248272d5/packages/apollo-server-core/src/requestPipeline.ts#L247-L250

https://github.com/apollographql/apollo-server/blob/54416e28835adb0117f89935c11aa270248272d5/packages/apollo-server-core/src/requestPipeline.ts#L436-L441

In (at least) these two cases, if the end hook itself throws, we then call it _again_ in the catch block (but with no try/catch if it throws!). I'd say these try/catches incorrectly assume that the hook won't throw, but we should be prepared for it to throw and handle it gracefully.

This probably means calling the hook after the try/catch or something else which doesn't result in the end hook possibly being called twice.

### PR DESCRIPTION
**Pull request by trevor-scheer**
Reproduction in first commit, resolution with test updates in second commit.

`executionDidEnd` hooks are currently called within both the try and catch clauses of the same block. This means that if a hook throws, they'll be called _again_ in the catch.

Similar to changes made for `parsingDidEnd` in https://github.com/apollographql/apollo-server/issues/6679, we now call the `executionDidEnd` hooks _after_ the try/catch and within the catch. This ensures they'll only ever be called once.

Fixes #6567

### CODE REVIEW

**Comment by glasser** [comment]
Great, and this error will now get sent to unexpectedErrorProcessingRequest instead, right?

**Comment by trevor-scheer** [comment]
@glasser right. I forgot we added that hook but probably would've been a good addition to this test. We do still see that code path exercised via the logger call and error that's thrown.

Maybe we just want a few tests for that hook?

**Comment by glasser** [comment]
Oops, probably should just have approved rather than merged — good call that more hook tests would be better.

**Comment by trevor-scheer** [comment]
No worries, opened an issue for myself when I'm back

**Pull request merged**
