### PR TITLE
Update restify lib

### PR DESCRIPTION
**Pull request by liyucun**
Update restify lib for apollo-server-restify. Referring to issue: #472

### CODE REVIEW

**Comment by liyucun** [comment]
Does the integration test broken?

**Comment by stubailo** [comment]
I think the tests should be working fine... let me see.

**Comment by stubailo** [comment]
Hmm, it does look like the failing tests are unrelated to the PR.

**Comment by liyucun** [comment]
Hmm, a bit weird, and maybe i miss something?

**Comment by martijnwalraven** [comment]
Thanks! The tests all seem to pass after the latest merge, not sure what went wrong before.

**Pull request merged**
