### PR TITLE
Enable overriding services for local dev with managed config in Apollo Gateway

### PR DESCRIPTION
**Pull request by michael-watson**
This PR enables developers to start up an `ApolloGateway` instance with [managed federation](https://www.apollographql.com/docs/graph-manager/managed-federation/overview/) and override services in the managed configuration to point a local dev environments. 

To enable overriding a **single service**, the Apollo Gateway would respond to three environment variables being set:

- `APOLLO_SERVICE_OVERRIDE=true`
- `APOLLO_SERVICE_OVERRIDE_NAME` - name of the service to change url of
- `APOLLO_SERVICE_OVERRIDE_URL` - local dev environment url

To enable override a **list of services**, the user would define a local json file that contains the list of `ServiceDefinitions`:
- `APOLLO_SERVICE_OVERRIDE=localOverride.json` - assumes root directory, but can provide absolute path
_localOverride.json_
```
{
  "servicesToOverride": [
    {
      "name": "accounts",
      "url": "http://localhost:4001"
    }
  ]
}
```

## Pros of current implementation
- local developers don't need to change code of gateway
- can clone gateway repo or startup gateway artifact with environment variables set
- local json file can be put into `.gitignore`

## Cons
- Another config file to manage, I suppose this could be put into the `apollo.config.js` as well. It was just quicker/easier for me to do any json file

### Other Options

I think there are also other patterns that can be considered here instead of a local configuration file. we could simply do a comma separated list and stick to only two environment variables (`APOLLO_SERVICE_OVERRIDE_NAME` and `APOLLO_SERVICE_OVERRIDE_URL`). There could also be the option to put this configuration into the `engine` configuration options. 

I haven't created an entry in the changelog yet because I wanted to wait until we landed on exactly how we want this to look. I like this option, but I'm biased.

### CODE REVIEW

**Comment by tizmagik** [comment]
This LGTM! Should there be any indication/warning message when an override is specified for a service that doesn't currently exist in managed mode? Or does that enable folks to add additional services locally?

**Comment by tizmagik** [comment]
Good points @jhampton ! +1 to explicit configuration over this collection of ENV vars 👍

**Comment by michael-watson** [comment]
@tizmagik There is a [console log when the service name provided can't be found in the service list](https://github.com/apollographql/apollo-server/blob/michael-watson/override-managed-service/packages/apollo-gateway/src/index.ts#L858), but now you bring up a great point. I think the developer **should** be able to add an additional service and we just log details to the console that the service was added to the configuration. I added this functionality in the latest commit.

@jhampton I get what you're saying and I added the hard coded config option. For anyone seeing this that might be wanting to just set environment variables in a docker image of your gateway, or just cloning the repo, here is a code snippet of what you can do:

```
let shouldOverrideServices = process.env.APOLLO_SERVICE_OVERRIDE;
let serviceOverrides = shouldOverrideServices ? setupServiceOverrides() : [];

function setupServiceOverrides() {
    let overrides = [];
    if (shouldOverrideServices == 'true') {
        overrides.push({ name: process.env.APOLLO_SERVICE_OVERRIDE_NAME, url: process.env.APOLLO_SERVICE_OVERRIDE_URL });
    } else {
        let localOverrideConfigFile = JSON.parse(readFileSync(resolve(__dirname, shouldOverrideServices), { encoding: "utf8" }));
        localOverrideConfigFile.servicesToOverride.map(serviceOverride => overrides.push({ ...serviceOverride }))
    }

    return overrides;
}

const gateway = new ApolloGateway({ debug: true, serviceOverrides });
```

**Comment by jhampton** [comment]
Can I assume this is deprecated in favor of a new approach @michael-watson ?

**Comment by abernix** [comment]
Hi @michael-watson!,

> This is a semi-automated message.  Apologies for the lack of personal detail.  I’d encourage reading the rest of this message but, if you're busy, hopefully this is as easy for you — or someone who is willing to own the contribution — as pushing the button later in this message to re-create this PR, from an auto-migrated branch, on the new Federation repository.  If you have time, read on!

We’re in the process of moving federation-related concerns out of this repository (where it has historically lived) into a new home specifically for Apollo Federation.   **This PR is affected by the transition since it touches code which has been moved**.

I’ve done some preparations to make this as easy as possible, but **we’ll need to close this PR, and I could use your help in re-opening it on the new Apollo Federation repository.**

In https://github.com/apollographql/federation/pull/134 (which has a lot more details, if you’re interested), we introduced the same code that was in this repository to the new Federation repository (maintaining its history) and removed the code from this repository in https://github.com/apollographql/apollo-server/pull/4561.

While **this** PR still needs to get reviewed and approved to land, it should no longer live in this repository in its current state since it cannot merge in anymore.  To facilitate the movement of this PR to the new home, I’ve **automatically generated branches on the new repository** using the same commit authorship and messages that you originally included on this PR.

Pull-requests can’t be moved on GitHub in the same way _Issues_ can be.  While I could just create the PRs from these new branches too, the contribution belongs to you!

---

**Original PR author only: Click this button to open a new PR from the auto-created  `apollo-server-import/pr-4245` branch on the new Apollo Federation repository**

[Original PR author: Click here to re-create this PR on the Federation repository](https://github.com/apollographql/federation/compare/main...apollo-server-import/pr-4245?expand=1&title=Enable+overriding+services+for+local+dev+with+managed+config+in+Apollo+Gateway&body=This+PR+enables+developers+to+start+up+an+%60ApolloGateway%60+instance+with+%5Bmanaged+federation%5D%28https%3A%2F%2Fwww.apollographql.com%2Fdocs%2Fgraph-manager%2Fmanaged-federation%2Foverview%2F%29+and+override+services+in+the+managed+configuration+to+point+a+local+dev+environments.+%0D%0A%0D%0ATo+enable+overriding+a+**single+service**%2C+the+Apollo+Gateway+would+respond+to+three+environment+variables+being+set%3A%0D%0A%0D%0A-+%60APOLLO_SERVICE_OVERRIDE%3Dtrue%60%0D%0A-+%60APOLLO_SERVICE_OVERRIDE_NAME%60+-+name+of+the+service+to+change+url+of%0D%0A-+%60APOLLO_SERVICE_OVERRIDE_URL%60+-+local+dev+environment+url%0D%0A%0D%0ATo+enable+override+a+**list+of+services**%2C+the+user+would+define+a+local+json+file+that+contains+the+list+of+%60ServiceDefinitions%60%3A%0D%0A-+%60APOLLO_SERVICE_OVERRIDE%3DlocalOverride.json%60+-+assumes+root+directory%2C+but+can+provide+absolute+path%0D%0A_localOverride.json_%0D%0A%60%60%60%0D%0A%7B%0D%0A++%22servicesToOverride%22%3A+%5B%0D%0A++++%7B%0D%0A++++++%22name%22%3A+%22accounts%22%2C%0D%0A++++++%22url%22%3A+%22http%3A%2F%2Flocalhost%3A4001%22%0D%0A++++%7D%0D%0A++%5D%0D%0A%7D%0D%0A%60%60%60%0D%0A%0D%0A%23%23+Pros+of+current+implementation%0D%0A-+local+developers+don%27t+need+to+change+code+of+gateway%0D%0A-+can+clone+gateway+repo+or+startup+gateway+artifact+with+environment+variables+set%0D%0A-+local+json+file+can+be+put+into+%60.gitignore%60%0D%0A%0D%0A%23%23+Cons%0D%0A-+Another+config+file+to+manage%2C+I+suppose+this+could+be+put+into+the+%60apollo.config.js%60+as+well.+It+was+just+quicker%2Feasier+for+me+to+do+any+json+file%0D%0A%0D%0A%23%23%23+Other+Options%0D%0A%0D%0AI+think+there+are+also+other+patterns+that+can+be+considered+here+instead+of+a+local+configuration+file.+we+could+simply+do+a+comma+separated+list+and+stick+to+only+two+environment+variables+%28%60APOLLO_SERVICE_OVERRIDE_NAME%60+and+%60APOLLO_SERVICE_OVERRIDE_URL%60%29.+There+could+also+be+the+option+to+put+this+configuration+into+the+%60engine%60+configuration+options.+%0D%0A%0D%0AI+haven%27t+created+an+entry+in+the+changelog+yet+because+I+wanted+to+wait+until+we+landed+on+exactly+how+we+want+this+to+look.+I+like+this+option%2C+but+I%27m+biased.+%0A---%0AOriginally+at%3A+apollographql%2Fapollo-server%234245)

(The code and your commits should be the same and **you will have an opportunity to confirm**, but this way you can continue to be the author and track its progress on the new Federation repository!)

---

There’s no easy way to bring over any existing comments on this PR, so I encourage you to copy and paste those onto the new issue if possible.

Overall, I hope this process is _relatively_ easy for you while maintaining your commit contribution authorship.  I apologize for any inconvenience caused by this shuffle, but please ping me if I can help in any way!

:rocket:

**Pull request closed without merging**
