### PR TITLE
apollo-server-core: Remove deprecated ApolloServer.schema field

### LINKED ISSUE #5148: AS3: Remove deprecated ApolloServer.schema field
It doesn't even work for gateways.

Note the comment about it when setting 'initialized with schema'.

### PR DESCRIPTION
**Pull request by glasser**
This field never worked with gateways.

Fixes #5148.

### CODE REVIEW

**Review by abernix — APPROVED** [review]

**Comment by abernix** [comment]
LGTM.  Do you want to track PRs like this on a milestone / marker for CHANGELOG-building purposes?

**Comment by abernix** [comment]
Correction to my comment, I know you edited the CHANGELOG already, so I guess I just mean for tracking purposes, in general.

**Comment by glasser** [comment]
@abernix The issue it Fixes is on the milestone (and on the Project I just made); not sure it helps to have the PR be too in that case?

**Comment by abernix** [comment]
Yeah, not sure.  I'm generally duplicative, but I recognize that's problematic in its own way.

**Pull request merged**
