### PR TITLE
fix: Use event.requestContext.path on lambda playground when available

### LINKED ISSUE #2136: lambda: playground Server cannot be reached
Hi team,

### Intended outcome

Using `"apollo-server-lambda": "^2.3.1"` expect the playground work fine.

---

### Actual outcome

Outcome in Playground webiste right side show 
```
{
  "error": "Response not successful: Received status code 403"
}
```

Check the browser console. The network's response in playground is `{"message":"Forbidden"}`

Note. I can test my graphQL api with curl command or aws lambda test. Only playground can not work fine.

---

### How to reproduce the issue

Here is my serverless.yml
```yml
service: jk-bot

custom:
  BOT_FB: "jk-bot-fb-table"

provider:
  name: aws
  runtime: nodejs8.10
  stage: v1
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["JkBotFb", "Arn"] }
  environment:
    BOT_FB: ${self:custom.BOT_FB}

resources:
  Resources:
    JkBotFb:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.BOT_FB}

functions:
  graphql:
    handler: handler.graphql
    events:
      - http:
          path: graphql
          method: POST
          cors: true
      - http:
          path: graphql
          method: GET
          cors: true
```

Here is my handler.js
```javascript
const { ApolloServer, gql } = require("apollo-server-lambda");
const { botTypeDef, botResolvers } = require("./models/bot");

const typeDefs = gql`
  ${botTypeDef}
`;
const resolvers = botResolvers;

const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: ({ event, context }) => ({
    headers: event.headers,
    functionName: context.functionName,
    event,
    context
  }),
  playground: {
    settings: {
      "request.credentials": "same-origin"
    }
  }
});

exports.graphql = server.createHandler({
  cors: {
    origin: "*",
    credentials: true
  }
});
```

### Issue might relative
* https://github.com/apollographql/apollo-server/issues/1500
* https://github.com/prisma/graphql-playground/issues/748
* https://github.com/prisma/graphql-playground/issues/826

---

Could anyone help this situation. Any better idea?

### PR DESCRIPTION
**Pull request by taogilaaa**
Should fix #2136 

TODO:

* [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by abernix** [comment]
@Kcin1993 Are you able to confirm that this would solve the issue you identified in #2136.  I'm also trying to determine if this might be a major-semver breaking change since it changes which `path` it is served on, but I may not understand the AWS Lambda environment enough to be certain .  Input appreciated!

**Comment by leggomuhgreggo** [comment]
@abernix @taogilaaa I'm also running into this issue and happy to lend a hand to prove out this PR. Thanks! 🙏

**Comment by Kcin1993** [comment]
@abernix  @taogilaaa 

Change local node_modules `apollo-server-lambda` just like this [fix](https://github.com/apollographql/apollo-server/pull/2241/commits/2f95295d6f44fcb335a6e6d69a7ac7c5ebab7380)

But the outcome still the same.`"error": "Response not successful: Received status code 403"`

---

Try the workaround taogilaaa metion above

* the url of playground is correct 
* `"error": "Response not successful: Received status code 502"`

image

Thanks this [reply](https://github.com/apollographql/apollo-server/issues/2136#issuecomment-458465128). Let me know more about `event`

**Comment by taogilaaa** [comment]
I have difficulties confirming the changes using my diff from the monorepo but basically [this](https://github.com/taogilaaa/serverless-basic-graphql)  is what i did

[serverless.yml](https://github.com/taogilaaa/serverless-basic-graphql/blob/master/serverless.yml)
[handler](https://github.com/taogilaaa/serverless-basic-graphql/blob/master/src/handler.js)

@Kcin1993 That's interesting, can you share your `serverless.yml` config and also the lambda handler ? I'm assuming we need to manually specify a valid `graphql` endpoint if we separate the playground url, something like

```
const server = new ApolloServer({
  typeDefs,
  resolvers,
  playground: {
    endpoint: '/v1/graphql'
  }
});
```

@abernix I've exposed `event` query resolver that will return json of the received event [here](https://p8c87nunv8.execute-api.ap-southeast-1.amazonaws.com/dev/graphql) if you want to play around with it

**Comment by Kcin1993** [comment]
@taogilaaa 
Thanks for your [repo](https://github.com/taogilaaa/serverless-basic-graphql). Simplify my code. This works fine!

**Comment by glasser** [comment]
As stated on https://github.com/apollographql/apollo-server/issues/2136#issuecomment-1267644842 this is probably no longer an issue, and definitely will no longer be a relevant issue for this repo once AS4 is out. Sorry for the delay!

**Pull request closed without merging**
