### PR TITLE
types: add support for passing typedefs as strings

### PR DESCRIPTION
**Pull request by 19majkel94**
TODO:

* [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by 19majkel94** [comment]
@abernix 
Should I update the changelog with this fix? Which package's changelog should I update (global? server-core?) 😉

**Comment by 19majkel94** [comment]
@martijnwalraven @abernix 
Any progress on revewing this tremendous PR? 😄

**Comment by abernix** [comment]
@19majkel94 I'm not opposed to this, but this PR doesn't link to an issue, so I'm not sure if there's an existing proposal or a reason for why this is necessary right now.  Can you help define the use-case here?

It's worth pointing out that — because of the use of `graphql-tools`' `ITypeDefinitions` — this change wouldn't just bring support for `typeDefs` defined as a string, but also also bring support for defining `typeDefs` as [a function which returns an array of `typeDefs`](https://github.com/apollographql/graphql-tools/blob/2394f0c3a8b30dbd4435dd21019727e76e61b892/src/Interfaces.ts#L87-L88).

That may be fine, but we'd want to build out tests for that.  That said, I think I'd want to hold off on building this out further until we discuss the use-case in more detail.

**Comment by 19majkel94** [comment]
@abernix 

My use-case is rather simple:
```ts
  const typeDefs = readFileSync(__dirname + "/schema.gql", {
    encoding: "UTF-8",
  });

  const server = new ApolloServer({
    typeDefs,
    resolvers,
  });
```

And I can confirm it works with `apollo-server` after casting to `any` because `typeDefs` are passed to `graphql-tools` that supports strings. So we should keep things in sync rather than rewriting the typings.

**Comment by 19majkel94** [comment]
@abernix Is there anything more I can do towards this PR? 😕

**Comment by abernix** [comment]
Thanks for submitting this!  I'll close this since this was resolved, albeit in a more round-about way, via https://github.com/apollographql/apollo-server/commit/77207ffadef1a3cfe3fc164e9a42a3b492974efd.  (Though your approach here would have worked as well, and had we accepted it when you submitted it, would have probably spared us from the regression that occurred in 2.6.6!)

**Pull request closed without merging**
