### PR TITLE
5288 - Allow setting response status

### PR DESCRIPTION
**Pull request by nathan-melly**
This PR is for https://github.com/apollographql/apollo-server/issues/5288 and makes the following changes:
- Uncomment `statusCode` in the `ApolloServerHttpResponse` type, allowing it to be added to `responseInit` objects
- Set `responseInit.status` to `response.http.status` (if it exists) in `runHttpQuery`
- In each of the server implementations, set the status code to `responseInit.status` or 200 if `responseInit.status` is not set, keeping the default behaviour the same as the existing behaviour
- Add test to cover all server implementations

### CODE REVIEW

**Comment by glasser** [comment]
I actually just yesterday started touching related code in #5156. I think this is a good idea but would best be built on top of that PR (so either target its branch if you're very fast or more likely `release-3.0`).

**Comment by glasser** [comment]
That PR is merged, so just base on `release-3.0`. (We're unlikely to add any new features to AS2 at this point.)

FWIW I don't love the fact that `runHttpQuery` throws errors and its callers all need to handle the "success" case and the "failure" case separately instead of just returning a response with an error in it... but I don't think I'm going to change that API shape right now.

**Comment by nathan-melly** [comment]
@glasser Ready to review 👍🏻

**Comment by glasser** [comment]
Thanks @nathan-melly! I rebased again and added a CHANGELOG.

**Comment by nathan-melly** [comment]
Thanks @glasser 🚀  Do you have any idea when a release containing this commit will be made?

**Comment by glasser** [comment]
It's my main focus. I just released a feature-complete preview, 3.0.0-preview.2.  Hopefully will get a full migration guide written by early next week.

**Pull request merged**
