### PR TITLE
Avoid duplicate `cacheControl` directives via `isDirectiveDefined`

### PR DESCRIPTION
**Pull request by cheapsteak**
This PR adds a utility function `isDirectiveDefined` and uses it to guard against duplicate directives when the user's schema already contains a directive (in this case, cacheControl)

TODO:

* [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by akadop** [comment]
Thanks for working on this!

**Comment by glasser** [comment]
I also think the text of the cache control directive should be exported by apollo-cache-control

**Comment by stevez86** [comment]
Any chance this will be merged anytime soon?

**Comment by stevez86** [comment]
I didn't realize that I could generate my own schema and get around this, you might want to add something in the documentation

**Comment by abernix** [comment]
This caused the regression in #2753, which is best explained in the body of https://github.com/apollographql/apollo-server/pull/2754, which contains its reversion.

@cheapsteak 	Not sure if you'll have the opportunity to revisit, but just letting you know!   (Also as noted above, passing your own schema is a work-around, so potentially less urgent!)

**Pull request merged**
