### PR TITLE
Transform interfaces into possible types only

### PR DESCRIPTION
**Pull request by vitramir**
Fix for issue https://github.com/apollographql/apollo-server/issues/3253

### CODE REVIEW

**Comment by rtymchyk** [comment]
@trevor-scheer This is a pretty small change but fixes a big pain point with using interfaces - are you the best person to take a look?

**Comment by martijnwalraven** [comment]
@rtymchyk I'm currently looking into this and some related issues, that I suspect we'll want to fix together. I hope to have more to say on this next week.

**Comment by rtymchyk** [comment]
Thanks for the update @martijnwalraven :)

**Comment by ksaldana1** [comment]
Any update regarding these issues @martijnwalraven? We've been playing with federation a bunch at work, but some of the issues around interfaces are a bit of a blocker at the moment to fully investing. There are workarounds we can do in the meantime, but obviously that's less than ideal. 

Thanks for your hard work!

**Comment by godspeedelbow** [comment]
Same here. We trying to roll this out but running into this issue.

**Comment by vitramir** [comment]
@godspeedelbow @ksaldana1 Does this PR solve your case?

**Comment by godspeedelbow** [comment]
@vitramir I don't how to test it, is there a way to easily use this PR's version of the code as a dependency so I can try it out?

**Comment by vitramir** [comment]
@godspeedelbow I've published it as @apollo-model/federation and @apollo-model/gateway

Source: https://github.com/apollo-model/apollo-server/tree/custom-package

**Comment by rtymchyk** [comment]
This PR fixes the issue for me.

**Comment by godspeedelbow** [comment]
I can confirm that this fixes our issue too.

@martijnwalraven any news when a fix will be shipped?

**Comment by trevor-scheer** [comment]
Closing this in favor of the PR that was just landed: #3529

Thanks again for this contribution @vitramir! We appreciate all of your help in identifying this issue and taking steps to resolve it. I've added co-authorship for you on the merge commit: https://github.com/apollographql/apollo-server/commit/43d3ac10ae505121f75634781648b66b2a4b0b7c

**Pull request closed without merging**
