### PR TITLE
Rest datasource trace protected

### PR DESCRIPTION
**Pull request by halfzebra**
Hello friends!

Thanks for maintaining this project! 👍 

This PR is another take at https://github.com/apollographql/apollo-server/pull/2182, which was originally closed.

Closes https://github.com/apollographql/apollo-server/issues/2009

Let me know what you think!

### CODE REVIEW

**Comment by halfzebra** [comment]
Hi @abernix! Any chance you have time to do a review for this?

**Comment by mikecaulley** [comment]
This would be nice to have merged. We are currently overriding the trace in a project to add some custom timing metrics.

**Comment by halfzebra** [comment]
@mikecaulley I feel like it's kind of hard decision for the maintainers as we are proposing to increase the API surface, which would probably mean some hidden cost for them.

Either way, I'm up for updating this PR anytime if it ever gets the attention.

**Comment by capaj** [comment]
please merge this. It would be very welcome addition for small projects now that apollo-studio is not free to use even for the smallest of projects.

**Comment by rosieshanley** [comment]
I’m sure you all had good reasons for postponing this for now, but I agree with @capaj that this would be a much appreciated addition.

**Comment by rval** [comment]
Would also love to see this merged! May not seem like a big deal but the unnecessary `console.log` output really clutters up output when running our test suite.

**Comment by glasser** [comment]
This looks straightforward enough, and I definitely think people should have control over their console output. Gonna bring this up to date with main and merge if it works.

(Full disclosure: I'm thinking quite seriously that RESTDatasource, while a really helpful tool, doesn't need to be part of Apollo Server core in AS3.  We introduced "dataSources" into AS in June 2018, and then added the new plugin interface in October of that year. As far as I can tell, everything you can do with dataSources you can do with plugins too. So I'm imagining a world where apollo-datasource and apollo-datasource-rest are deprecated, and instead there's an `@apollo/server-plugin-rest` (on its own release cycle not strongly tied to Apollo Server, compatible with v2 and the future v3) that makes it easy to define RESTDataSources and inject them to where they are accessible by resolvers.)

**Review by glasser — APPROVED** [review]

**Comment by halfzebra** [comment]
Thanks for merging this! :+1:

**Comment by glasser** [comment]
Released in v2.20.0.

**Pull request merged**
