### PR TITLE
Call formatError when passed in options to runHttpQuery, fixes #1439

### LINKED ISSUE #1439: apollo-server-core formatError never called
We're using [**runHttpQuery**] from apollo-server-core on lambda and passing **formatError** as one of the options.
However this handler never gets called back when exception is raised in resolver...

`resolve = (source, args, context, info) => {
    throw new Error("This is generic error");
  }
`

Is this meant for other types of errors?

Notes: I had a look at runHttpQuery which passes the formatError to runQuery but it looks like runQuery never uses this handler (I'm also using [formatResponse] which gets called without issues)

### PR DESCRIPTION
**Pull request by tgriesser**
Another pass at #1660

The formatError option is being ignored if it's added in the `options` outside of the ApolloServer constructor (in `runHttpQuery`). This is fairly common use in contexts like lambda, and seems like a pretty big regression. This PR moves the code into `doRunQuery` and unshifts onto the extension stack, so it runs before the engine reporting agent, as the comments suggest it should.

TODO:

* [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by abernix** [comment]
Sorry for the delay on this.

The `doRunQuery` function no longer exists and has been rolled up into the new request pipeline (see #1795).  We don't recommend calling `runHttpQuery` directly which, unless you explicitly passed your own extension which implemented behavior which reacted to `formatError` as well, would still exhibit this same behavior.  That said, I agree that it's weird that `runHttpQuery` still seems to accept `formatError` and does nothing with it, but I also believe it to be an _internal_ API (and always has been, as far as I'm aware).  We'll should still try to fix this, but it's not a high priority, and I'd still not recommend using it.

Luckily, your concern should be addressed — even on Lambda — by constructing an instance of `ApolloServer` (per the documentation) and, in the case of Lambda, using the result of that instantiated `ApolloServer`'s `createHandler` method:

```js
const { ApolloServer, gql } = require("apollo-server-lambda");

const typeDefs = gql`
  type Query {
    hello: String
  }
`;

const resolvers = {
  Query: {
    hello: (parent, args, context) => {
      return "Hello, world!";
    }
  }
};

const server = new ApolloServer({
  typeDefs,
  resolvers,
  formatError(err) {
    err.message = "Manipulated";
    return err;
  },
});

exports.handler = server.createHandler();
```

I suspect this should work properly for you.  If you're still struggling with it, please do ping for a re-open!

**Comment by abernix** [comment]
I should add, I'm very grateful for you taking the time to look at this — twice!

**Comment by tgriesser** [comment]
@abernix I'm mainly looking to be able to access the request's context within `formatError`, is this possible with the approach you mentioned?

**Comment by gajus** [comment]
Was this ever released?

As far as I can tell, `formatError` is never called.

**Pull request closed without merging**
