### PR TITLE
Include the compatible graphql version to incremental delivery docs

### PR DESCRIPTION
**Pull request by thomaswelton**
Updated the [documentation on incremental delivery](https://www.apollographql.com/docs/apollo-server/workflow/requests#incremental-delivery-experimental) to include the specific prerelease version of graphQL that Apollo Server is compatible with for incremental delivery.

The current docs state "As of September 2022...", but a new pre release version was made available in 2023 https://github.com/graphql/graphql-js/releases/tag/v17.0.0-alpha.3 and this appears to contain a breaking change in the incremental payload delivery.

### CODE REVIEW

**Comment by trevor-scheer** [comment]
@thomaswelton did you confirm that `alpha.2` is working? We currently test against a specific canary, maybe we should update those references to `alpha.2` as well.
i.e. our tests use `graphql@17.0.0-alpha.1.canary.pr.3361.04ab27334641e170ce0e05bc927b972991953882`

**Comment by thomaswelton** [comment]
For our test cases Alpha 2 works, we're now using defer in production

**Comment by trevor-scheer** [comment]
@thomaswelton would you mind updating the couple references in the repo to `alpha.2`? I can as well if you don't mind me pushing to your branch.

**Comment by thomaswelton** [comment]
@trevor-scheer Sure done

**Review by trevor-scheer — APPROVED** [review]
Thanks!

**Pull request merged**
