### PR TITLE
Apollo Server 2.0: AWS DynamoDB Cache Integration

### PR DESCRIPTION
**Pull request by MeixnerTobias**
TODO:

* [ ] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [ ] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by MeixnerTobias** [comment]
Please consider this as additional apollo-server package to help serverless community using Lambda for example avoiding long polling connections such as Redis/Memcached.....using DynamoDB instead which has it's own DAX cache too.

I wrote more about it:
https://medium.com/@meixnertobias/automatic-persisted-queries-on-aws-using-cloudfront-serverless-and-dynamodb-1328ca26d1c2

Looking forward to maintain in future as well.

I need help with adding the test - not familiar with JEST....if someone could jump on this:
https://github.com/apollographql/apollo-server/pull/1278/files#diff-043c0e1c991f0baa93b77b0e9886c024

Thank you

**Comment by MeixnerTobias** [comment]
@clarencenpy Hi, I think there might be 2 other options e.g.
https://github.com/99xt/serverless-dynamodb-local
> Requires Serverless framework & Java - it's a Node wrapper around the Local DynamoDB
otherwise this can work
https://github.com/mhart/dynalite

or maybe (never tried):
https://github.com/localstack/localstack

**Comment by clarencenpy** [comment]
I think that another great option moving forward is for you to publish the `apollo-server-dynamodb` package. It will be a great win to link DynamoDB users to your package, while also encouraging others to share third party cache implementations as well (:

**Comment by MeixnerTobias** [comment]
Closing in favor of npm publication

**Pull request closed without merging**
