### PR TITLE
feat(gateway): CSDL - make `fields` directive args parseable

### PR DESCRIPTION
**Pull request by trevor-scheer**
As an artifact of composition, CSDL should generally be easily consumed by tooling. The existing
format for a `FieldSet` looks like so: `@key(fields: "id")`. Currently, whenever we
make use of that `@key` in existing (related) implementations, we parse the fields argument,
but not before adding a surrounding `{ ... }` set of curly braces to make the string
valid for parsing by the graphql library.

This is fine in JS, but it's an additional step. In Rust (where we're consuming this format
for the first time), modifying strings like this rather than making use of the original string
slice is not nearly as trivial due to lifetimes and ownership. By making this string parseable
as-is, we eliminate a step for anyone using the CSDL format in tooling and eliminate a number of
ergonomic issues for our Rust use case.

### CODE REVIEW

**Comment by glasser** [comment]
I don't have any strong feelings about whether or not the curly braces are "good" but I think if we start adding them to CSDL then they should also be allowed in normal federation input (ie, the federation spec should be updated to say that the argument is optionally enclosed in curlies). 

I will note that the justification does not feel ultra compelling to me. Surely one could extend a GraphQL library in any language to have an entry point that allows parsing the inside of a selection set in addition to an existing entry point that parses the outside of one. Changing a shared data format seems like a much bigger step.

**Comment by trevor-scheer** [comment]
I'm going to land this and open an issue for us to circle back. My takeaway on the conversation here is that we should consider this a pragmatic solution to unblock current work. When the time is right, we can revisit this decision and see if we can't arrive at an **effective** solution that doesn't deviate from the existing `fields` argument format (for user input, without the additional curly braces).

**Comment by trevor-scheer** [comment]
@glasser I don’t disagree this is possible but I think you’re trivializing the overhead of forking and maintaining a fork of a GraphQL parser solely for the sake of being able to parse `SelectionNode[]` instead of the much more common `Document`. This would be a requirement for all consumers of the CSDL format, and that's not a burden I'm willing to impose on even just ourselves, let alone anything that may come of CSDL in OSS outside of Apollo.

> Surely one could extend a GraphQL library in any language to have an entry point that allows parsing the inside of a selection set in addition to an existing entry point that parses the outside of one.

My intent isn't to be argumentative, but I did want to at least address your comment so you know I'm not being dismissive. If you meant something else by `extend` then I'd be curious to hear how you mean, esp. if you see a simpler path to solving this problem.

**Comment by glasser** [comment]
Well, to be fair, it's not a requirement for all consumers — just for all consumers which consider the operation of surrounding a string with two characters to be an undue performance burden.

I do think that we will regret creating a situation where literally every SDL `@key` directive is an illegal CSDL `@key` directive and vice versa.

That said, this was really just a drive-by opinion from me — if my instincts aren't convincing, that's fine!

**Comment by glasser** [comment]
Oh hey, I've got a concrete suggestion that I think will get us the best of both worlds!

What if in CSDL the name of the argument was `selection` instead of `fields`?

Then we would have a simple rule: federation directives (whether in backend schemas or CSDL) with arguments named `fields` have values without curlies, and arguments named `selection` have values with curlies.

It would be mildly odd that the backend schema SDL directive named `@key` has a `fields` argument where the CSDL version has a `selection` argument, but it would still be easy to remember which syntax goes with which argument name.

(One could imagine a later version of the backend schema SDL directive allowing you to pass either argument instead of just `fields`.)

I think this works a lot better than forcing people to remember that sometimes you write `fields: "{ x }"` and sometimes you write `fields: "x"`.

**Pull request merged**
