### PR TITLE
Implement internal directive

### PR DESCRIPTION
**Pull request by KhaledSakr**
This is an implementation of the `@internal` directive discussed in https://github.com/apollographql/apollo-server/issues/2812

### CODE REVIEW

**Comment by trevor-scheer** [comment]
@KhaledSakr, thank you so much for taking this on! I'll need to take a close look at this to make sure it receives proper review and I fully consider the effects of a change like this. Give me a day or two and I'll find the time to look at this in detail.

**Comment by trevor-scheer** [comment]
Hey @KhaledSakr, I think this approach may not be what we're looking for as far as how the `@internal` directive operates. The gateway still needs knowledge of the fields marked as internal so that it can issue queries to services using those fields, but it shouldn't expose them as part of the query-able schema to clients. I don't believe that's possible if we strip the `@internal` fields during the composition step.

I would love to see some integration tests at the gateway level that explores various cases of internal fields. There's plenty of inspiration to draw from (and mock services already set up) in the `packages/apollo-gateway/src/__tests__/integration` directory. Feel free to add to those mocks to accommodate testing the `@internal` directive.

@StephenBarlow will review the docs once the implementation is complete if you feel like continuing to pursue this. Changes to the spec will require @jbaxleyiii 's approval.

Thanks again for digging into this. I'm happy to answer questions as I'm available. Let me know how you'd like to go forward!

**Comment by KhaledSakr** [comment]
Hey @trevor-scheer, thanks for the feedback!

I'd like to continue pursuing this. For my understanding and to be able to create something testable, can you elaborate on a case where this would be useful? By this I mean the gateway being able to issue queries to internal fields.

**Comment by jhampton** [comment]
Hi @KhaledSakr - I was pointed to this PR while investigating a slightly different use case.  I'd like to follow-along here.

I'm wondering if a more generalized approach of allowing _multiple views_ of a schema using a similar kind of directive.

**Comment by trevor-scheer** [comment]
Sure thing @KhaledSakr! One might imagine a service that makes a field available for another service to compute / resolve a different field against. This `internal` field could then be `require`d.

Caveat: possible oversights in this example, I'm winging it.

Products
```graphql
type Product @key(fields: "sku") {
  sku: ID!
  internalID: ID! @internal
}
```

Inventory
```graphql
extend type Product @key(fields: "sku") {
  sku: ID! @external
  internalID: ID! @external
  quantity: Int @requires(fields: "internalID")
}
```

This means that we want the final schema to know about these fields for the sake of query planning, we just don't want the gateway to consider client queries issued with `internal` fields to be considered valid. We also wouldn't want those fields to show up during introspection.

Caveat: I haven't put much thought into this, but a reasonable approach might be to maintain 2 schemas - one complete and one stripped of `@internal` fields. The latter being the schema we would:
* respond to introspection queries with
* validate incoming queries against
* maybe something else, I'm uncertain if this list is complete

Let me know what questions you have. I'd love to hear about your thoughts on implementation (esp. if you have other approaches in mind!) as well as your motivation to build this. Regardless, your interest is appreciated. Thanks again!

**Comment by KhaledSakr** [comment]
That'd be an interesting concept @jhampton, maybe using some sort of "namespacing" for the fields to be available to different consumers. But I think that would be against the one graph principle.

**Comment by KhaledSakr** [comment]
@trevor-scheer That makes sense now, even though it's a little different than the use cause I intended this for. I originally meant for this to be, as I mentioned in the documentation, a way to hide specific queries and mutations from the exposed API. Kind of similar to FilterRootFields when using schema stitching.

Regarding implementation, I have thought of returning the schema including internal fields from  `composeAndValidate`, and then stripping the internal fields before returning the schema from `load`. That way `ApolloGateway`'s schema will be complete and can be used for query planning, while the schema used by `apollo-server` will be stripped out and used for validation and introspection. 

I'd like to hear your feedback on this approach!

**Comment by KhaledSakr** [comment]
@trevor-scheer I'm still waiting for feedback on this. Whenever you have the time we can pick up where we left off.

**Comment by trevor-scheer** [comment]
Hey @KhaledSakr, sorry for the delay on this. There's actually been a lot of parallel discussion within Apollo and it's undecided if we want to go forward with the `@internal` directive or something else with a bit more power and flexibility. For example: https://github.com/apollographql/apollo-server/issues/2812#issuecomment-545089426

**Comment by andrewmcgivery** [comment]
Not to dog pile on this but wanted to bump this and say that I think the ability to have fields used by the gateway and across microservices but not exposed to the consumer of the Gateway would be really helpful! Definitely have use cases for this!

**Pull request closed without merging**
