### PR TITLE
refactor: use Promise constructor to wrap builtin gzip

### PR DESCRIPTION
**Pull request by dnalborczyk**
support for `Cloudflare Workers`

ref: https://github.com/apollographql/apollo-server/issues/6034

### CODE REVIEW

**Comment by glasser** [comment]
I am happy to merge this change because there's nothing particularly negative about it and I trust you that it resolves the CF worker issue.

But it is hard for me to know as a maintainer what to avoid doing in the future — eg, the fact that `zlib` is fine for CF workers and `utils` is not seems unpredictable. If you have any thoughts on something straightforward we can add to our CI process to check that we're not breaking that, that would be awesome — I don't *think* you suggested anything specific on #6034 but I might have missed it.

**Comment by dnalborczyk** [comment]
thank you @glasser for pulling this in!

> I am happy to merge this change because there's nothing particularly negative about it and I trust you that it resolves the CF worker issue.
> 
> But it is hard for me to know as a maintainer what to avoid doing in the future — eg, the fact that `zlib` is fine for CF workers and `utils` is not seems unpredictable.

I agree, that's totally understandable. `Cloudflare Workers` are implemented using the v8 engine (always latest as far as I understand) in addition to Web API (URL, URLSearchParams, URLPattern, TextEncoder etc.). `Wrangler` is the build and deployment tool for CFW. as of v2, they adopted `esbuild` as _default_ bundler, for the fantastic performance, as CFW _currently_ only supports a single file to be deployed. however developers can use _any_ bundler (webpack, rollup, etc.). `esbuild` transforms js/ts, bundles, and minifies - but it doesn't know anything about any node specific built-ins (`util`, `assert` etc.) nor globals (`Buffer`, `process` etc.). Those can be, and are, polyfilled by plugins. if the plugins were up-to-date and fully working none of this would be a problem, unfortunately they are not, as `esbuild` is also a fairly new project.

> If you have any thoughts on something straightforward we can add to our CI process to check that we're not breaking that, that would be awesome — I don't _think_ you suggested anything specific on #6034 but I might have missed it.

Good point. There might be not a straight forward way to easily accomplish that without constraining further development and improvements of Apollo Server. Generally speaking, preferring JS/Web API over platform specific API would definitely help, for CFW or any other platform than node.js, such as deno, bun etc. In addition, avoiding (currently) non-polyfillable modules such as `http`, `fs` etc. would help as well.

I would think most developers who are using CFW are hopefully aware of the implications the platform comes with, and we could (or even should) add some additional suggestions on the the CFW integration docs, such as pinning the deps, and always use lock files etc., otherwise bring it up in an issue or a PR.

**Comment by glasser** [comment]
OK, so waiting til v3 might make sense for this sort of testing?

What's the next step we can take towards getting Cloudflare support on our integrations page? Your package ready for that?

**Comment by dnalborczyk** [comment]
> OK, so waiting til v3 might make sense for this sort of testing?

forgot to mention, `wrangler v2` has support for an `experimental-local` flag, which then uses `miniflare v3` powered by `workerd`. the last couple days I got everything working locally: CFW standalone as well as federation (gateway + subgraphs).

https://github.com/dnalborczyk/apollo-server-cloudflare-workers
https://github.com/dnalborczyk/apollo-federation-cloudflare-workers

`npm start` for local development, might not currently work with `node v19` and/or `npm v9`. I haven't looked into the details.

> What's the next step we can take towards getting Cloudflare support on our integrations page? Your package ready for that?

There's only a couple things left, other than that it should be ready to go, we can move the repo over to `as integrations`:

I removed the `path` and `http method` restriction https://github.com/dnalborczyk/apollo-server-integrations-cloudflare-workers/commit/8859f7c8f3c5fc905c91db07fbdf38f883c687f4  because it did only support POST requests (no GET), and a path was required (should be optional). I want to re-introduce both again at a later time. (will be optional and non-breaking).

another small thing on my todo list is to look at: https://github.com/dnalborczyk/apollo-server-integrations-cloudflare-workers/blob/97c085d7e481a94d668a0b4378d7e9462a3e36d7/src/startServerAndCreateCloudflareWorkersHandler.ts#L97  

last but not least we need to add some tests.

**Pull request merged**
