### PR TITLE
Clean package-lock.json

### PR DESCRIPTION
**Pull request by mjfaga**
While making a minor update in https://github.com/apollographql/apollo-server/pull/5445, I noticed that a clean `npm install` was actually changing the root lock file and figured I'd submit this to clean things up and avoid rouge changes in future PRs.

### CODE REVIEW

**Comment by glasser** [comment]
The `main` branch is not currently under active development. Do you get the same results on `release-3.0`?

**Comment by glasser** [comment]
I think this happens less on release-3.0 due to the npm 7 upgrade. That said, this will help in releasing your #5445.

**Comment by glasser** [comment]
Hmm. I get this reverted when I run `npm i`. This might be an npm version issue?

**Comment by mjfaga** [comment]
I'm running with npm v6.14.13. I had upgrade to 7.* but it introduced tons of changes so I reverted back.

**Pull request merged**
