### PR TITLE
Add proxy support for engine reporting agent

### LINKED ISSUE #1836: [apollo-engine-reporting] Support proxy servers
Hey guys,
Is there any way to set apollo engine reporting metrics to go through a proxy server?

Our environment in production does not have direct access to the internet, so we cannot proceed with apollo-engine metrics for now.

I saw in an older version that `proxyUrl` was supported, but I do not see it in the current apollo versions.

### PR DESCRIPTION
**Pull request by eberhara**
This PR fixes #1836.

TODO:

* [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by eberhara** [comment]
It got resolved!
let's merge it!  :)

**Comment by abernix** [comment]
Thanks for taking the time to work on this!

While this might work for some cases, and presumably works for yours, this offering a `proxyUrl` as a `String` greatly over-simplifies of the configuration necessary for many proxies and because of the `https` specific implementation chosen, might actually create problems for someone wanting to use an `http` proxy (for example, on a local network).  The underlying Node.js HTTP and HTTPS agents ([`http.Agent`](https://nodejs.org/docs/latest-v8.x/api/http.html#http_class_http_agent) and [`https.Agent`](https://nodejs.org/docs/latest-v8.x/api/https.html#https_class_https_agent) respectively) support a number of additional configuration parameters which just cannot be conveyed via a `String`. For example, providing custom certificates, keep-alive configuration, agent pooling rules, re-using an existing agent for performance reasons, specifying protocol families, and more.  For SSL, there are a number of options from [`tls.connect`](https://nodejs.org/docs/latest-v8.x/api/tls.html#tls_tls_connect_options_callback) which must be supported.

I do think there is a change that Apollo might need to make though, but I think it can be much more thin and more feature-rich.  As an alternative implementation, instead of `proxyUrl`, how about a `requestAgent` which can be used using the same familiar API as `http.Agent` and `https.Agent`?  Out of the box, the same API could be utilized (e.g. `undefined` would still use an existing agent or a global agent, if defined. `false` would create a new agent) — with no additional work or dependencies by Apollo.  You'd simply pass an `https.Agent` (you could still use `https-proxy-agent`, if you so desire, but in your own code), which you'd possibly even have already created for other outgoing connections and want re-used.

As an immediate work around, have you tried setting `http.globalAgent` (or `https.globalAgent`) to the appropriate instantiated `Agent`?: `https.globalAgent = yourAgentFromHttpsProxyAgentModuleOrElsewhere`.

**Comment by eberhara** [comment]
hey @abernix,

Not sure whether you tested `https-proxy-agent`, but from the docs:
> This module provides an http.Agent implementation that connects to a specified HTTP or HTTPS proxy server, and can be used with the built-in https module.
So, it works with both http and https proxies connecting to apollo-engine (just tested both cases in production).

So, yes, I believe a proxyUrl string solves the problem for most of the projects that run inside companies infrastructure and need a proxy to report their metrics.

As for the whole bunch of parameters that `http.Agent` receives: In this pull request, I  am solving only the proxy feature.
However, it already enables the possibility to further configure the http.Agent. But the only feature requested so far was the proxy.
My opinion is to resolve the further configuration of the agent when we need to (which isn't now).

I do see your point about having the `agent` as part of the params, not the proxyUrl. However, the configuration is indeed only for the engine reporting agent.
Also, from the perspective of the developer using the lib, I am not sure whether this kind of implementation detail would do any good. Again, whenever we need to further configure the agent, we can expose the configs (not the instance) through the `engine` configuration respecting the interface of the `http.Agent`, but I do not think we should bind the projects using apollo to always set an `http.Agent` instance. For me, it makes more sense to receive the params and then *we* (apollo-engine-reporting) forward that to the agent we chose to use.

As for your immediate work around: Yeah, it is not an option (and I believe that's for most projects running in production) since (currently) nothing but apollo-engine should go through proxy since everything else runs in our internal infrastructure.

What do you think?

**Comment by eberhara** [comment]
@abernix what do you think of this PR #1879 ?

Just want a solution :)

**Comment by abernix** [comment]
Superseded by #1879.

(I like it, Thanks!)

**Comment by abernix** [comment]
Also, yes, I did read the `https-proxy-agent` module and read its code.  Providing a custom SSL certificate is still common practice in many enterprise environments, which is why I still felt strongly the way I did about using the Node.js agent implementation, which has considered this and provides facilities to accommodate it.

**Pull request closed without merging**
