### PR TITLE
Update graphql-upload to v10.0.0

### PR DESCRIPTION
**Pull request by LynchyC**
Update 'singleUpload' tests to reference 'createReadStream' instead of
'stream'

### CODE REVIEW

**Comment by LynchyC** [comment]
Fixes #3508

**Comment by mickeyschwab** [comment]
Does it make sense to bump this to 10 given the latest release?

**Comment by artonio** [comment]
I desperately need this feature, will this be merged soon?

**Comment by abernix** [comment]
Thanks for opening this PR!

Taking a very quick look [at the changelog for `graphql-upload`](https://github.com/jaydenseric/graphql-upload/blob/master/changelog.md#1000), I suspect that landing this upgrade would be a breaking change for the end-user if they haven't made the appropriate changes to their own usage of uploads.  If my suspicion is correct, communicating that need would necessitate bumping the major version of Apollo Server accordingly, which the only hesitation in landing this update right now in Apollo Server 2.x.

If someone (@jaydenseric, perhaps?) could dismiss my above suspicion as invalid, then I'd be happy to land this into Apollo Server 2.x.  Baring that though, we'd need to wait for a major version bump.

However, since we intend on removing the close coupling between `graphql-upload`s and Apollo Server in the next major version, as an alternative approach, I'd love to introduce a guide into Apollo Server's documentation which can hopefully demonstrate how to disable the currently baked-in `graphql-upload` behavior in Apollo Server and show how to use the upstream package directly.

Thoughts?

**Comment by abernix** [comment]
Superseded/duplicated by #4039

**Pull request closed without merging**
