### PR TITLE
Allow to use @provide with interfaces

### PR DESCRIPTION
**Pull request by vitramir**
Solution for this issue https://github.com/apollographql/apollo-server/issues/3231

### CODE REVIEW

**Comment by trevor-scheer** [comment]
Hey @vitramir, thanks for taking the time to put this together! This change makes sense to me, and I don't have any comments to add on the implementation 👍 

Would you mind adding a few tests that demonstrate the new functionality?
We'd also appreciate a changelog entry in `apollo-federation/CHANGELOG.md` 😄

Thanks again!

**Comment by vitramir** [comment]
Ok, I will add some tests

**Comment by vitramir** [comment]
@trevor-scheer I added the test you requested

**Comment by trevor-scheer** [comment]
Thanks @vitramir, apologies for the delay on this. Your test does show composition adding the metadata as expected, but we'd like to see an integration test case that covers this as well.

A great spot for a test like this would be here:
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-gateway/src/__tests__/integration/provides.test.ts

If you have any questions, please let me know. Thanks!

**Comment by trevor-scheer** [comment]
Closing this was a mistake, I targeted the wrong PR. Reopening this one.

**Comment by ksaldana1** [comment]
@vitramir @trevor-scheer Any update on this particular PR? I know a whole bunch of other interface issues got solved with https://github.com/apollographql/apollo-server/pull/3529, but I still feel like I see issues around the interaction of provides + interfaces.

**Comment by vitramir** [comment]
@trevor-scheer I have just read through the thread and understand that I have to add tests. Is it actual task?

**Comment by vitramir** [comment]
@trevor-scheer I have added integration tests

**Comment by jgnieuwhof** [comment]
@vitramir / @trevor-scheer - any updates here? We've got a team here experiencing some pain trying to use interfaces across services in our federated graph; being able to specify `@provides` on a field that returns an interface should allow us to properly route field requests to the appropriate service(s).

This comment from @martijnwalraven suggests that support is intended: https://github.com/apollographql/apollo-server/issues/2987#issuecomment-509431969.

As per https://github.com/apollographql/federation/issues/141, this PR would need to be re-created in the new repo, aside from that are there any real blockers to moving this forward?

If there's anything I can do to help I'd be happy to do so.

**Comment by abernix** [comment]
Hi @vitramir!,

> This is a semi-automated message.  Apologies for the lack of personal detail.  I’d encourage reading the rest of this message but, if you're busy, hopefully this is as easy for you — or someone who is willing to own the contribution — as pushing the button later in this message to re-create this PR, from an auto-migrated branch, on the new Federation repository.  If you have time, read on!

We’re in the process of moving federation-related concerns out of this repository (where it has historically lived) into a new home specifically for Apollo Federation.   **This PR is affected by the transition since it touches code which has been moved**.

I’ve done some preparations to make this as easy as possible, but **we’ll need to close this PR, and I could use your help in re-opening it on the new Apollo Federation repository.**

In https://github.com/apollographql/federation/pull/134 (which has a lot more details, if you’re interested), we introduced the same code that was in this repository to the new Federation repository (maintaining its history) and removed the code from this repository in https://github.com/apollographql/apollo-server/pull/4561.

While **this** PR still needs to get reviewed and approved to land, it should no longer live in this repository in its current state since it cannot merge in anymore.  To facilitate the movement of this PR to the new home, I’ve **automatically generated branches on the new repository** using the same commit authorship and messages that you originally included on this PR.

Pull-requests can’t be moved on GitHub in the same way _Issues_ can be.  While I could just create the PRs from these new branches too, the contribution belongs to you!

---

**Original PR author only: Click this button to open a new PR from the auto-created  `apollo-server-import/pr-3244` branch on the new Apollo Federation repository**

[Original PR author: Click here to re-create this PR on the Federation repository](https://github.com/apollographql/federation/compare/main...apollo-server-import/pr-3244?expand=1&title=Allow+to+use+%40provide+with+interfaces&body=Solution+for+this+issue+https%3A%2F%2Fgithub.com%2Fapollographql%2Fapollo-server%2Fissues%2F3231%0A---%0AOriginally+at%3A+apollographql%2Fapollo-server%233244)

(The code and your commits should be the same and **you will have an opportunity to confirm**, but this way you can continue to be the author and track its progress on the new Federation repository!)

---

There’s no easy way to bring over any existing comments on this PR, so I encourage you to copy and paste those onto the new issue if possible.

Overall, I hope this process is _relatively_ easy for you while maintaining your commit contribution authorship.  I apologize for any inconvenience caused by this shuffle, but please ping me if I can help in any way!

:rocket:

**Pull request closed without merging**
