### PR TITLE
Make it possible to pass custom fetch to rest data source

### PR DESCRIPTION
**Pull request by jbachhardie**
This addresses #1729 

We were unsure whether it would be better for the `RESTDataSource` constructor to take a `fetch` implementation or an options object with a `fetch` property. We stuck to the former because it is simpler, not requiring the creation of a new type, and because the `HTTPCache` constructor seems to be a precedent for this pattern.

I know the feature hasn't been given the go-ahead but we were making these changes for our own use anyway and they're non-breaking so figured we'd put a PR in.

TODO:

* [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by hollsteinm** [comment]
Is there an ETA when the conflicts will be resolved and merged? I am finding this to be a useful feature as well.

**Comment by alexanderkhivrych** [comment]
@jbachhardie  plz merge it ASAP

**Comment by jbachhardie** [comment]
I've resolved the conflicts (which were just changelog stuff) if that's what you mean. I can't merge the PR since I'm not a maintainer.

**Comment by alexanderkhivrych** [comment]
@renovate-bot

**Comment by alexanderkhivrych** [comment]
@jbachhardie  plz pull last master

**Comment by alexanderkhivrych** [comment]
@abernix can you help with this pr, i want to use custom fetch in the data source, because i have good sdk client, so  i want to use it with data source,i don`t want to replace  cache logic, plz ASAP

**Comment by alexanderkhivrych** [comment]
i think it really good option

**Comment by alexanderkhivrych** [comment]
this pr created 1 month  ago, but any responses WTF?

**Comment by alexanderkhivrych** [comment]
https://github.com/apollographql/apollo-server/issues/1729

**Comment by alexanderkhivrych** [comment]
@martijnwalraven

**Comment by intpp** [comment]
@martijnwalraven @abernix @evans merge it please

**Comment by tlgimenes** [comment]
Hey, how is this feature going guys ? I also need it and it looks it's ready for merging ... Thanks !

**Comment by matthewfitch23** [comment]
@jbachhardie do you have an example of how a custom fetch could be used with this?

**Comment by bulka777** [comment]
> @jbachhardie do you have an example of how a custom fetch could be used with this?

```
export class SomeAPI extends RESTDataSource {
  constructor() {
    super(customFetch);
  }
}
```

Would be really awesome to have this so that fetch could be easily instrumented.

**Comment by btaylor-ihr** [comment]
Hey, @jbachhardie, @martijnwalraven, and @abernix :)

Do you know if there is any chance of this getting merged? I'm looking to use https://www.npmjs.com/package/fetch-retry for retry logic whilst avoiding creating my own `RESTDataSource` if I can help it. Let me know if you recommend something else 👍

**Comment by hwillson** [comment]
Thanks very much for working on this @jbachhardie. We'll get this merged shortly.

**Comment by bryancuster** [comment]
I am trying to add in `zipkin-instrumentation-fetch` to our `apollo-server-express` so I needed a custom fetch instance. While passing in a custom instance of `fetch` seems to be working, adding headers seems to have broken in `willSendRequest`.

```js
willSendRequest(request) {
    request.headers.set('Authorization', `Bearer ${this.context.user.bearerToken}`)
  }
```

**Pull request merged**
