### PR TITLE
feat: pass context to formatErrors

### PR DESCRIPTION
**Pull request by JonathanCa97**
If you want to show different types of errors based on your context, for instance personalized errors based on the user (language) that has sent the request, ...

TODO:

* [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by JonathanCa97** [comment]
@abernix , when is this PR going to be watched?

**Comment by tim-soft** [comment]
any blockers here? I'm very keen to see this merged @martijnwalraven @abernix

**Comment by JonathanCa97** [comment]
@martijnwalraven any blocking issues? I want to know why this isn't reviewed/accepted yet.

**Comment by BigMaster** [comment]
I have solved this problem!
[https://github.com/BigMaster/graphql-format-error-context-extension](https://github.com/BigMaster/graphql-format-error-context-extension)

**Comment by DriesVandermeulen** [comment]
It would be very useful to have the context available in the format function.
Is there any way we can get this moving again? @abernix @JonathanCa97 
An extra argument in a function seems like a reasonable (not breaking) change. Any blokkers I can help with?

**Comment by abernix** [comment]
I see the value you might gain by having this additional `context` argument, however, the `formatError` method is meant to match the function signature of the underlying `graphql-js` library, [as defined here](https://github.com/graphql/graphql-js/blob/72bd71e7ecffd8e5ba670ee852032962fcfd4042/src/error/formatError.js) and for compatibility reasons, I think it should stay true to that signature.

That doesn't mean that there shouldn't be a way to accomplish what you're (likely) trying to do though and I'd encourage you to explore the new `didEncounterErrors` life-cycle hook which was introduced in #2719.  There's a bit of an example of how to use it in https://github.com/apollographql/apollo-server/issues/1709#issuecomment-495793375 which should allow you to react to the presence of errors with context-awareness.   (There will be documentation added to https://github.com/apollographql/apollo-server/pull/2008 for `didEncounterErrors`, but I hope that example does the trick for now.)

I think we should explore the possibilities of that new life-cycle hook.  Keep in mind that it's possible to attach properties to an error object in `didEncounterErrors` and that property will eventually be present on the error received by `formatError`.

If this still doesn't work out, please open a new issue so we can come to a consensus on the best approach before moving into a PR.  Ultimately, we'd like to have this be addressable within the request pipeline API.

**Pull request closed without merging**
