### PR TITLE
Earlier example in no longer in production.

### PR DESCRIPTION
**Pull request by sahilrajput03**

### CODE REVIEW

**Comment by sahilrajput03** [comment]
> @sahilrajput03: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

I did accept the agreement!!.
It must be fine now. : )

**Comment by sahilrajput03** [comment]
Whats the status on this pullrequest, coz I don't see any discrepany in additions I made. Please get it out to produciton, cause inability to reproduce result from the current state of docs makes people like me to get frustrated.

**Comment by abernix** [comment]
Can you clarify the workflow that you are running into this in?  You are opening this PR to the v1 version of the documentation, is this something you're running into with Apollo Server v1?

**Comment by sahilrajput03** [comment]
Okay, so I see, there's no documentation on connecting with koa now. But its still the issue as I can see @ https://www.apollographql.com/docs/apollo-server/integrations/middleware/#applying-middleware , coz it points to older koa library i.e., apollo-server-koa which doesn't work actually. 
So i had put the real package that's working at now, i.e., koa-graphiql .
If I try to use apollo-server-koa , it just doens't work and throws no error. :(

**Comment by glasser** [comment]
This PR is to the ancient version 1 of Apollo Server.

We also will no longer be directly maintaining a Koa integration as part of the core AS project when AS4 is fully released this week.

Sorry for the delay!

**Pull request closed without merging**
