### PR TITLE
Move `apollo-engine-reporting` signatures into `apollo-graphql`.

### PR DESCRIPTION
**Pull request by abernix**
Many of these signature calculation functions are now utilized in tools or helpers which are not directly related to `apollo-server` functionality, including various aspects of the `apollo` CLI which live within the [`apollo-tooling` repository](https://github.com/apollographql/apollo-tooling/).

Currently, because of `apollo`'s dependency on `apollo-engine-reporting` for
this signature, this requires bringing in the entire dependency tree since `apollo-engine-reporting` depends on `apollo-server-core`.

By moving this into this new `apollo-graphql` utility library, we're able to trim that rather hefty dependency tree and drastically reduce the download for running, say, `npx apollo`.

Furthermore, this PR makes the additional change of switching to the [modular `lodash.sortby` package](https://www.npmjs.com/package/lodash.sortby) instead of using the whole of `lodash`.  (The only place we use `lodash` in the entire `apollo-server`
repository is to utilize the `sortBy` function for this signature generation.)

Looking at the bundle stats, it appears that `lodash` represents 7.1% of the `apollo-server` package.  We're a server, so bundle size is generally less of a concern, but it's still not to be ignored and it's something we want to work on, particularly as we move into worker environments.  But, back to the immediate concern about the [`apollo` CLI](https://www.npmjs.com/package/apollo), since this package will be utilized by the `apollo` CLI, we'll be shaving additional precious download time off the invocation of `npx apollo` if we can get this down.

We'll still depend on `@types/lodash` for _just_ the `ListIteratee` type (since the modular packages don't provide the `lodash/common` types) and we should be able to trim 55.4kB minified (19.1kB minified+gzip'd) off the `apollo-server` build.

cc @trevor-scheer @jbaxleyiii @martijnwalraven

### CODE REVIEW

**Comment by glasser** [comment]
Moving this out of the reporting package sounds like a great idea.

A few thoughts:
- This is a backwards-incompatible change to apollo-engine-reporting due to the lack of exports. I think you understand this (the major version bump, etc) but I'd be curious to know if we had any knowledge of people actually using the exports to pass a custom `calculateSignature` in.
- Looks like the documentation of `calculateSignature` in apollo-server.md could at least a tiny update to reference the new package.
- What if the new package's name was more specific? `apollo-graphql` is pretty vague (it's basically our company's name!)  How about something more like `apollo-graphql-query-format` or `apollo-graphql-query-normalize`?  Note that my personal instinct is to try to eventually move our company towards a world where "signature" is literally just a well-defined lossless whitespace and sort order normalization.

**Comment by abernix** [comment]
@glasser Apologize for the brevity; I'm on my way out:

> This is a backwards-incompatible change to apollo-engine-reporting due to the lack of exports. I think you understand this (the major version bump, etc) but I'd be curious to know if we had any knowledge of people actually using the exports to pass a custom calculateSignature in.

No knowledge of it in the wild, but the major version has already been bumped (maybe while you were writing your review) in https://github.com/apollographql/apollo-server/pull/2259/commits/8d5e731a45635dfd64d6d9eb3d13e83e148364ce and change log updated in https://github.com/apollographql/apollo-server/pull/2259/commits/ceabd8179e55ae871900bfab0bc5918f59ee2d7b (and now 9eca8213459e7475b5f3edb054ed2e6fd5095059 after rebasing to fix linting failures)

> Looks like the documentation of calculateSignature in apollo-server.md could at least a tiny update to reference the new package.

Thanks! Done via e84aca256c76379e4d2ccecf86827671f2f601a2.

> What if the new package's name was more specific? apollo-graphql is pretty vague (it's basically our company's name!) 

Yes, I know. 😄  This is a new utility package, not just a package for signatures.

> Note that my personal instinct is to try to eventually move our company towards a world where "signature" is literally just a well-defined lossless whitespace and sort order normalization.

Agree!  We're hoping that this is simple enough that it can live in the `apollo-graphql` utility package and not require yet another package until proven necessary.  So far this is already a big improvement, I think.

**Comment by glasser** [comment]
I dunno, I kinda feel like "grab-bag loosely coupled utility package" is kinda an anti-pattern...  Y'know, like `graphql-tools` that we kinda regret already.
And that "a package name that literally is our company name" might want to be saved for something more important than that :)

Can we make it at least a little tighter?  Like, "grab-bag of utilities relating to parsed GraphQL queries" seems a lot more coherent as a concept. `apollo-graphql-ast-utilities` or `apollo-graphql-query-manipulation` or something...

**Comment by abernix** [comment]
@glasser Without understanding the details of what we're planning to put in this package right now, I think it's unfair for you to accuse me of building a "grab-bag loosely coupled utility" package.  I've never suggested anything in this package will be grab-baggy and I don't think there's enough of an outline or context here to form the conclusion that it's going to be loosely coupled.

Furthermore, you seem to be implying that you're aware of my feelings about `graphql-tools` or that my feelings are the same as yours.  I personally believe that `graphql-tools` may no longer be the easiest way to build a GraphQL server but I've never regretted anything about its components or the coupling of those components together into a package that facilitates GraphQL server development.  That's fine if you feel that way, but I think you could be a bit more sensitive about publicly claiming regret when [you don't](https://github.com/apollographql/graphql-tools/graphs/contributors) appear in the contributor list for that package.

I'm not opposed to making yet another package to house this logic and I'm happy to consider another name if that ultimately makes sense, but I'd rather we do this as a dialog where you ask questions about the intended direction of the package rather than making assumptions.

In regards to signatures, I share the same hope as you that they will eventually become a well-defined lossless normalization, but I'm also hopeful that something like that will eventually be available from `graphql-js`.

Nothing is set in stone here as we're free to change the contents of this `apollo-graphql` package at any time.  I think if enough demand is created where we feel like this could stand well on its own then we can break it out into its own package and maintain backwards compatibility from `apollo-grahpql` by relying on the new package and not breaking would-be consumers of a "operation formatting" package.  On the other hand, if we create the extra package today and later decide it's not worth the maintenance burden of a separate package, I believe deprecating the additional package creates more work for the consumers since they'll be forced to move to a new package which provides the dependency.  That said, I still believe the primary consumer of signature logic will be our own tooling, so I'm basically claiming that we need more closely-coupled formatting logic before we bring on another formatting package which isn't zero-cost.

**Comment by abernix** [comment]
Concretely, once published and consumed this solves an undesired dependency on `apollo-server-core` by the `apollo` CLI.  As it stands right now though, those signature algorithms also need to be used by both the `apollo-tooling` repository (which houses the `apollo` CLI) and (this) `apollo-server` repository (which houses `apollo-engine-reporting`).

We can explore moving formatting functions into another package if it makes sense but there are more concrete plans (which, admittedly, are yet to be fully publicized and finalized) for this package aside from it being a home for signature algorithms, which is certainly not its sole purpose.

**Pull request merged**
