### PR TITLE
Add config hook for federation introspection query

### PR DESCRIPTION
**Pull request by JacksonKearl**
Re #2891.

### CODE REVIEW

**Comment by ElliotChong** [comment]
I just ran into this issue today (my service requires a particular header), FWIW it would be nice to be able to manipulate headers on a per-service basis rather than just globally.

**Comment by glasser** [comment]
My instinct is that there could be two layers here:

- By default, we can turn a service list into definitions by using the exact same `GraphQLDataSource` (or whatever it's renamed to), and perhaps just passing `context: null` to indicate "there's no user context, it's the internal service fetch". I don't think there needs to be two different configuration points for "how do I do a GraphQL call to a backend over HTTP" — one is enough.
- Additionally, if you *don't* want to fetch the definition by a GraphQL call over HTTP, there's a more rarely used hook you can use to replace that.  But you don't need this for the common case of "tweaking the HTTP connection in the same way for all GraphQL requests to the backend service"

**Comment by jbaxleyiii** [comment]
@glasser the `request` portion of that API would also be undefined or null. I'm good with this direction though cc @JacksonKearl! This should make people pretty dang happy!

**Comment by glasser** [comment]
No, the `request` would be describing the `_service { sdl }` query, right?

Anyway this PR does seem fine but I'm sure it doesn't close the door on customization.

**Comment by thinkjson** [comment]
When is this expected to be included in a release?

**Comment by abernix** [comment]
@thinkjson 	Have you checked the versions listed in this publish commit: 2ea5887acc43461a5539071f4981a5f70e0d0652

**Comment by flosch-hb** [comment]
Hej guys, I am not entirely sure of what the API looks like, but just a question: would this allow to use different headers for different services?
(E.g. if different services require different `Authorization` headers?)

**Comment by alex-hioperator** [comment]
Hi Everyone! Just wanted to check if a solution got pushed out? I'm running into a wall where I need to pass unique tokens for each of my underlying apollo server endpoints, and I need to do this for the introspection phase.

**Pull request merged**
