### PR TITLE
[WIP] uWebSockets Integration

### LINKED ISSUE #2353: Integration with uWebSockets.js
uWebSockets.js looks like an extremely promising HTTP server alternative that provides both an incredibly fast native `http` module replacement and nice JS interface. `apollo-server-uwebsockets` anyone? 

GitHub: https://github.com/uNetworking/uWebSockets.js
Introduction: https://levelup.gitconnected.com/will-node-js-forever-be-the-sluggish-golang-f632130e5c7a

### PR DESCRIPTION
**Pull request by timkendall**
This is the beginnings of a new integration with [uWebSockets.js](https://github.com/uNetworking/uWebSockets.js), a spicy new super-fast native HTTP framework replacement for Node. 

I've gotten the basic functionality working but a few things still need to be tackled (and some things may be blocked by uWebSockets right now).

TODO
* [ ] Support file uploads
* [ ] Support subscriptions
* [ ] Fix janky tests that require a random free port to be chosen (may be an issue with something I'm doing but I couldn't seem to get it to cleanly give up the port even following their [GracefulShutdown example](https://github.com/uNetworking/uWebSockets.js/blob/master/examples/GracefulShutdown.js))
* [ ] Add support for fully constructing `Request` objects before passing to `runHttpQuery` (see https://github.com/uNetworking/uWebSockets.js/issues/70)
* [ ] Solidify what we want to pass to `createGraphQLServerOptions` (have to be very careful with the `req`/`res` objects given to us by uWebSockets so we may want to pass "fake" versions of them with basic data copied out)
* [ ] Fix a handful of failing tests

Apollo TODO:
* [ ] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [ ] Make sure all of the significant new logic is covered by tests
* [ ] Rebase your changes on master so that they can be merged easily
* [ ] Make sure all tests and linter rules pass

Closes #2353

### CODE REVIEW

**Comment by orefalo** [comment]
Neat! exactly what I was trying to build

**Comment by timkendall** [comment]
@orefalo ha I saw your issue in uWebSockets and thought so :) Would love your help on this if you have time.

**Comment by alexhultman** [comment]
@timkendall Hello, could you please explain more about the graceful shutdown issue?

**Comment by timkendall** [comment]
Hey @alexhultman , yeah to elaborate I was seeing `app.listen` fail to return a listen `token` when attempting to startup the server before each test https://github.com/apollographql/apollo-server/blob/5cb46e52eefb8698012dbdfb9c4044eac0dde711/packages/apollo-server-uwebsockets/src/__tests__/uWebSocketsApollo.test.ts#L56

When I switched to using random free ports (like I'm using right now) the problem went away (i.e got that listen token successfully).

Again, could just be something that I'm doing wrong ;)

**Comment by mattiasewers** [comment]
@timkendall What kind of speeds do you get with a simple hello world query?

**Comment by timkendall** [comment]
Looks like `uWebSockets.js` `v15.6.0` has support for getting all headers from a request. Will be adding this.

 https://github.com/uNetworking/uWebSockets.js/releases/tag/v15.6.0

**Comment by orefalo** [comment]
> @timkendall What kind of speeds do you get with a simple hello world query? Tested your code on a hello world query on osx and got 8.5K req/sec.

I didn't benchmark with apollo yet. But the core library is close to 50% faster than bare metal node.
https://github.com/orefalo/turbo-http/tree/master/benchmarks
```
┌──────────────────────────┬────────────┬─────────┬───────────────┐
│                          │ Requests/s │ Latency │ Throughput/Mb │
├──────────────────────────┼────────────┼─────────┼───────────────┤
│ uws.js                   │ 75211.2    │ 6.95    │ 5.38          │
├──────────────────────────┼────────────┼─────────┼───────────────┤
│ turbo-http.js            │ 64627.2    │ 7.63    │ 4.87          │
├──────────────────────────┼────────────┼─────────┼───────────────┤
│ bare-node.js             │ 50165.6    │ 9.77    │ 5.55          │
├──────────────────────────┼────────────┼─────────┼───────────────┤
│ polka.js                 │ 49209.46   │ 9.94    │ 5.44          │
├──────────────────────────┼────────────┼─────────┼───────────────┤
│ rayo.js                  │ 48861.82   │ 10.02   │ 5.41          │
├──────────────────────────┼────────────┼─────────┼───────────────┤
│ fastify.js               │ 43109.6    │ 11.23   │ 6.45          │
├──────────────────────────┼────────────┼─────────┼───────────────┤
│ express.js               │ 40096.37   │ 12.11   │ 4.44          │
├──────────────────────────┼────────────┼─────────┼───────────────┤
│ hapi.js                  │ 19007.6    │ 25.04   │ 2.83          │
```

 It behaves particularly well under heavy load.

**Comment by orefalo** [comment]
@mattiasewers  could you share your benchmark code, tks

**Comment by mattiasewers** [comment]
@orefalo This is no longer an issue with `res.experimental_cork`

**Comment by dalisoft** [comment]
@timkendall Can we help? It would be great to implement uWebSockets.js with Apollo Server with subscriptions support

**Comment by dalisoft** [comment]
@mattiasewers From single request simulator or single client difference will be 20-30%, but when real-world app with 100K sim. connection, then you can see difference, especially with cost. I have graphql server without subscription and difference with cost is 50% (from 15$ to 8$), when i can implement subscription, cost will be dropped to 4.5-5$ (for 10-20K connections).

_These numbers may not work for you, the cost of server may differs from server configuration, caching and etc_

**Comment by hayes** [comment]
I've been looking at how to integrate apollo with uWebsocket.js, was there a technical reason this stalled out?

**Comment by timkendall** [comment]
@hayes not really, just got busy (upload support may be a little involved but we don't need to do that right away :)

**Comment by hayes** [comment]
I looked a bit at what it would take to get subscription support (my use case) and that looks a bit more involved.  There are a lot assumptions around having nodes request/connection objects in the ws transport package.  

I'm not sure if I'll have the time to figure out how to make that compatible.

**Comment by orefalo** [comment]
"I've been looking at how to integrate Apollo with uWebsocket.js, was there a technical reason this stalled out?"

I personally dropped uWS, the author is way too arrogant and egocentric... rude would be a more appropriate term.

**Comment by hayes** [comment]
That's discouraging to hear.  It may not be worth it in this case.  Mostly just exploring options at this point

**Comment by alexhultman** [comment]
@orefalo I checked our email conversation and I find nothing but polite conversation from both ends. You stopped emailing me when I told you my hourly rate.

Of course, you interpreted my disapproval of your idea as "rude". If you want to hire someone only to **confirm your original idea**, without any **critical thinking**, then hire an actor or diplomat. You can't expect everyone to agree with your direction just because you wave a couple of dollar bills around.

That's called confirmation bias - you look for someone to agree with your idea rather than look for objective input to challenge your idea until the idea is either right or wrong, proven by evidence.

Alright, take care.

**Comment by maxpain** [comment]
Any update on this?

**Comment by orefalo** [comment]
it's dead - if you want speed and scalability, switch to go and rust. you will get both without the arrogance. cheers

**Comment by alexhultman** [comment]
> the arrogance

Ah yes because a middle aged Rolex wearing narcissistic "I model, therefore I am" kind of man who cannot take a "no" is never at fault.

You are mad because I turned down your idea and had a too high rate, and now you act like a 5-year-old who won't get the newest Transformers toy for Christmas.

If I remember correctly you acted like an inflated overly proud alpha cat with stiff tail pointing straight up and thought you could just come and throw (way too little) money at me and have me automatically agree with anything.

**Comment by orefalo** [comment]
Good,
You are starting to show your real self again Alex:rudeness is popping again in your jargon. But this time around you won't be able to delete the thread, right?
I believe you have a real personalty disorder... plus memory issues. it's laughable: you are pissing off so many people you can't even remember which is which.
Go reply with your insults...

**Comment by alexhultman** [comment]
Relations require chemistry and it's clear that we both dislike each other so let's just leave it at that. We don't need to be friends.

**Comment by maxpain** [comment]
I've done integration [here](https://github.com/enisdenjo/graphql-ws/pull/89)

**Pull request closed without merging**
