### PR TITLE
Docs - More clearly point to special web client case

### PR DESCRIPTION
**Pull request by nataliaschlebinger**
Would solve [this issue](https://github.com/apollographql/apollo-client/issues/9904). I only mention the React case, since the other clients appear to infer this.

### CODE REVIEW

**Comment by trevor-scheer** [comment]
Can you point me to where it's documented or in code that the non-react clients infer this? I'm not sure how that would be the case, but I'm less familiar with the other projects.

Otherwise, LGTM! Thanks for the PR. I'll wait to hear from you so you can adjust accordingly or show me where that's actually the case.

**Comment by nataliaschlebinger** [comment]
From what I gather, they generate and expose accessors for the properties requested `on` the interfaces, following along with the author of the queries. These generated names will hold a null value if no object of matching type is returned. What I called "inference" is the clients learning about that relationship from the queries instead of it being explicitly stated.

Following along the "Droid on Hero" and "Human on Hero" examples:

[For the Kotlin client:](https://www.apollographql.com/docs/kotlin/essentials/fragments#inline-fragments)

> For this operation, Apollo Kotlin generates a `Hero` class that contains `OnDroid` and `OnHuman` nested classes. `Hero` also includes `onDroid` and `onHuman` fields that enable you to access fields that are specific to `Droid` and `Human`
> These `on<ShapeName>` fields (`onDroid` and `onHuman`) are `null` if the returned object is not the corresponding type.

[And for the Swift client:](https://www.apollographql.com/docs/ios/fetching/fragments#inline-fragments)
> You can use inline fragments with type conditions to query for type-specific fields
> And results from inline fragments with type conditions will be made available through specially generated `as<Type>` properties
Also here's [context for that type conditions biz](https://www.apollographql.com/docs/ios/fetching/type-conditions/#accessing-conditional-response-data), I was not familiar with it in particular:
> Using a fragment on another type creates a type condition in the generated model objects.
> In order to access the `primaryFunction` on the `Hero` model, we need to know if the hero is a droid. Apollo iOS will generate a `Hero` model with an optional `asDroid` property

BTW thanks for the response! Let me know what you think!

**Comment by trevor-scheer** [comment]
Ah! I gathered "React vs. other web frameworks (i.e. Vue, Angular, etc.)" rather than our other first-party mobile clients. Let's just call it "web client". Apollo Client (web)'s core functionality / API is agnostic to the web framework it's used in, even though we only maintain a React integration ourselves. So just "React" -> "web" and I'll land this PR. Thanks!

**Comment by nataliaschlebinger** [comment]
Ahh, awesome!! That makes sense, there's the change!

**Review by trevor-scheer — APPROVED** [review]
Thanks!

**Pull request merged**
