### PR TITLE
Fixes #3131. Adds HEAD method helper to RESTDataSource.

### LINKED ISSUE #3131: add HEAD requests in `datasource-rest`
Some endpoints of my REST API can be requested via a HEAD request but head is not implemented yet.

```
export class MyFancyAPI extends RESTDataSource {
    async countFancyDataset() {
        const response = await this.head(`countFancyDataset`); // myFancyDataset: 413212  (in Response Header)
        ...
    }
}
```

### PR DESCRIPTION
**Pull request by Phoenix1405**
Fix for https://github.com/apollographql/datasource-rest/issues/27. Adds the HEAD http method helper function to RESTDataSource. Added a test for this method (it should not return a response body).

### CODE REVIEW

**Review by abernix — CHANGES_REQUESTED** [review]
Thanks for opening this PR.  This looks pretty good to me, my comments / _requested changes_ don't relate to changes in the code.

Just to quote my comment on the issue that this closes, which aims to question the original omission of `HEAD` support (https://github.com/apollographql/apollo-server/issues/3131#issuecomment-728829672):

> I don't have the precise answer as to the exact "why", but I could certainly believe that the omission of `HEAD` from the original implementation was because it wasn't fully realized that there was much in the way of **data** to be retrieved from such an endpoint (that doesn't return a body).
>
> That said, data obviously comes in various forms and it's entirely possible to return certain valuable data as header values, so I think the need resonates with me

My requested changes are:

* The documentation ([seen here on the web](https://www.apollographql.com/docs/apollo-server/data/data-sources/#http-methods), but located in [`/docs/source/data/data-sources.md`](https://github.com/apollographql/apollo-server/blob/main/docs/source/data/data-sources.md) within the repository) should be updated as well to reflect the availability of `head`. 
* A `CHANGELOG.md` entry should be added.  Do you want to try writing a `CHANGELOG.md` for this and adding it to this branch as well, or would you like me to take care of that?

  I might suggest something like:

  > `apollo-datasource-rest`: Introduced support for the HTTP `HEAD` method by exposing a `head` method on the base `RESTDataSource` class.  This works similarly to the `get` method, but for `HEAD` requests which do not return "body" content.  Rather than exposing data that can be retrieved from the body, `HEAD` requests typically expose data in their HTTP response headers (e.g., numbers, shorter strings, identifiers, [`ETag`s](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag), etc.). [Issue #3131](https://github.com/apollographql/apollo-server/issues/3131) [PR #4739](https://github.com/apollographql/apollo-server/pull/4739).

**Comment by Phoenix1405** [comment]
@abernix Thanks for the feedback. Do I add the CHANGELOG.md entry in the package? or in the root folder? or both?

**Comment by Phoenix1405** [comment]
@abernix Actually, do you mind doing the CHANGELOG.md change? I figure it'll be faster for you to do it since I'm not familiar with the process. I've updated the other docs as requested.

**Comment by Phoenix1405** [comment]
Thanks @abernix. Anything left?

**Comment by trevor-scheer** [comment]
Hey @Phoenix1405, sorry for the delay on this. The REST datasource package has recently migrated:
https://github.com/apollographql/datasource-rest

I'll suppose that @abernix's approval of the idea means this PR is probably worth entertaining. If you'd like to reopen this PR against the new repo I'd be happy to evaluate and review.

**Pull request closed without merging**
