### PR TITLE
[FIX] Fix fastify startup deprecation warning

### PR DESCRIPTION
**Pull request by randomnerd**
Update the `fastify` package
Use the preHandler instead beforeHandlers - Fix Issue #3477

### CODE REVIEW

**Comment by randomnerd** [comment]
Could someone please do a review? Thanks!

**Comment by randomnerd** [comment]
updated to master, approval still required

**Comment by zieglar** [comment]
any update?

**Comment by zieglar** [comment]
@martijnwalraven @abernix  please review this, need update with fastify

**Comment by pauloedurezende** [comment]
This change had already been made previously on #3527

**Comment by markrzen** [comment]
Duplicate of https://github.com/apollographql/apollo-server/pull/2391

**Comment by abernix** [comment]
Closing as duplicate of https://github.com/apollographql/apollo-server/pull/3527 and https://github.com/apollographql/apollo-server/pull/2391.  It is absolutely on my mind to get the major version bumped in the next major version of Apollo Server.  I understand the disappointing delay, in particular on the Fastify updates, but opening more of these same/similar PRs won't get the blockers unblocked for that work.  We are trying to get to a stage where this is less problematic both now, and in the future. (See also, #3184 and #3576)

**Pull request closed without merging**
