### PR TITLE
Update to Hapi 17

### LINKED ISSUE #636: Hapi v17
Upgrade hapi plugin to work with new release of Hapi https://github.com/hapijs/hapi/issues/3658

### PR DESCRIPTION
**Pull request by EgoAleSum**
Note that TypeScript typings for Hapi 17 are not available yet (see #636), so the types packages have been temporarily removed for Hapi and Boom.

Tests are passing, and linter is happy too.

This should close #636 and #685

### CODE REVIEW

**Comment by EgoAleSum** [comment]
Regarding the travis CI errors... For Node 4 and 6, it is expected that CI fails, because Hapi 17 uses async/await and requires Node 8+.

For Node 8+: on my machine, it works 3 times out of 4; the other times, I get weird behavior like in the CI case above. I am not sure what's causing it, but it's likely an issue with the tests themselves as they hang on something async. I tried looking into it, but not sure how to fix them.

**Comment by orblazer** [comment]
Hello, your exemple for register plugin on hapi is broken.

This exemple is right :
```js
await server.register(graphqlHapi, {
  path: '/graphql',
  options: {
    graphqlOptions: {
      schema: myGraphQLSchema,
    },
    route: {
      cors: true
    }
  }
});
```

Thanks for your contribution.

**Comment by EgoAleSum** [comment]
@orblazer Uhm, are you sure about that? There's no such thing as `path` in the `options` arguments for Hapi 17: https://hapijs.com/api#plugins

**Comment by EgoAleSum** [comment]
Ok, I finally figured it out! The issues were with the Adonis test unit. It took many hours of literally going through the Adonis' source code, but some methods that were supposed to be async were called synchronously.

After I made the tests async (to support Hapi, which is all async), issues with Adonis came out. I'm not sure why it was fine before, but essentially there were situations where the Adonis server was not started or closed properly. It should be all good now.

I've also made sure that the Hapi package is tested only on Node 8.9+ (minimum version for Hapi 17).

All tests pass now, yay!

**Comment by martijnwalraven** [comment]
Thanks a lot for working on this!

**Comment by orblazer** [comment]
@EgoAleSum Yes i am sure, with your exemple the hapi crash.

**Comment by EgoAleSum** [comment]
@martijnwalraven thanks for merging this, do you have any timeline for the next release? (note the change is not backwards-compatible as you can imagine :) )

**Comment by martijnwalraven** [comment]
@EgoAleSum Yes, we should probably release these changes as 1.3.0. I was hoping we could get https://github.com/apollographql/apollo-server/pull/679 in as well, but if that takes too long we should release without it.

**Comment by martijnwalraven** [comment]
Published as 1.3.0, thanks!

**Pull request merged**
