### PR TITLE
Fix Typescript import error: TS1192 module has no default export

### PR DESCRIPTION
**Pull request by Arthie**
I get the following error when using the apollo-server-core with typescript (3.2.4) :

```
node_modules/apollo-server-core/dist/types.d.ts:4:8 - error TS1192: Module '"/node_modules/@types/ws/index"' has no default export.
import WebSocket from 'ws';
```

The change fixes this error!

TODO:

* [ ] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [X] Make sure all of the significant new logic is covered by tests
* [X] Rebase your changes on master so that they can be merged easily
* [X] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by abernix** [comment]
@Arthie I do believe we need to provide a fix here, but can you provide a use-case/code-snippet showing exactly how you're encountering this type error, in usage of `apollo-server-*`, for posterity's sake?  Are you using something from `apollo-server-core`?

**Comment by Arthie** [comment]
@abernix 

Just adding this line to a file is enough to trigger the error:
`import { ApolloServer } from "apollo-server-lambda";`

Here is my typescript config:
```
{
  "compilerOptions": {
    "lib": ["es2017", "esnext.asynciterable"],
    "moduleResolution": "node",
    "noEmit": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "allowUnreachableCode": false,
    "strict": true,
    "sourceMap": true,
    "target": "es2017",
    "outDir": "dist",
    "baseUrl": "src",
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/*.graphql"]
}
```

I also get a secondary error similar to the first one but in apollo-server-lambda:
```
node_modules/apollo-server-lambda/dist/ApolloServer.d.ts:1:8 - error TS1192: Module '".../node_modules/@types/aws-lambda/index"' has no default export.

1 import lambda from 'aws-lambda';
```

**Comment by Arthie** [comment]
@abernix Added a new commit to fix the secondary import error. The `aws-lamda` types package also has no default export.

Summery of this tiny patch:
Fixes 2 import errors: `error TS1192: module ... has no default export`
from package `ws` in `apollo-server-core` and `aws-lambda` in `apollo-server-lambda`

**Comment by abernix** [comment]
This has been included in 2.4.3.  I plan on promoting it to the `latest` tag tomorrow, but you can try this right now using the `next` tag or by directly installing 2.4.3.  e.g.:

    npm install apollo-server-lambda@2.4.3

**Comment by Arthie** [comment]
Tested version apollo-server-lambda@2.4.3 and got no errors! Thank you 👍

**Comment by abernix** [comment]
Thank you for this first contribution!

**Pull request merged**
