### PR TITLE
chore: fix npm constraints for Renovate

### PR DESCRIPTION
**Pull request by rarkins**
The existing `force` statement is not necessary now and actually causes a problem by overriding the existing detected `constraints` in `package.json`. This results in `npm@latest` being installed.

### CODE REVIEW

**Comment by glasser** [comment]
Thanks @rarkins. Just to confirm: @abernix added this only a few months ago in https://github.com/apollographql/apollo-server/commit/88ec8f1a12b732b9b900d76751a22be66068bffd as part of https://github.com/apollographql/apollo-server/pull/4775 where we explicitly did not want an npm@7 upgrade. Are you saying that Renovate's behavior about this has changed since December? I'm also unsure if when you say "This results in npm@latest being installed" you mean before or after your PR.

**Comment by rarkins** [comment]
> Are you saying that Renovate's behavior about this has changed since December?

Yes, but more importantly the key chanage is that npm defaulted to installing npm@7 instead of npm@6

> I'm also unsure if when you say "This results in npm@latest being installed" you mean before or after your PR.

It means that your current `force` config is *causing* the problem. You could solve it by adding an npm constraint to `force`, but it's entirely unnecessary to have a `force` config so that's a better solution.

**Comment by glasser** [comment]
@rarkins Just to be clear, is "the problem" that npm@7 *is* being used (when we don't want it) or that it's being prevented from being used (where you might expect us to want it)?

**Comment by glasser** [comment]
I think what you're saying is that our force config is redundant with a *subset* of our `engines` config but also overrides the other part, so the npm part of our engines config isn't taking effect and we are surprisingly getting npm@7, and merging this will keep us on npm@6 as desired, right?

**Comment by rarkins** [comment]
Yes

**Review by glasser — APPROVED** [review]

**Comment by glasser** [comment]
Got it! Thanks for checking in on us.

**Comment by glasser** [comment]
Ah, I finally noticed that this issue was referenced from https://github.com/renovatebot/renovate/issues/9036 :)

**Pull request merged**
