### PR TITLE
Rename packages from graphql-server- to apollo-server-

### PR DESCRIPTION
**Pull request by martijnwalraven**

### CODE REVIEW

**Comment by DxCx** [comment]
Oh?
the packages where originally called `apollo-server-*` and there was a decision to rename to `graphql-server-*`
can you explain?

CC @stubailo @helfer

**Comment by helfer** [comment]
@DxCx I don't know and I'm curious to know the answer myself.

**Comment by stubailo** [comment]
Hi @DxCx @helfer - we were trying to move quickly so that we could get @helfer's 1.0 announcement out there, I think in the future it will be better to wait a bit to get more feedback.

I think originally one of the reasons for the rename from Apollo Server was that we didn't want people to think that it only worked with Apollo Client, and the name reinforced that it's a generic GraphQL server.

Today, it doesn't seem like that association is a big problem anymore, and it looks like the name is not completely sticking - a lot of people we talk to these days are using graphql-server but refer to it as "Apollo Server". One nice thing is that people are very excited about the Apollo association - they understand that the two technologies are decoupled, but enjoy the fact that they can use them together and be sure that they are compatible.

When we were thinking about the naming long term, it seemed bad to have a package which is officially named one thing, but is always colloquially called something else, since that might make it harder to find and talk about.

The strategy we decided on is intended to minimize negative impact to stuff like download counts and SEO. Let's talk about it during contributor weekly if you can come. We're thinking it will be good to publish both sets of packages in parallel for a bit while people have time to get used to the new name, and then add a deprecation warning to the `graphql-server-*` packages in a few weeks. In the meanwhile we can try to track down some of the most important tutorials and examples and get them to switch.

**Comment by helfer** [comment]
Makes sense, thanks for clarifying!

**Pull request merged**
