### PR TITLE
Fix file upload bug with apollo-server-koa (#2843)

### PR DESCRIPTION
**Pull request by owencalvin**
This pull request is related to the issue: #2843

### CODE REVIEW

**Comment by Nerzull3** [comment]
LGTM

**Comment by OwenCalvin** [comment]
So some news about this PR ?

**Review by vanyadymousky — COMMENTED** [review]
LGTM

**Comment by glasser** [comment]
Direct integration with `graphql-upload` was removed from Apollo Server in v3 last year.

**Pull request closed without merging**
