### PR TITLE
apollo-gateway export types

### PR DESCRIPTION
**Pull request by wareczek**

### CODE REVIEW

**Comment by wareczek** [comment]
Hi @trevor-scheer, please make it happen :)

**Comment by trevor-scheer** [comment]
Hey @wareczek, thank you for submitting a PR! I'm not opposed to exporting these types, but as these functions are still experimental, I'm erring on the side of not (for now).

My primary justification for this is that TS can infer these types automatically for typical use cases. If you (or any other 👍'ers) would like to demonstrate a case where these types are needed, I'll consider the addition!

**Comment by wareczek** [comment]
So be consequent. Callback `experimental_didUpdateComposition` has exported type `DidUpdateCompositionCallback` :P

https://github.com/apollographql/apollo-server/blob/master/packages/apollo-gateway/src/index.ts#L119

**Comment by abernix** [comment]
One of the side-effects of a strongly-typed language is that the corresponding auto-completion results in users using features which they (often, in my experience) don't realize are experimental or subject to change.

It's entirely possible that the prefix of the method name itself will make that clear, but I'm curious if it would hurt/help to also prefix the types with a similar prefix (e.g. `Experimental_`).  So I ponder: Is that an okay pattern to use here?  (I think so.)  Common pattern? (Not sure!) Bad pattern? (I don't think so.)

Thoughts, anyone?

(Not saying we'll need to exercise this, but luckily, since TypeScript uses structural typing, even if a type is renamed later on it will still work just fine by implementors of the previous type, so long as the shape remains the same.)

**Comment by abernix** [comment]
Hmm, test failures do not seem to be spurious, but do not seem to be related to this PR? 🤔

**Comment by trevor-scheer** [comment]
@wareczek, let's go ahead and export these types with the `Experimental_` prefix rename to the related types (including the types that are already exported, as you've pointed out).

So I'm not ambiguous, I'll list them:
- [ ] `DidResolveQueryPlanCallback`
- [ ] `DidFailCompositionCallback`
- [ ] `DidUpdateCompositionCallback`
- [ ] `UpdateServiceDefinitions`
- [ ] `CompositionInfo`

If you don't mind adding those prefixes, I'd be happy to merge this! Also a [changelog](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-gateway/CHANGELOG.md) entry would be greatly appreciated 😄

**Comment by trevor-scheer** [comment]
> Hmm, test failures do not seem to be spurious, but do not seem to be related to this PR? 🤔
@abernix a re-run did pass the failing Node6 tests for me, so I'll chalk it up to spurious unless you saw something I didn't.

**Comment by trevor-scheer** [comment]
Thank you @wareczek! 🎉

**Pull request merged**
