### PR TITLE
Fix security vulnerabilities in documentation

### PR DESCRIPTION
**Pull request by ebickle**
The Apollo Server data source documentation has sample code snippits that contain security vulnerabilities:
- Web Parameter Tampering (https://www.owasp.org/index.php/Web_Parameter_Tampering)
- A limited form of Server Side Request Forgery / SSRF (https://www.owasp.org/index.php/Server_Side_Request_Forgery)

In the samples, raw query input is used to concatenate URLs used to invoke backend REST APIs. If an attacker passes input that contains URL control characters they can modify the URL being accessed in a way the GraphQL Server does not expect, potentially gaining access to sensitive information or functionality.

I've modified the documentation to properly encode the URL parameters to properly neutralize the input. Nearly all of the projects based on Apollo Server that I've reviewed contain these vulnerabilities due to developers copying & pasting the patterns from the official documentation.

### CODE REVIEW

**Comment by ebickle** [comment]
I've signed the Apollo Contributor License Agreement. Build failed, but looking at the logs for netlify shows errors that seem unrelated to this change. Any ideas?

**Comment by ebickle** [comment]
Pull request is obsolete due to documentation filenames being renamed. A new PR will be issued.

**Comment by glasser** [comment]
Wow, sorry that this got overlooked. I'll definitely take a look at the new PR!

**Comment by ebickle** [comment]
@glasser No worries at all! 

I've tossed a new PR over at https://github.com/apollographql/apollo-server/pull/5681 (checks pending as I write this). To be clear, this isn't a security vulnerability in Apollo itself - just the sample code. I've seen a few developers copying & pasting those examples and ending up with some issues in their production code as a result 😀 The PR reduces adds a slight bit of complexity to the documentation examples but most developers should be able to immediately understand what it's doing.

**Pull request closed without merging**
