### PR TITLE
expose TypeScript types for apollo-server-testing client

### PR DESCRIPTION
**Pull request by schmod**
This is a small Pull Request to expose a TypeScript type for the test clients that can be created with the `apollo-server-testing` client.

### CODE REVIEW

**Comment by schmod** [comment]
I'm going to need to run this CLA by some folks.  

Would the Apollo folks mind adding this to the documentation?  This is one of the stronger CLAs that I've seen, and it's a little awkward being blindsided by it _after_ submitting a Pull Request, as there are definitely folks who aren't going to be able to sign it.

**Comment by schmod** [comment]
CLA signed!

**Comment by abernix** [comment]
Sorry for the blindside!  As it notes at the bottom of [the agreement](https://contribute.meteor.com) (which I know you couldn't have known about ahead of time!), our CLA is derived from the Apache Software Foundation's Individual Contributor License Agreement V2.0.  The specific deviations from the original are also itemized there.

That said, I've added a note to the `CONTRIBUTING.md` in https://github.com/apollographql/apollo-server/commit/d767397b59a8403e4e460ea69c844b38a791e233 to make it more clear that the CLA requirement exists.  Thanks for pointing that out! :)

**Comment by schmod** [comment]
@abernix Thanks!!! I appreciate the update!

**Pull request merged**
