### PR TITLE
docs: Remove Zeit Now v1 deployment guide

### LINKED ISSUE #3617: Deploying to zeit now
Hi,

after reviweing your tutorial and wanted to deploy apollo server (express) with zeit now I found that your part of docs are outdated.

https://www.apollographql.com/docs/apollo-server/deployment/now/

Actually as far as I know, zeit now looks for build not start.

Could you please update documentation accordingly that you will be able to deploy apollo-server to zeit now?

Kinds,
Nik

### PR DESCRIPTION
**Pull request by mcsdevv**
This PR removes ZEIT Now as a deployment option. This is because it refers to the Now 1.0 platform which is no longer open to new users. In the future, it is possible that a further PR will be made, showing how to use `apollo-server-lambda` with Now 2.0.

Fixes #3617

### CODE REVIEW

**Comment by trevor-scheer** [comment]
@msweeneydev is this information still relevant to existing users?

I'd like to avoid creating a dead link if possible. At the very least, I'd like to keep this page in existence with a note saying that the previous 1.0 workflow is deprecated - possibly with a link to some docs that would be helpful for them to get started with 2.0?

In a better case (if these docs are still relevant for existing users), we keep the page as is with a note at the top saying that existing users can still use this workflow but that new users must move on to a Now 2.0 workflow.

**Comment by msweeneydev** [comment]
Hello @trevor-scheer, this information is relevant only to a small portion of the ZEIT Now userbase and not for any users joining the platform, however, it does cause significant confusion, see [this thread](https://spectrum.chat/zeit/general/cant-deploy-graphql-to-zeit-now~d23e962a-7788-4c14-86da-c27bdb7c7d0e) as an example.

Whilst it is technically possible to run a GraphQL server within a single Serverless Function, it is not currently recommended as there are limitations, for example, the usage of subscriptions is not possible.

**Comment by mcsdevv** [comment]
@trevor-scheer Now 1.0 has now been limited to existing deployments only. It is no longer possible for users to follow the steps listed here. Therefore, is it possible to remove this page?

**Comment by trevor-scheer** [comment]
Thanks for the ping @mcsdevv, can you take a look at this PR and see if it's a preferable update in favor of deleting this page? I'm not sure if just a rename is appropriate but I figure you might as a Vercel team member.

If the content is good we can recommend an url change to vercel and add a redirect from now -> vercel for anyone holding on to an old link.

**Comment by mcsdevv** [comment]
Hey @trevor-scheer, it's definitely a case of removal rather than content change. The Now 1.0 platform cannot be deployed to anymore and as such, the content no longer applies.

**Comment by trevor-scheer** [comment]
@mcsdevv 🤦 I really didn't link the PR: #4016. If this is an undesirable change then I'll land your PR to remove Now altogether. Though we'd love another guide to take its place for Vercel!

**Comment by mcsdevv** [comment]
Hey @trevor-scheer - your previous message makes more sense now!

For now, removal is certainly the preferable action. If a better solution for both sides appears in the future then we'll be lining up to get something added.

**Comment by mcsdevv** [comment]
@trevor-scheer can we get this merged please?

**Comment by mcsdevv** [comment]
For reference on why this is important: https://twitter.com/amacarthur/status/1271287739627929601?s=21

**Comment by apuyou** [comment]
I managed to run Apollo Server on Now 2.0 using apollo-server-micro, which has the same API as the new Vercel platform. I wrote about it here: https://apuyou.io/blog/serverless-graphql-apollo-server-nextjs

Would you accept a PR with these instructions? I would be happy to contribute if that is of interest.

**Pull request merged**
