### PR TITLE
Upgrade graphql-subscriptions

### PR DESCRIPTION
**Pull request by davedash**
This allows Apollo Server Express to be used with GraphQL ^15.0.0

I believe I followed the contribution guidelines.  I ran the tests and couldn't see any errors.  Please let me know if there's anything else I can do.  I'm new to the `npm` eco-system.

I'm fine maintaining my fork, but ideally I'd like to track with the `main` of this project.  

Thanks.

### CODE REVIEW

**Comment by glasser** [comment]
Hmm.

- The only thing any package in this repo does with `graphql-subscriptions` is import all symbols from it and immediately re-export them. So if the symbols you're getting from apollo-server-express are from too old a version of the package, you can just install `graphql-subscriptions@1.1.0` yourself and import from there. (Apollo Server 3 is very likely to drop this automatic re-export "feature".)
- This is just a minimum version, so technically you can play some games with npm where you get your package-lock to lock in 1.1.0 anyway.  Install `graphql-subscriptions@1.1.0` in your app and run `npm dedup` or something. But those games aren't actually very fun.
- On the other hand 1.1.0 is very very old so I doubt there will be much harm from this change. And if somebody else really needs to rely on 1.0.0 they can install it themselves and use it directly.
- This PR doesn't really explain what the problem you're seeing trying to use AS with graphql-js is.  Are you saying that you literally can't install `apollo-server-express` and `graphql@15` at the same time, even if you're not using this graphql-subscriptions re-export feature?  I'm definitely more likely to merge this if I can reproduce the problem, apply your patch, and see that the problem goes away!
- A few of the other apollo-server-* packages also import and re-export `*` from `graphql-subscriptions`. Do they have the same problem? Should they be upgraded too?

**Comment by davedash** [comment]
Thanks for the feedback.

It's definitely not a functionality issue, it's an I can't install this and
keep npm 7.5 happy and to get around it I need to use --force and just pin
the dependencies myself.

**Comment by glasser** [comment]
OK, you piqued my curiosity. Thanks for specifying the npm version. You're right: with npm v7.5.1, running `npm i graphql@15 apollo-server-express` in an empty directory gives an error, and it is in fact related to graphql-subscriptions@1.0.0.

But running `npm i graphql@15 graphql-subscriptions@1.1.0` also gives the same error! It looks like https://github.com/apollographql/graphql-subscriptions/pull/229 has not in fact been published. We'll need to put out a new `graphql-subscriptions@1.2.0` to get this working, I think.

It's the end of my work week but I'll look into it soon... maybe today if publishing g-s is easy enough.

Looking forward to dropping this dependency in AS3 :)

**Comment by glasser** [comment]
OK, I published graphql-subscriptions@1.2.0.

The good news is: I think that's actually good enough to fix the graphql-subscriptions problem. We don't need to change the dependency in apollo-server-express etc: npm is smart enough to find graphql-subscriptions@1.2.0 when you install the current version of apollo-server-express.

The bad news is it isn't good enough.  We get through graphql-subscriptions but get stuck on graphql-upload, where we're using an old major version that doesn't support graphql@15.

I'm going to close this as duplicate of #4865 where I'll work next week to resolve the issue.

**Comment by glen-84** [comment]
> OK, I published graphql-subscriptions@1.2.0.

I think you need to tag the release and update the changelog. 🙂

**Comment by glasser** [comment]
Ah thanks, forgot to push. Got too used to the CircleCI publishing automation we have on our other repos :)

**Comment by davedash** [comment]
Thanks David,

This was extremely helpful.  I will use `--legacy-peer-deps` for now, but
track the saga with core and graphql-upload.


Dave Dash

**Pull request closed without merging**
