### PR TITLE
Added GraphQL Middleware support

### PR DESCRIPTION
**Pull request by maticzav**
TODO:

* [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by maticzav** [comment]
https://github.com/apollographql/apollo-server/pull/1795

#1603

**Comment by edevil** [comment]
This seems great! Any news?

**Comment by abernix** [comment]
Just FYI, we have seen this and it is on our minds; thanks for opening this! We're a bit busy with some other work, even more so as we get closer to GraphQL Summit and in the wake of GraphQL Finland, but we do hope to circle back to this soon!

**Comment by hundsim** [comment]
Any updates/ETA?

**Comment by vroudge** [comment]
Any news on this?

**Comment by thanpolas** [comment]
are we there yet?

**Comment by jashmenn** [comment]
This pull looks good, but unfortunately suffers from the async introspection query introduced by `graphql-middleware`. See: https://github.com/apollographql/apollo-server/issues/1935

**Comment by chanlito** [comment]
Hasn't this been fixed already?

**Comment by maticzav** [comment]
Hey @abernix @martijnwalraven 👋,

I believe everything discussed in the thread has been fixed. Besides that, all the tests passed as well. Could you verify that this is ready to go, and merge if possible? 🙂

**Comment by maticzav** [comment]
@martijnwalraven I believe this extends beyond `fragment` functionality, which we probably both know is not the main reason for you not supporting the addition of the feature. I am sad to see the PR with most ❤️and 👍 being ignored but who am I to judge. You probably know better what the community wants 🙂.

**Comment by egorzaremba** [comment]
Any news on this? I guess it closing feature or probably it will be added?

**Comment by thanpolas** [comment]
@martijnwalraven are you suggesting that apollo will not support middleware out of the box?

**Comment by hwillson** [comment]
As @martijnwalraven mentioned in https://github.com/apollographql/apollo-server/pull/1799#issuecomment-448545801, is there any reason why `graphql-middleware` 3.0.0 can't be used outside of Apollo Server? Adding new dependencies like this (and adjusting the public API to work with them) increases the cognitive and maintenance overhead of a project. Definitely something we're up for doing when there is a clear cut value add, but in this case I'm not seeing how using the approach suggested in this PR:

```js
const { ApolloServer } = require('apollo-server-express');
const { makeExecutableSchema } = require('graphql-tools');
const someMiddleware = require('some-middleware');

const server = new ApolloServer({ 
  typeDefs: '...', 
  resolvers: {...},
  middlewares: [someMiddleware],
});
const app = express();
server.applyMiddleware({ app, path: '/graphql' });
app.listen({ port: 4000 }, () => console.log(`Ready!`));
```

is significantly better than the following approach that can be used currently:

```js
const { ApolloServer } = require('apollo-server-express');
const { makeExecutableSchema } = require('graphql-tools');
const { applyMiddleware } = require('graphql-middleware');
const someMiddleware = require('some-middleware');

const schema = applyMiddleware(
  makeExecutableSchema({ typeDefs: '...', resolvers: {...} }),
  someMiddleware,
);
const server = new ApolloServer({ schema });
const app = express();
server.applyMiddleware({ app, path: '/graphql' });
app.listen({ port: 4000 }, () => console.log(`Ready!`));
```

Am I missing something obvious here?

**Comment by thanpolas** [comment]
> Am I missing something obvious here?

A firm decision. 

Is apollo ever going to support native middleware? (yes/no)

If no, fine.

If yes, the issue is long-term compatibility & sustainability. Let's talk about what the plans are and why this community contribution is not a good fit. @martijnwalraven hinted to possible middleware support but personally, I didn't understand what the concerns are:

>  Even though the core middleware functionality is useful and might be something we'd want to include as part of the request pipeline, we'd want this to be built on a common foundation and avoid features that are not in line with our roadmap like the fragment replacements.

**Comment by martijnwalraven** [comment]
@thanpolas Let me try to clarify my position on this. I think we'll want to add something similar to middleware to the native plugin and request pipeline API at some point, but we're not in a hurry and we would want to understand the use cases better before we commit to an API.

In the meantime, `graphql-middleware` seems like a fine solution, and as @hwillson showed there should be nothing keeping you from using it without the Apollo Server API taking on an additional dependency.

**Comment by piglovesyou** [comment]
Honestly, I would like Apollo Server not to have "native middleware" support. Native middlewares let you integrate features like [`graphql-shield`](https://github.com/maticzav/graphql-shield) and [more](https://github.com/prisma/graphql-middleware#awesome-middlewares-) very casually, but the more you integrate middlewares, the more the behavior becomes away from GraphQL schema you just defined. In other words, how people know your graphql-shield rules by your GraphQL schema? Does your schema can be resolved without HTTP server (with like `apollo-link-schema`)?

Instead of accepting "middlewares", I prefer using GraphQL Directives approach. There's [a good Access Control example by Directives](https://www.apollographql.com/docs/graphql-tools/schema-directives.html#Enforcing-access-permissions) already. But yeah it's not convenient yet (graphql-shield's `and`, `or` and `not`  functions are awesome), so if someone puts `apollo-directives-shield`, I'll get a ton of happiness.

I wonder what others people expect in middlewares. Logging?

**Comment by meodemsao** [comment]
> @martijnwalraven are you suggesting that apollo will not support middleware out of the box?

It's not work with apollo serer 2.x 

```sh

  return ((typeof obj.fragment === 'string' || typeof obj.fragments === 'object') &&
                        ^
TypeError: Cannot read property 'fragment' of undefined
 
```

**Comment by Sytten** [comment]
Will this ever get merged?

**Comment by glasser** [comment]
`graphql-middleware` is a popular and great tool. Apollo Server's current philosophy is to enable users to choose which tools to use when defining their schema rather than trying to bake them into Apollo Server itself; our old batteries-included philosophy essentially led to us being dependent on outdated versions of third-party software for backward-compatibility reasons.  If there's anything about Apollo Server that makes it challenging to wrap a schema using `graphql-middleware` and pass it as the `schema` option to the ApolloServer constructor, we can improve that, but we're not going to add a hard-coded dependency on `graphql-middleware`.

**Pull request closed without merging**
