### PR TITLE
fix(subs): allow additional server variations (e.g., Tls, Http2)

### LINKED ISSUE #4198: subscription server not properly initialized when taking websocket.Server
### What happens
I have an express server running multiple websockets and I'm adding a graphql endpoint with subscription to it. 

I found `installSubscriptionHandlers` took a WebsocketServer but I didn't get any notification, but passing a http server to `installSubscriptionHandlers` works

I found `subscriptions-transport-ws` does not think I'm passing a websocket server on this line
https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/server.ts#L132

And actually it received
```
{
   server: WebSocketServer 
}
```

I used TypeScript and I try to print my argument out in transpiled js files

```js
// server.js
console.error("Whats my wss2? is it instanceof WebSocketServer?", wss2 instanceof ws_1.default.Server);
aserver.installSubscriptionHandlers(wss2);
```
Here I got 
```
 Whats my wss2? is it instanceof WebSocketServer? true
```

```js
// node_modules/apollo-server-core/dist/ApolloServer.js
  installSubscriptionHandlers(server) {
    console.error("let me ask agiain! Whats my wss2? is it instanceof WebSocketServer?", server instanceof ws_1.default.Server);
    console.error("really?????")
    var whatever = new ws_1.default.Server({noServer: true})
    console.error("let me ask this! Whats my whatever? is it instanceof WebSocketServer?", whatever instanceof ws_1.default.Server);
```
here I got

```
 let me ask agiain! Whats my wss2? is it instanceof WebSocketServer? false
 really?????
 let me ask this! Whats my whatever? is it instanceof WebSocketServer? true
```

It does not make sense to me, or is it a common gotcha of `instanceof` ?

### deps

"apollo-server-core":  "2.13.1",

```typescript
import express from "express";
import { ApolloServer, gql } from "apollo-server-express";
import WebSocket from "ws";
import url from "url";
const app = express();
app.set("port", 12345);

const server = app.listen(app.get("port"), () => {});

const typeDefs = gql`

  type Book {
    title: String
    author: String
  }

  type Query {
    books: [Book]
  }
`;

const books = [
  {
    title: "Harry Potter and the Chamber of Secrets",
    author: "J.K. Rowling",
  },
  {
    title: "Jurassic Park",
    author: "Michael Crichton",
  },
];

const resolvers = {
  Query: {
    books: () => books,
  },
};

const aserver = new ApolloServer({ typeDefs, resolvers });

const wss1 = new WebSocket.Server({
  noServer: true,
});

const wss2 = new WebSocket.Server({
  noServer: true,
});

console.error("Whats my wss2? is it instanceof WebSocketServer?", wss2 instanceof WebSocket.Server);
aserver.installSubscriptionHandlers(wss2);

server.on("upgrade", (request, socket, head) => {
  const pathname = url.parse(request.url).pathname;
  if (pathname == "/") {
    wss1.handleUpgrade(request, socket, head, (ws) => {
      wss1.emit("connection", ws, request);
    });
  } else if (pathname == aserver.subscriptionsPath) {
    wss2.handleUpgrade(request, socket, head, (ws) => {
      wss2.emit("connection", ws, request);
    });
  }
});

```

### PR DESCRIPTION
**Pull request by braineo**
fix #4198 

Refer to discussion in the issue please.

### CODE REVIEW

**Comment by jedwards1211** [comment]
Seems like we should check for `HttpsServer` and `Http2Server` as well?

**Comment by braineo** [comment]
Hi @jedwards1211 I have not checked if https or http2 server are supported. Just reading from the function signature typing and seems it only take `http.Server`

```ts
import { Server as HttpServer } from 'http';
/// code
  public installSubscriptionHandlers(server: HttpServer | WebSocket.Server) 
```

**Comment by jedwards1211** [comment]
@abernix I'm guessing when using just JS it's possible to pass an `https.Server` or `http2.Server`?

**Comment by braineo** [comment]
@jedwards1211 Let me know what do you think. Should be easy to add.

**Comment by braineo** [comment]
@jedwards1211 @abernix 

Ok I added type of http2 servers too. Just `http2` module does not expose the class constructor that we cannot use `isInstanceof`

alternatively I used `net.Server` and `tls.Server`, what do you think?

As for the CI, it says

```
FAIL  packages/apollo-gateway/src/__tests__/integration/networkRequests.test.ts (5.838s)
  ● Downstream service health checks › Managed mode › Rolls over to new schema when health check succeeds

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout
```

I am not sure if it is a bug or just time out

**Comment by braineo** [comment]
@jedwards1211 @abernix 

Seems the master branch is failing the same test and probably not introduced by this PR. Would you review or comment anything so that we can merge this PR soon please?

**Comment by jedwards1211** [comment]
?

**Comment by abernix** [comment]
Unintentional closing! Please stand-by: https://github.com/apollographql/apollo-server/issues/4304

**Comment by jedwards1211** [comment]
gotcha, I see hump day decided to celebrate for you

**Comment by braineo** [comment]
@abernix where will be the best place to add?

inside  `packages/apollo-server-integration-testsuite/src/ApolloServer.ts` and add more like this but ignore the `httpServer` pass down from a Promise?

```js
        createApolloServer({
          typeDefs,
          resolvers,
        }).then(({ port, server, httpServer }) => {
          server.installSubscriptionHandlers(httpServer);
```

**Comment by braineo** [comment]
@abernix 

I added test for websocket server.

**Comment by braineo** [comment]
@abernix Ping

**Comment by braineo** [comment]
@abernix  Ping

**Pull request merged**
