### PR TITLE
Expose composed middleware via getMiddleware().

### PR DESCRIPTION
**Pull request by ganemone**
This PR exposes the composed koa middleware via the `server.getMiddleware()` function. This is useful for integrating with systems which may not expose the koa app directly such as Fusion.js. This is an alternative approach to try and resolve some comments on #2244 

* [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by ganemone** [comment]
Anyone have a sec for a review here? This would unblock us from integrating with fusion.js. @martijnwalraven / @benjamn

**Comment by ganemone** [comment]
ping @abernix - any comments?

**Comment by abernix** [comment]
@ganemone Thank you so much for taking the time to put this together — I really respect this alternate approach and plan to get it in.

That said, we need to try to main some API consistency across (at least our most popular) integrations), with Express being the [most pressing](https://npmcharts.com/compare/apollo-server-express,apollo-server-hapi,apollo-server-koa,apollo-server-azure-functions,apollo-server-cloud-functions,apollo-server-cloudflare,apollo-server-fastify,apollo-server-lambda,apollo-server-micro?interval=7).

To maintain that consistency, I took the time to apply the same concept you've used here to `apollo-server-express`.  It seems to work well and I'll be trying to finish that PR that soon, but am a bit limited on time.  If anyone was interested in picking it up and testing it, that could help expedite this and allow us to land with a consistent API.  It also contains an attempt at Hapi, but can't say that's polished yet. 
 Anyhow, my PR is built on top of this PR (and makes a couple changes that I'd have requested), but if anyone is interested in taking a peak, here it is: https://github.com/apollographql/apollo-server/compare/abernix/pr-2435

To be clear, I think Express, Hapi and Koa are the main candidates here.  Other integrations which already have a "handler" are already a bit more "exposed".

Lastly, I'm tempted to call this exposed method `getComposedMiddleware` or _along the lines of `getHighOctaneMiddleware`_, rather than just `getMiddleware`, but curious if anyone has any thoughts here.  Yes, currently there is `applyMiddleware`, but I do see a future where there could be a `getBareMiddleware` (getting the naming and API right here is really my concern) or `applyMiddleware` could _apply_ something more minimal than what it currently does (See also: #2360).

**Comment by ganemone** [comment]
@abernix - I included your changes into this PR. I also looked into hapi but I don't think this pattern makes much sense for hapi because of how hapi has multiple middleware stacks. Express and koa both have a single middleware stack so exposing a composed middleware makes a lot of sense. I understand the desire for API consistency, and this gets us closer to that, but I also think that things will never be 100% identical simply due to the fundamental differences between some of these underlying server abstractions.

**Comment by p4bloch** [comment]
Thank you for this! 🎉

**Comment by abernix** [comment]
Finally landed this in Apollo Server 2.9.0, with some adjustments. 😄 🎉 	

Copying and pasting my comments from https://github.com/apollographql/apollo-server/issues/1308#issuecomment-524430566, since the proposal I mentioned is certainly a direction I see us going, and this seems like a good audience to float it by:

> Ok, after recovering from the need to revert it, the `getMiddleware` bit that I suggested (just) above in [#1308 (comment)](https://github.com/apollographql/apollo-server/issues/1308#issuecomment-507736742) finally landed in Apollo Server 2.9.0 (thanks to #3047). (Finally!)
> 
> That said, I've made a proposal for what I hope is an even better and more flexible/customizable solution in the future. Those subscribers to this issue seem like a relevant audience to solicit for input, so please do take a look at the proposal I put together in #3184! 😄
> 
> (For now, I hope `getMiddleware` will help y'all.)

**Pull request merged**
