### PR TITLE
added a null check for serialized value as well

### PR DESCRIPTION
**Pull request by SarasArya**
I was trying to run this with ioRedis and apollo-graphql-lambda and faced this error .cachePolicy of null. Then I realized that `serializedValue` was being set to Null and what we hoped for was undefined. It seemed pretty trivial to me to have a null check as well. Hence went ahead and added it. Open to discussion and changes if required.

### CODE REVIEW

**Comment by SarasArya** [comment]
Can someone rerun the test cases on Node 6? Seems like they failed even when I have not made any changes to those affected places.
In case there is an issue can someone guide me why that's happening, so that I can fix it. 
Thanks 
@abernix

**Comment by SarasArya** [comment]
@donedgardo will this PR be merged?

**Comment by abernix** [comment]
@SarasArya Are you using a recent version of `apollo-server-cache-redis`?  I feel like this should be guarded by that implementation itself? 

https://github.com/apollographql/apollo-server/blob/112178503611ec1275889cc121f9e43af038825f/packages/apollo-server-cache-redis/src/RedisCache.ts#L40-L47

Also, @donedgardo Isn't able to merge PRs.  They recently opened their own PR for the same reason in https://github.com/apollographql/apollo-server/pull/4085.

**Comment by abernix** [comment]
@SarasArya, thoughts on the above? ☝️   (Also feel free to reply on https://github.com/apollographql/apollo-server/pull/4085 which is the same/similar.)

**Comment by SarasArya** [comment]
@abernix since this is already fixed!! let's go ahead and close this. Apologies, this got somewhere lost in all the notification dump from Github. Thanks to https://github.com/pulls/mentioned I found this!!.

**Pull request closed without merging**
