### PR TITLE
Pass the context along to all the extension methods

### LINKED ISSUE #614: Expose request Object to formatError
I would like to log the request body when an error occurs. This requires access to the request object.

In general, request object often contains additional details that might be desired to be logged, e.g. user session ID.

### LINKED ISSUE #631: Context in formatError
Any way to reach the context inside the `formatError` function? I couldn't find anything about it in the docs.

```ts
export const graphQlRoute = graphqlExpress(req => ({
  schema,
  context: {
    user: req.user
  },
  formatError
}))
```

### LINKED ISSUE #1343: Request: Provide context on global error handlers
It would be very beneficial to have the request context on the global error handlers so we can have better insights as to who caused an error and have a better chance at debugging it.

### PR DESCRIPTION
**Pull request by Whoaa512**
Addresses #1343

With this change you should now be able to implement an extension like so:

```javascript
class MyErrorTrackingExtension extends GraphQLExtension {
    willSendResponse(o) {
        const { context, graphqlResponse } = o

        context.trackErrors(graphqlResponse.errors)

        return o
    }
}
```

TODO:

* [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

Edit by @evans :
fixes #1343
fixes #614 as the request object can be taken from context or from requestDidStart
fixes #631 ""

### CODE REVIEW

**Comment by seromenho** [comment]
Seems that this addresses also:
https://github.com/apollographql/apollo-server/issues/614
https://github.com/apollographql/apollo-server/issues/631

**Comment by evans** [comment]
@Whoaa512 Thank you so much for the PR!

**Comment by martijnwalraven** [comment]
I think there may be an alternative where `context` is an instance property, similar to how we do this for data sources. But let's revisit this when we finalize the API with the new request pipeline.

**Comment by cliedeman** [comment]
Thanks a lot for this change, I am using to try some tracing integration and its working well so far.

Is there any reason the context object was not added to the `parsingDidStart` and `validationDidStart` methods?

**Comment by Whoaa512** [comment]
@cliedeman I think it might have just been on oversight on my part. Feel free to add another PR if your needs require it.

**Comment by cliedeman** [comment]
Thanks, PR #1653 Created

**Comment by ebenoist** [comment]
This is great and will fix issues I'm having with using sentry! Whats the normal release cadence for these things?

**Comment by dauledk** [comment]
Can anyone provide a small example of how to use this? I have not used extensions before - where do you provide them?

**Comment by Whoaa512** [comment]
@dauledk @maimike I wrote a small example of how to use this here: https://github.com/apollographql/apollo-server/issues/1681#issuecomment-422101643

**Comment by twelve17** [comment]
@seromenho could you shed some insight as to how this issue addresses #614 ? I'm not seeing how to access the context from the `formatError` function.

**Comment by seromenho** [comment]
@twelve17 It doesn't expose the context to `formatError` but instead It does expose it to all extension methods. 
Looking at this again and actually it doesn't address #614 directly, I think it is kinda of a workaround. You implement an extension get the errors and the context and do something with them.

**Pull request merged**
