### PR TITLE
Add skipValidation option.

### PR DESCRIPTION
**Pull request by damour**
Sometimes validation takes long time:
https://github.com/graphql/graphql-js/issues/723
We use persisted queries to skip query parse & validate.
Also now this comment will be actual https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/runQuery.ts#L153

TODO:

* [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by Piefayth** [comment]
Closes: #833 #722

**Comment by timrs2998** [comment]
@stubailo any updates? we're interested in this issue too, since we have the same use case as damour

**Comment by damour** [comment]
Rebased. Add jaeger trace with long validation. @stubailo PTAL.

**Comment by tgriesser** [comment]
This PR, or a revert of https://github.com/apollographql/apollo-server/pull/424 in favor of a cleaner solution to handling GET requests would be great to see. 

The validation step can end up taking quite some time relative to the overall request depending on how complex the query is. @stubailo or @helfer anything I can do here to help move this along?

**Comment by evans** [comment]
Thank you! We'll include this in a last release before 2.0

**Comment by jsonbrooks** [comment]
Did this option disappear in 2.0? I can't find it.

**Pull request merged**
