### PR TITLE
fix lamdba reponse type

### PR DESCRIPTION
**Pull request by vcfvct**
currently the response is a string which is not a proper json when return to client side. 
**Before** fix, response looks like:
```json
{
  "statusCode": 200,
  "headers": {
    "Content-Type": "application/json"
  },
  "body": "{\"data\":{\"locations\":[{\"id\":34,\"city\":\"Austin\"},{\"id\":35,\"city\":\"Austin\"},{\"id\":36,\"city\":\"Austin\"},{\"id\":13,\"city\":\"Henrico\"}}]}}"
}
```

Also tools like `Insomnia` cannot fetch and properly parse the schema introspect query. 

**After fix**, response is: 
```
{
  "statusCode": 200,
  "headers": {
    "Content-Type": "application/json"
  },
  "body": {
    "data": {
      "locations": [
        {
          "id": 34,
          "city": "Austin"
        },
        {
          "id": 35,
          "city": "Austin"
        },
        {
          "id": 36,
          "city": "Austin"
        },
        {
          "id": 13,
          "city": "Henrico"
        }
      ]
    }
  }
}
```

### CODE REVIEW

**Comment by abernix** [comment]
@vcfvct What are you using in front of your Lambda? (i.e. What is triggering the Lambda)  Is it AWS API Gateway?  Apollo Engine?  Something else?

**Comment by vcfvct** [comment]
@abernix , i am using this in an corporate internal gateway that invokes lambda. Any issue with that?

**Comment by abernix** [comment]
The current expectation is that the invoker of lambda functions will behave in the same way as [Amazon API Gateway](https://aws.amazon.com/documentation/apigateway/) or [Apollo Engine](https://www.apollographql.com/docs/engine/) — neither of which require the additional parsing.  For example, the raw response back from a Lambda setup with `apollo-graphql-lambda` looks like:

```json
{"data":{"greeting":"Hello, Jesse."}}
```

That is to say, the gateway should only be returning the `body`.

**Comment by vcfvct** [comment]
Got it! I will use my own fork and close this. Thanks!

**Comment by abernix** [comment]
@vcfvct Out of curiosity, can you share what your corporate gateway is (name/product)?  (Understand if you can't!) Even though I'm not sure we can land this right now, I'm interested in considering it still and there's probably a way to expose this through an option.

**Comment by vcfvct** [comment]
@abernix lambda is invoked by an internal gateway, which handles the http request response part, just like what the aws `api gateway`. We are using this in Capital One, a bank 😃. 
Have to go thru internal gateway because the `aws` one is wide open and cannot impose much corporate control.

**Pull request closed without merging**
