### PR TITLE
await shouldReadFromCache and shouldWriteToCache options

### PR DESCRIPTION
**Pull request by centogram**
@glasser here is a potential fix to consider for https://github.com/apollographql/apollo-server/issues/4886

### CODE REVIEW

**Comment by centogram** [comment]
The CLA form is throwing a 500 when trying to complete.

On February 1, 2021 at 9:11:25 PM, 'apollo-cla' via Accounts (accounts@centogram.com) wrote:
@centogram: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

**Comment by glasser** [comment]
@centogram can you share a screenshot? I tested and it worked for me.

**Comment by centogram** [comment]
Hope this helps.  Let me know if its something on my end.

On February 1, 2021 at 9:43:57 PM, 'David Glasser' via Accounts (accounts@centogram.com) wrote:

@centogram can you share a screenshot? I tested and it worked for me.

**Comment by glasser** [comment]
Looking at the logs, I think it's because your GitHub email address contains whitespace.

**Comment by glasser** [comment]
But looking on our server, your CLA is successfully signed (you just don't have a record of it because the email failed, and the bot didn't get up to making the red x into a green check). Future PRs should get the green check though. Will review tomorrow!

**Comment by centogram** [comment]
> Looking at the logs, I think it's because your GitHub email address contains whitespace.

That was it.  I found the oddball email address on my profile, removed it and now the CLA passed as designed.

**Review by u007 — APPROVED** [review]

**Comment by centogram** [comment]
@u007 are you able to cover the test portion.  I'm a bit tied up the next few days.

**Comment by u007** [comment]
okay will try :)

**Comment by u007** [comment]
Hi @centogram ive created a a merge to your branch

https://github.com/centogram/apollo-server/pull/1

**Comment by glasser** [comment]
Thanks @centogram  for the fix, and thanks @u007 for the test! (I hadn't even thought that by selectively returning a promise or a bool, we could have a single hook that tests both sync and async cases — I'll have to remember that trick!)

**Comment by u007** [comment]
thank you @centogram @glasser :)
wondering when will it be released?

**Comment by glasser** [comment]
I have one more change I want to get into v2.20 but hopefully today!

**Comment by u007** [comment]
cool, thank you :)

**Comment by glasser** [comment]
Released in v2.20.0.

**Pull request merged**
