### PR TITLE
centralized “Get Started” Image in the doc

### PR DESCRIPTION
**Pull request by kazuyaseki**
- [x] docs

the image is used in this page
https://www.apollographql.com/docs/apollo-server/

introduction___apollo_server

### CODE REVIEW

**Comment by abernix** [comment]
I appreciate you taking the effort to do so, but the text is now misaligned for me, in both Chrome and Safari.  Something else must be the problem?

### Safari

image

### Chrome

image

**Comment by abernix** [comment]
(Btw, you're correct, it's not perfectly centered, but it's actually leaning _left_ rather than right, for me.)

**Comment by n1ru4l** [comment]
Here is my view OSX 10.13.6 Chrome Version 69.0.3497.100

bildschirmfoto 2018-10-26 um 14 59 37

**Comment by kazuyaseki** [comment]
Thanks for taking time for reviewing!
the difference was due to the default font of my browser. I'm using Japanese as my default language for my Chrome which set the default font to "Hiragino Kaku Go". It became looking ok when I changed the default font to Helvetica

so in the last commit, I made a change to svg to centralize the text no matter which font is used.
here is my view OSX 10.13.4 chrome and safari after the change.

## Chrome (ver. 69.0.3497.100)



## Safari (ver 11.1)

**Comment by abernix** [comment]
Ah, that explains it!  We probably shouldn't have text inside an SVG since I don't believe it will translate with Google Translate (I don't think it supports that?), but this is an improvement regardless.  Thank you very much for taking the time to fix this! 🙏 🎉

**Pull request merged**
