### PR TITLE
Optimize buildQueryPlan when two FetchGroups are on the same service

### PR DESCRIPTION
**Pull request by hugues33**
This PR is to fix issue #3134.

The goal is to limit the number of Fetch to improve performance.

I've made the following modifications in `function splitSubfields`:
When it's an extension field (field defined in an `extend type` in another service):
- when all the required fields are provided by the parent FetchGroup, if the parent FetchGroup is the owning service, it's not necessary to create a new dependant group: just return the parent group.
- when all the required fields are **not** provided by the parent FetchGroup, we need to get the key fields on the base service. If the parent FetchGroup is the base service, it's not necessary to create a new dependant group to add key fields provided by the base service.

In `function splitFields` I removed the special case on Interface type because of the FIXME comment. The general case seems correct to me.

I've not studied all possible cases, but I optimized only use cases I've encountered.

### CODE REVIEW

**Comment by trevor-scheer** [comment]
> The Azure functions link here should have a trailing slash

Resolved here, thanks @trevorblades!
https://github.com/apollographql/apollo-server/pull/3163

**Comment by trevor-scheer** [comment]
This is an excellent contribution, thank you @hugues33! I appreciate your thoroughness and finding/fixing our skipped tests as well.

I've tried updating the `federation/CHANGELOG.md` to save you the trouble, but I'm having git config issues on my end. Would you mind adding an entry there please?

A bit of technical explanation in the PR description would be helpful for future contributors looking back in the history as well.

Thanks again!

**Comment by hugues33** [comment]
Hi @trevor-scheer, thank you for your review.

I've modified the `gateway/CHANGELOG.md` and added some explanations in the PR description.

**Comment by trevor-scheer** [comment]
Thanks again, @hugues33! 🙇

**Pull request merged**
