### PR TITLE
enable setting of content-type

### PR DESCRIPTION
**Pull request by jlally21**
requests were setting `Content-Type` to `application/json`, even if a custom `Content-Type` had been set previously.   This change enables the setting of a custom `Content-Type`, like `application/vnd.api+json`.

Issue: https://github.com/apollographql/apollo-server/issues/2035

### CODE REVIEW

**Comment by saernz** [comment]
Oh thank God, someone made a PR! This is an annoying bug for sure. Please someone merge this! 😛

**Comment by drewbarontini** [comment]
Our team just ran into this issue today, and would love to get this PR merged in. Anything we can do to help push it through?

**Comment by jlally21** [comment]
@drewbarontini  Yes, we would like to get it pushed through as well!   Unfortunately, I am not too familiar with the PR approval process for `apollo-server` as this is the first PR I've opened for this project.  

If anyone has any insight on how to get the PR reviewed and merged in, please let us know!

**Comment by drewbarontini** [comment]
@jlally21 It looks like you need to sign the [Meteor Contributor Agreement](https://contribute.meteor.com/), if you haven't already. And there are a few file conflicts that I'm sure need to be resolved. It looks like the ["Small bug fixes"](https://github.com/apollographql/apollo-server/blob/master/CONTRIBUTING.md#small-bug-fixes) section outlines what needs to be done:

> For a small bug fix change (less than 20 lines of code changed), feel free to open a pull request. We’ll try to merge it as fast as possible and ideally publish a new release on the same day. The only requirement is, make sure you also add a test that verifies the bug you are trying to fix.

So there might need to be a test written for this fix in order to get merged in.

**Comment by wlaaraki** [comment]
Hello guys, any updates on this PR?

**Comment by abernix** [comment]
Thanks so much for submitting this!  I'll get this into an upcoming 2.6.0 alpha real soon.

**Pull request merged**
