### PR TITLE
[apollo-server-lambda] Add support for `isBase64Encoded`

### PR DESCRIPTION
**Pull request by styfle**
This PR adds support for Lambda Proxy when `isBase64Encoded: true`.

The body must be decoded from base64 before parsing JSON.

https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html

### CODE REVIEW

**Comment by styfle** [comment]
@abernix Is there something wrong with Netlify? The previous commit (5935c81) was passing CI but the changelog commit you added (e621ccb) is now failing CI 🤔

**Comment by styfle** [comment]
@abernix Great, thanks!

What's the best way to get notified when this is released?

I subscribed to [GitHub Releases](https://github.com/apollographql/apollo-server/releases) on this repo but it doesn't look like they are used, only tags.

**Comment by abernix** [comment]
@styfle I put it on the milestone (2.16.0) where I believe it'll land.  I _try_ to drop messages on PRs within a release when the release ships, based on that milestone's contents — It's a manual ergonomic, but not usually too hard for me to remember. 😉 

It probably won't be this week — since it'd be great to get a few more things into this release — but I'm trying to get some triaging and releasing done before Tuesday!

**Comment by styfle** [comment]
@abernix Makes sense!

I only see one item in the [2.16.0 Milestone](https://github.com/apollographql/apollo-server/milestone/48) so that should easy enough 😉 

Looking forward to this release, thanks 👍

**Comment by abernix** [comment]
📣 Published in `apollo-server-lambda@2.16.0`!  Thank you for putting this together.

**Comment by krailler** [comment]
Can anyone see #4430?

**Pull request merged**
