### PR TITLE
⚠️ Update the default branch of the Apollo Server repository.

### PR DESCRIPTION
**Pull request by abernix**
This PR changes the default branch of this repository to `main` from its previous name, `master`.  While this could be done exclusively in the UI (and that change has been made already), this is being opened as a PR for a few reasons:

* **Awareness**: Anyone who is routinely developing on this repository should take note of the new branch name, and hopefully this PR makes it clear that it happens (e.g., via repository watcher notifications).
* **Review**: There were a lot of changes to files within this repository (mostly search and replaced, largely related to links in documentation) that relate to this change which are worth reviewing!
* **PR re-targeting**: All of the existing PRs need to be changed to use the new branch name. 
 With the recent introduction of [automatic pull-request retargeting](https://github.blog/changelog/2020-05-19-pull-request-retargeting/) by GitHub, this will happen automatically when this PR is merged.

I've pushed the housekeeping commits to make this change whole to the (no longer default!) `master` branch which this PR is opened from.  There are a couple additional changes which I've put into this PR, mainly around alignment of patterns within this repository and adopting the `directory` notation within `package.json`'s `repository` specifications.  See the individual commits for details.

### CODE REVIEW

**Comment by abernix** [comment]
Well, that did not work as expected.  When this PR merged, many PRs _were_ re-targeted, but _most_ were closed.  I've contacted GitHub Support and am going to open a pinned issue.

**Comment by gentunian** [comment]
did I miss any april's fools?

**Comment by Vultraz** [comment]
I'm curious, what was this change for?

**Comment by gentunian** [comment]
don't say it out loud, but probably has to do with this _rare_ movement that thinks the word "master" refers to slavery.

**Comment by Favna** [comment]
@gentunian you hit the mark. Git and GitHub are reportedly also moving towards releasing an update where this will become standard after said update. It's a ~~dark~~ ~~colourful~~ ~~white~~ rainbow world we live in

**Comment by gentunian** [comment]
Thanks, for sure changing branches naming will make this world a better place. Glad to see this coming.

**Pull request merged**
