### PR TITLE
fix: cache-control for older browsers

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Fixes: https://github.com/apollographql/apollo-server/issues/2605

In older browsers undefined cache-control means it being cached indefinitely (or I'm doing something wrong but as I see other people are experiencing this as well).

This is a draft PR since I'll have to adjust tests for this, so I first want to run this by you all.

### CODE REVIEW

**Comment by abernix** [comment]
Interesting! What's the definition of older browsers here?

**Comment by JoviDeCroock** [comment]
> Interesting! What's the definition of older browsers here?

In my case this bug report came in from an IE11 and a certain version of Edge

**Comment by abernix** [comment]
I see! Do you have any other details from the bug report?  For example, is there a `Last-Modified` header present or an `Expires` header?

Overall though, I think I agree with the idea of ensuring that these are not cached by being more explicit and always providing the `max-age=0` when we've decided that it's not cacheable.  That said, we should be respectful to anything that does check the truthiness of `computeOverallCachePolicy`, such as:

https://github.com/apollographql/apollo-server/blob/d1a0d16065d915e10859934aec808c1fbe3ff9d1/packages/apollo-cache-control/src/index.ts#L164-L173

I believe this change would result in that conditional _always_ being truth-y, so we should just adjust that to not check it conditionally if the result is guaranteed.

Additionally, and probably worth considering, @fabsrc recently opened a PR  (https://github.com/apollographql/apollo-server/pull/2715) which avoided setting `Cache-Control` under error conditions.  I think that having errors not be cacheable makes sense, but perhaps — in a similar way — it would be best to explicitly return `max-age=0` for those cases rather than avoiding the `cache-control` header altogether.

@fabsrc: Do you have thoughts on this?

**Comment by fabsrc** [comment]
I actually also came across this issue recently when I was configuring a CDN. Apollo not sending a `Cache-Control` header if the GraphQL response is not cachable meant that I had to set the default cache time to `0`. 

So I like the idea of being more explicit here and always send a `Cache-Control` header (if `calculateHttpHeaders` is set to `true`). Of course this should then also be sent if the GraphQL response contains errors.

You could also consider using `no-cache, no-store, must-revalidate` instead of `max-age=0` (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control).

**Comment by jimsorock** [comment]
Is this fix not happening? Has it happened elsewhere?  Thanks!

**Comment by JoviDeCroock** [comment]
@jimsorock I'm going to close this, my PR section is getting crowded and this does not seem to gain traction

**Comment by abernix** [comment]
I'm very much in favor of the direction noted in https://github.com/apollographql/apollo-server/pull/2675#issuecomment-496616878 if someone is willing and able to pick this up!

**Pull request closed without merging**
