### PR TITLE
Add missing options for subscription server

### PR DESCRIPTION
**Pull request by nuragic**
Add `onOperation` and `onOperationComplete`.

### CODE REVIEW

**Comment by nuragic** [comment]
Sorry for the noise on the force pushed commits! I was trying to publish my fork (this same branch) to npm (my account) in order to be able to install this version directly in our packages... however I found the process really troublesome... so for now, as we _need_ these options for implementing custom monitoring (start/stop transactions, etc), my solution is to temporally opt out of using the `new ApolloServer({ ... })` constructor until this PR would be merged...

Please let me know if something is missing or you need any tests, whatever.

Thanks!

**Comment by abernix** [comment]
Are these missing in a sense that _you needed them and the configuration points didn't exist so you added them_, or missing in the sense of _they were supposed to exist because of some circumstantial longer-standing reason_?

**Comment by nuragic** [comment]
@abernix Hi! I mean that currently, if you use the `new ApolloServer({ subscriptions: { ... } })` is not possible to pass your own functions for `onOperation` and `onOperationComplete`; is it possible however if you use the `new SubscriptionServer({ ... })` constructor: https://github.com/apollographql/subscriptions-transport-ws#constructoroptions-socketoptions--socketserver

So _missing_ in the sense that the `subscription` object of the `ApolloServer` constructor doesn't accept the same options as the `SubscriptionServer` constructor.

**Comment by nuragic** [comment]
@abernix Hi! Why closed? Has been already fixed by another commit? Thanks

**Comment by glasser** [comment]
Direct subscriptions integration was removed from Apollo Server in v3 last year. (Partially because of how the old flimsy integration led to problems like this one.)

**Pull request closed without merging**
