### PR TITLE
Adds cors options available to configure

### PR DESCRIPTION
**Pull request by alvincrespo**
## Changes

- Adds `cors` options that can exist on the object for configuration, per https://github.com/apollographql/apollo-server/blob/6ffec8e4535946289f724451aed8b2ade966cac5/packages/apollo-server-azure-functions/src/ApolloServer.ts#L13-L20

I am unsure what the proper format for the documentation should be. Please let me know and I'll make the appropriate updates.

### CODE REVIEW

**Comment by abernix** [comment]
This is a really valuable addition.  Sadly, though this **might** be a subset of all possibilities, it is certainly not the super-set of the possible options, since these are actually integration specific (e.g. Azure, Express, Lambda, Fastify, etc.).

Therefore, I'd like to explicitly double check before we land this so we don't misguide someone on this security sensitive feature.  Are you able to spend a few minutes and check through the various options and boil them down to the subset of options and then add a note that says, e.g., "Additional options may be available depending on an integrations CORS implementation"?

For example, `apollo-server-express` uses `cors`'s `CorsOptions`:

https://github.com/apollographql/apollo-server/blob/49cd7332edc5d36f05b4aabd67d123cab688383e/packages/apollo-server-express/src/ApolloServer.ts#L27

...which can be found in DefinitelyTyped types [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cors/index.d.ts#L16-L23).

And Hapi uses `hapi.RouteOptionsCors`:

https://github.com/apollographql/apollo-server/blob/49cd7332edc5d36f05b4aabd67d123cab688383e/packages/apollo-server-hapi/src/ApolloServer.ts#L151

...which is found in [this definition file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hapi/index.d.ts#L1242-L1274).

Do you mind taking a look?  As for formatting, I'd probably backtick most of the bits!

**Comment by alvincrespo** [comment]
@abernix Thanks for the awesome feedback - this totally helps! Yes, I'll take a look at a few of these and see whats common among them - something I didn't think about originally. This would be super confusing for folks if added as is.

What do you think if we just add links to the definition types, like this:

<hr>

For configuration options specific to your setup, check out:

- [Express](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cors/index.d.ts#L16-L23)
- [Hapi](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cors/index.d.ts#L15-L24)

Don't see your configuration listed here? Additional options may be available depending on an integrations CORS implementation.

**Comment by abernix** [comment]
@alvincrespo Your suggestion sounds spot on.  Thanks for looking into it!

**Comment by abernix** [comment]
Any updates on this, @alvincrespo?

**Comment by glasser** [comment]
As @abernix described above, it's challenging that Apollo Server pretended to have a single cross-web-integration API around things like `cors` when different integrations actually function differently. We have fixed this in AS4 (currently a Release Candidate) by removing the built-in support for CORS configuration and instead allowing users to treat Apollo Server like a normal middleware that can be combined with your framework's CORS middleware directly. Sorry for the delay!

**Pull request closed without merging**
