### PR TITLE
add azure function examples

### PR DESCRIPTION
**Pull request by ErickWendel**
Signed-off-by: Erick Wendel <erick.workspace@gmail.com>

**#2130** 

TODO:

* [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [x] Make sure all of the significant new logic is covered by tests
* [x] Rebase your changes on master so that they can be merged easily
* [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by ErickWendel** [comment]
Anyone could see this PR?

**Comment by abernix** [comment]
Hi @ErickWendel.  Thanks for the PR! Most of the team has been enjoying some time off during the holidays.  We'll get to reviewing this as soon as possible.

**Comment by abernix** [comment]
Also, @michael-watson is still out, but I'm particularly interested in their input on this as they'd been working diligently on some Azure Functions stuff in December.

**Comment by ErickWendel** [comment]
Hi guys, anyone  could review this PR ?

**Pull request merged**
