### PR TITLE
Handle Errors with circular references gracefully

### LINKED ISSUE #1433: Throwing circular object in resolver breaks apollo-server (500 HTTP error)
OK, so the title isn't 100% accurate. Putting this code in a resolver:

```
await axios.zeit.post('/v2/domains/salamander.ai/records', {
  name: subdomain,
  type: 'A',
  value: instanceUrl
})
```

Lead to this error when the request failed (printed in console & returned to client):

```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at prettyJSONStringify (/home/ashton/code/6labs/packages/salamander-apollo/node_modules/apollo-server-core/dist/runHttpQuery.js:19:17)
    at Object.<anonymous> (/home/ashton/code/6labs/packages/salamander-apollo/node_modules/apollo-server-core/dist/runHttpQuery.js:297:33)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ashton/code/6labs/packages/salamander-apollo/node_modules/apollo-server-core/dist/runHttpQuery.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I wanted to simplify a bit so came up with this, but it worked fine (good error with `message === "[Object object]"`):

```
const a = {}
const b = {a}
a.b = b
throw a
```

Not sure why the first thing is bad but second is OK.

FYI I'm using `apollo-server-express@2.0.0-rc.5`

### PR DESCRIPTION
**Pull request by mdlavin**
Fixes #1433 

TODO:
* [X] Update CHANGELOG.md with your change (include reference to issue & this PR)
* [X] Make sure all of the significant new logic is covered by tests
* [X] Rebase your changes on master so that they can be merged easily
* [X] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by mdlavin** [comment]
Looking at the error in the linting build, I don't believe that I introduced this problem. 

@martijnwalraven / @abernix if you'd like me to take a different approach fixing this problem, I'm happy to update the code. Just let me know what I can do

**Comment by mdlavin** [comment]
I rebased on master with hope that it would fix the linting failure in the last commit

**Comment by mdlavin** [comment]
I figured out the issue with the linting failures. It was a problem in the `package-lock.json` file that I fixed.

**Comment by mdlavin** [comment]
@martijnwalraven @abernix is there anything I should change about this PR?

**Comment by martijnwalraven** [comment]
@mdlavin Sorry about the radio silence, but both @abernix and myself have been preoccupied with other (but related!) projects. Although I realize circular references in errors can be a problem, it should never actually get to the point that we try to serialize these. That seems like a mistake in the current implementation. 

We've experimented with making some related changes [on a separate branch](https://github.com/apollographql/apollo-server/tree/response-with-formatted-errors), getting rid of `FormatErrorExtension` altogether and clarifying the behavior of `formatError`. In short, errors should always be formatted before a response is serialized, respecting the contract of [`formatError` in `graphql-js`](https://github.com/graphql/graphql-js/blob/master/src/error/formatError.js), which means circular fields in `Error` instances shouldn't become part of the `GraphQLFormattedError` we serialize.

**Comment by mdlavin** [comment]
I'm happy to hear that the problem is getting fixed and I'm not attached to my version of the fix =). Is there hope for your branch merging soon or would be make sense to merge this fix now so that people are unblocked quickly?

**Comment by mdlavin** [comment]
@martijnwalraven any updates on your new branch? I'd love to help get this problem fixed if I can. I run into it daily and it's making my server return 500s =(. 

If there is anything I can do, please point me at the work. I'm happy to fix whatever is needed.

**Comment by martijnwalraven** [comment]
@mdlavin That work was part of https://github.com/apollographql/apollo-server/pull/2574 and has recently been merged into https://github.com/apollographql/apollo-server/pull/2482. Could you try and see if `2.5.0-alpha.6` solves your issue?

**Comment by mdlavin** [comment]
I tested with `2.5.0-alpha.6` and I still see "Converting circular structure to JSON" errors in the log that I did before. I don't notice any improvement in the alpha release

**Comment by mdlavin** [comment]
I rested this with `2.5.0-rc.0` and it still throws "Converting circular structure to JSON" errors. @martijnwalraven did you expect this to be fixed?  I can fix the merge conflicts and update this PR if you'd like me to

**Comment by mdlavin** [comment]
I rested this with 2.5.0 and it still throws "Converting circular structure to JSON" errors. @martijnwalraven did you expect this to be fixed? I can fix the merge conflicts and update this PR if you'd like me to

**Comment by abernix** [comment]
I've commented with some thoughts on the original issue https://github.com/apollographql/apollo-server/issues/1433#issuecomment-493202449.

**Comment by abernix** [comment]
Thank you for opening this originally, and thank you _very much_ for the excellent [reproduction](https://github.com/mdlavin/graphql-circular-error-axios) you provided in https://github.com/apollographql/apollo-server/issues/1433#issuecomment-494368741.

That said, I think this PR is no longer necessary with the notes I've left in https://github.com/apollographql/apollo-server/issues/1433#issuecomment-514773285.  I hope you'll understand this approach and find this satisfactory!

**Pull request closed without merging**
