### PR TITLE
enable async in formatError hook

### PR DESCRIPTION
**Pull request by anymost**
[feature] enable async in formatError hook
[https://github.com/apollographql/apollo-server/issues/1747](url)

### CODE REVIEW

**Comment by anymost** [comment]
@martijnwalraven  Hi，The reason why I use async/await in formatError is we have so internal tools. The tools are used to report error and so on,  But most tools are run async asynchronously, so I want to formatError support asynchronous logic.

**Comment by anymost** [comment]
meantime, formatResponse hook support async/await, I take formatError hook supporting async/await for granted

**Comment by eltonio450** [comment]
@martijnwalraven we also use async function to log errors (via Sentry), and would like to use the formatError hook to do so. 

Do you think this PR is going to be merged in master in the future ?

thank you !!

**Comment by eltonio450** [comment]
(to be even more specific, we use the serverless version of apollo server, and everything needs to be handled before the return. For now, we receive empty errors + erros are not reported in sentry

**Comment by abernix** [comment]
Thanks for opening this originally.

As of https://github.com/apollographql/apollo-server/pull/2719 (which is included in the latest `alpha` releases of Apollo Server 2.6.0 on the `next` npm `dist-tag`; tracked in #2669) we now include a `didEncounterErrors` life-cycle hook as part of the request pipeline events.  It supports `async` so should hopefully be exactly what you need in order to implement this and cover this use-case.  Please let us know if this doesn't tick that box!

**Pull request closed without merging**
