### PR TITLE
Add graphql dependency to server integrations

### LINKED ISSUE #1225: Apollo Server 2: Is graphql dependency needed in integrations?
After installing `apollo-server-lambda`, I saw warnings about a missing peer dependency: `graphql`. I haven’t seen anywhere in the `apollo-server-lambda` docs that `graphql` needs to be installed along with it, so I took a look at the code. **I see that `apollo-server-core` has `graphql` In its [peer dependencies](https://github.com/apollographql/apollo-server/blob/ebacd8fcda15c10bc4b950e894ad1815577fc072/packages/apollo-server-core/package.json#L65), but none of the apollo server variants that depend on the core (express, hapi, lambda, etc.) install `graphql` along with it. Should `graphql` be a dependency of `apollo-server-<variant>`? Or should it be installed by the end user, along with `apollo-server-<variant>`?** (If it’s the latter, then maybe `graphql` should be a peer dependency of the variant packages, as it's the case for `apollo-server`).

Thanks, and please accept my apologies if I missed something!

### PR DESCRIPTION
**Pull request by olistic**
Fixes #1225

### CODE REVIEW

**Comment by evans** [comment]
@olistic Thank you so much for the PR! It would be better if graphql is a peer dependency of the integrations, so that a single version of graphql can be installed for the full package. Something like [this line](https://github.com/olistic/apollo-server/blob/6379c338aa3b3b587783cc97057fbf9bdb9e3ebe/packages/apollo-server-core/package.json#L65) would be incredible

**Comment by olistic** [comment]
Ups! I misunderstood [your comment](https://github.com/apollographql/apollo-server/issues/1225#issuecomment-399538792). What about `apollo-server-integration-testsuite`? Do we want the peer dependency there as well?

**Comment by evans** [comment]
@olistic The integration testsuite is a private package to the repository, so it doesn't need the peerDeps. Thank you so much for the PR!

**Comment by abernix** [comment]
The `graphql@14` package is still a [release-candidate](https://github.com/graphql/graphql-js/blob/4f92f55a74477fde3b00eb99f9a37f1ff2d1bd0d/package.json#L3) (also, [on npm](https://www.npmjs.com/package/graphql)) and utilizes [semver "pre-release"](https://docs.npmjs.com/misc/semver#prerelease-tag) versioning.  This means the version range defined here only meets a version of `graphql` that hasn't been released yet.  While that may seem like a forward-thinking idea, I'd caution against doing this until compatibility has been verified since offering it as a "peer dependency" today seems like an endorsement for its use.

**Pull request merged**
