### PR TITLE
Update heroku.md for deployment

### PR DESCRIPTION
**Pull request by emmadal**
to deploy the GraphQL server on Heroku with apollo server, we must set the NODE_ENV to `development`. why? because when the NODE_ENV is set to production we cannot access to the playground graphql and we always to get this error ``GET query missing```, but when the NODE_ENV is set to `development`, the graphql playground appears and we can enjoy of this interface

### CODE REVIEW

**Comment by axelvaindal** [comment]
> to deploy the GraphQL server on Heroku with apollo server, we must set the NODE_ENV to `development`. why? because when the NODE_ENV is set to production we cannot access to the playground graphql and we always to get this error ``GET query missing```, but when the NODE_ENV is set to `development`, the graphql playground appears and we can enjoy of this interface

Well, no.
The reason graphlq playground and introspection are not working on your heroku deployment with `NODE_ENV` set to `production` is because they are disabled by default with the production mode of `apollo-server`. You can still enable them in your `ApolloServer` configuration if needed (see [here](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#constructoroptions-apolloserver)). Production mode for `apollo-server` is `NODE_ENV` based, so `production` value is mandatory.
Thus, the docs are correct and shouldn't be modified.

If you're looking to make a deployment on `heroku` with production mode on for `apollo-server`, there is no other way (afaik) :slightly_smiling_face: .
You can still deploy with `NODE_ENV` set to `development`, `staging` or any other value that suits you, but production mode wouldn't not be available in this case.

**Comment by emmadal** [comment]
ok i understand. thank you for the clarity. Thank you so much😊😊

**Comment by emmadal** [comment]
thank you so much for the clarity <3

**Comment by axelvaindal** [comment]
No problem.
When in doubt, don't hesitate to ask on [StackOverflow](https://stackoverflow.com/) or to the community for help and open an issue if you're sure there is a bug before opening a PR. 
This should help the maintainers of this project.

Can you please close the current PR as it's not necessary anymore ? :slightly_smiling_face:

**Pull request closed without merging**
