### PR TITLE
feat: support customizing micro request body parsing options

### PR DESCRIPTION
**Pull request by marbemac**
These changes make it possible to customize the micro request body parsing options by introducing two new options - `requestBodyLimit` and `requestBodyEncoding`. These options get passed through to `json.limit` and `json.encoding` (https://github.com/zeit/micro#api).

Usage looks like this:

```ts
const apolloServer = new ApolloServer({
  // ... existing options
});

return new http.Server(
  apolloServer.createHandler({
    requestBodyLimit: '10mb',
    requestBodyEncoding: 'utf8',
  }),
);
```

This is not a breaking change - both options are optional.

### CODE REVIEW

**Comment by jaymaycry** [comment]
Ran into the same issue.. waiting for this @marbemac @apollo-cla

**Comment by filipebarcos** [comment]
@apollo-cla @jaymaycry I'd love to get this in too. PR is ready to review/merge.

**Comment by Nezteb** [comment]
@jaymaycry @abernix It's been 11 months since the last update to this PR; have there been any updates on this?

There's no major rush, I just wanted to check, thank you!

**Comment by glasser** [comment]
Apollo Server 4 (currently a Release Candidate) no longer attempts to wrap framework-specific body-parsing APIs at all, so changes like this are no longer needed. (Additionally, we no longer maintain web framework integrations as part of the core project other than the Express middleware; Micro users will be able to build their own integration using the new stable integration API.) Sorry for the delay!

**Pull request closed without merging**
